"""Deterministic KickAssembler export for 19656 level packages.

Each level exports a directory of five includes:
    stage_config.asm    constants: height, scroll divider, terrain palette
    stage_charset.asm    the level's own terrain glyph bitmaps + TERRAIN_GLYPH_COUNT
    stage_map.asm        metatileDefs (from the level tileset) + stageMetatileRows
    stage_turrets.asm    TURRET_TOTAL + turretCols/turretRows (desc by world row)
    (no waves file -- encounter data is level-package bytes; see WAVES below)

Gameplay imports one level's directory (level1/); other levels coexist on disk
unreferenced. Re-running the exporter is byte-identical.
"""
from pathlib import Path

from engine_data import (
    METATILE_NAMES,
    METATILES_PER_ROW,
    TERRAIN_GLYPH_BASE,
    TURRET_POOL,
)
from project import (
    ProjectValidationError,
    composition_size,
    iter_turrets,
    turret_world_col,
    turret_world_row,
    validate_project,
)

CONFIG_NAME = "stage_config.asm"
CHARSET_NAME = "stage_charset.asm"
# THE MAP FILE IS stage_map.asm. It was stage_test.asm when the map was a test
# fixture assembled into the engine PRG; it is now level content split by the
# Makefile into the two halves the level package emits at $e000 and $f130.
STAGE_NAME = "stage_map.asm"
TURRETS_NAME = "stage_turrets.asm"
# THERE IS NO WAVES FILE. Encounter data ships as bytes in the level package and
# is authored in src/wave_programs.asm and src/wave_encounters.asm; the renderer
# that used to emit stage_waves.asm spoke the retired attack-catalogue contract
# and has been removed with it. Encounter export arrives in Contract v2 Phase 3.


def _byte_line(values, comment=None):
    body = ",".join(f"{value:3d}" for value in values)
    line = f"    .byte {body}"
    if comment:
        line += f"   // {comment}"
    return line


def _require_valid(project):
    errors = validate_project(project)
    if errors:
        raise ProjectValidationError("\n".join(errors))


def _sorted_turrets_desc(project):
    """Turrets as (world_row, world_col), sorted DESCENDING by world row - the
    order gameplay's downward-scrolling SCROLL_ROW crosses them, which the engine
    streaming cursor walks."""
    entries = [
        (turret_world_row(t["metatileRow"]), turret_world_col(t["metatileCol"]))
        for t in iter_turrets(project)
    ]
    entries.sort(key=lambda rc: (-rc[0], rc[1]))
    return entries


# --- individual includes -------------------------------------------------------

def render_stage_config(project):
    _require_valid(project)
    p = project.palette
    glyph_count = len(project.tileset["glyphs"]) if project.tileset else None
    metatile_count = len(project.tileset["metatileDefs"]) if project.tileset else None
    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        "//",
        "// CONSTANTS-ONLY level-config include. Emits no bytes, no memory segment,",
        "// no program-counter change. Imported very early so every level-owned",
        "// constant exists before the engine constants/code that consume them.",
        "//",
        "// Ownership: these values belong to the level package, NOT to the engine.",
        "// The engine derives STAGE_LOGICAL_ROWS = STAGE_METATILE_ROWS * METATILE_H",
        "// and METATILE_DEF_COUNT = STAGE_METATILE_COUNT (the level's metatile-def",
        "// table is variable length: STAGE_METATILE_COUNT * 16 bytes, 1..64).",
        "//   TERRAIN_BACKGROUND_COLOUR -> $D021",
        "//   TERRAIN_MC_COLOUR_1       -> $D022   (multicolour bit-pair 01)",
        "//   TERRAIN_MC_COLOUR_2       -> $D023   (multicolour bit-pair 10)",
        "//   TERRAIN_CHARACTER_COLOUR  -> colour RAM low 3 bits (bit-pair 11)",
        "// TERRAIN_GLYPH_COUNT is level-owned too (the tileset lives in",
        "// stage_charset.asm); it is declared here so the engine's early glyph-",
        "// namespace guards resolve before the byte block is imported.",
        "// ============================================================================",
        f".const STAGE_METATILE_ROWS     = {project.height}",
        f".const SCROLL_FRAME_DIVIDER    = {project.scroll_frame_divider}",
        *([f".const STAGE_METATILE_COUNT   = {metatile_count}"] if metatile_count is not None else []),
        f".const TERRAIN_BACKGROUND_COLOUR = {p['background']}",
        f".const TERRAIN_MC_COLOUR_1     = {p['multicolour1']}",
        f".const TERRAIN_MC_COLOUR_2     = {p['multicolour2']}",
        f".const TERRAIN_CHARACTER_COLOUR = {p['character']}",
        ".const TERRAIN_COLOUR_RAM      = 8 | TERRAIN_CHARACTER_COLOUR",
    ]
    if glyph_count is not None:
        lines.append(f".const TERRAIN_GLYPH_COUNT     = {glyph_count}")
    lines.append("")
    return "\n".join(lines)


def render_stage_charset(project):
    """The level's own terrain glyph bitmaps. This is the swappable tileset unit
    (up to 1024 bytes): char codes TERRAIN_GLYPH_BASE .. TERRAIN_GLYPH_BASE+COUNT-1
    ($3B00..). A future multiload transition replaces exactly this block."""
    _require_valid(project)
    if not project.tileset:
        raise ProjectValidationError("Level has no tileset; cannot render stage_charset.asm.")
    glyphs = project.tileset["glyphs"]
    count = len(glyphs)
    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        "//",
        "// LEVEL-OWNED terrain glyph bitmaps - the swappable tileset unit. Codes",
        f"// {TERRAIN_GLYPH_BASE}..223 are the permanent terrain glyph namespace",
        f"// ($3B00-$3EFF, 128 slots); this level authors the first {count}.",
        "// initBackground copies TERRAIN_GLYPH_COUNT glyphs (declared in",
        "// stage_config.asm) to $3B00. A future multiload transition replaces",
        "// exactly this byte block.",
        "// ============================================================================",
        "terrainGlyphs:",
    ]
    for i, glyph in enumerate(glyphs):
        lines.append(_byte_line([b & 0xFF for b in glyph], f"code {TERRAIN_GLYPH_BASE + i}"))
    lines.extend([
        "terrainGlyphsEnd:",
        ".if (terrainGlyphsEnd - terrainGlyphs != TERRAIN_GLYPH_COUNT * 8) {",
        '    .error "terrainGlyphs data size does not match TERRAIN_GLYPH_COUNT * 8"',
        "}",
        "",
    ])
    return "\n".join(lines)


def render_stage_asm(project, metatiles=None):
    _require_valid(project)
    if project.tileset:
        defs = project.tileset["metatileDefs"]
    elif metatiles is not None:
        defs = metatiles
    else:
        raise ProjectValidationError("render_stage_asm needs a tileset or an explicit metatiles list.")
    lines = [
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        f"// {project.height} metatile rows x {METATILES_PER_ROW} columns.",
        "// Terrain colour is level-global; there is intentionally no per-cell colour table.",
        "// ============================================================================",
        "",
        "metatileDefs:",
    ]
    for tile_id, tile in enumerate(defs):
        name = METATILE_NAMES[tile_id] if tile_id < len(METATILE_NAMES) else f"M{tile_id}"
        lines.append(_byte_line(tile, f"M{tile_id} {name}"))
    lines.extend(["METATILE_DEFS_END:", "", "stageMetatileRows:"])
    for row_index, row in enumerate(project.metatile_rows):
        lines.append(_byte_line(row, f"row {row_index}"))
    lines.extend([
        "STAGE_METATILE_ROWS_END:",
        "// Size/memory guards remain engine-owned immediately after this include.",
        "",
    ])
    return "\n".join(lines)


def render_stage_turrets(project):
    """Authored turret PLACEMENT only. Behaviour stays engine-owned.

        .const TURRET_TOTAL          authored count (0..255)
        .var   turretCols            world CHARACTER columns
        .var   turretRows            world CHARACTER / logical rows (16-bit safe)

    Sorted DESCENDING by world row (streaming-cursor order). Authoring order is
    irrelevant to the output."""
    _require_valid(project)
    entries = _sorted_turrets_desc(project)
    rows = [r for r, _ in entries]
    cols = [c for _, c in entries]
    add_cols = f".add({', '.join(str(c) for c in cols)})" if cols else ""
    add_rows = f".add({', '.join(str(r) for r in rows)})" if rows else ""
    return "\n".join([
        "// ============================================================================",
        "// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.",
        f"// Level: {project.name}",
        "//",
        "// Authored turret PLACEMENT layer. Constants + assembler lists only.",
        "// PLACEMENT is editor-owned; BEHAVIOUR stays engine-owned",
        "// (src/background_turrets.asm). The engine streams these through a fixed",
        f"// pool of {TURRET_POOL} live glyph slots as SCROLL_ROW crosses them.",
        "//   world row = metatileRow * 4 + 1     world col = metatileCol * 4 + 1",
        "//   values above 255 are supported (16-bit world rows).",
        "// ============================================================================",
        f".const TURRET_TOTAL = {len(entries)}",
        f".var turretCols = List(){add_cols}",
        f".var turretRows = List(){add_rows}",
        "",
    ])


# --- level export ------------------------------------------------------------

def export_level(project, output_dir, *, engine_data=None, metatiles=None):
    """Write the four generated includes for one level package.

    Returns them in canonical order (config, charset, map, turrets). It used to
    return five and also write a stage_waves.asm; see the WAVES note above.

    THIS IS THE v5 EXPORTER, kept for the existing GUI and its tests. The v6
    Contract v2 exporter is tools/level_editor/export_v6.py, which takes a
    ProjectV6, requires an explicit destination and refuses an invalid project.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / CONFIG_NAME
    charset_path = output_dir / CHARSET_NAME
    stage_path = output_dir / STAGE_NAME
    turrets_path = output_dir / TURRETS_NAME
    config_path.write_text(render_stage_config(project), encoding="utf-8")
    charset_path.write_text(render_stage_charset(project), encoding="utf-8")
    stage_path.write_text(render_stage_asm(project, metatiles), encoding="utf-8")
    turrets_path.write_text(render_stage_turrets(project), encoding="utf-8")
    return config_path, charset_path, stage_path, turrets_path


def export_project(project, metatiles, output_dir):
    """Back-compat 3-file export (config, stage, turrets) into a single dir.
    Prefer export_level for the full level package."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / CONFIG_NAME
    stage_path = output_dir / STAGE_NAME
    turrets_path = output_dir / TURRETS_NAME
    config_path.write_text(render_stage_config(project), encoding="utf-8")
    stage_path.write_text(render_stage_asm(project, metatiles), encoding="utf-8")
    turrets_path.write_text(render_stage_turrets(project), encoding="utf-8")
    return config_path, stage_path, turrets_path
