#!/usr/bin/env python3
"""AUTHORABLE DROPPER MOVEMENT: schema, migration, validation, export, preview.

    A Dropper Trigger owns its Dropper's PATH. `dropper_program` is None for the
    hard-coded three-pass flight in src/dropper.asm -- which is what every
    project authored before this field existed means -- or the id of a movement
    program that MEMBER 0 flies on the ordinary movement engine.

The runtime half is proved on the emulator in
tests/test_dropper_movement_program.py. This proves everything between the
author's fingers and the generated bytes:

    * a project with no field at all opens as Legacy, and stays Legacy;
    * both selections survive save, reload, export and re-import;
    * a Dropper Trigger draws and spawns exactly ONE object;
    * a dangling, renamed or deleted reference is an ERROR, not a guess;
    * capacity is DERIVED from the record size, so the tenth column's cost is
      computed and not restated;
    * the preview draws both modes and its cache notices every parameter that
      changes the Dropper's geometry -- including the two that arrived with it.

NOTHING PRODUCTION IS WRITTEN. Every save and export goes to a temporary
directory; the committed level documents and the shared library are byte-compared
at the end.

THE WIDGET SECTION NEEDS A WORKING TK. Run it with an interpreter that has one:

    /usr/local/bin/python3 tools/level_editor/test_dropper_movement.py
"""
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import asm_decl                                                  # noqa: E402
import contract_v2 as C                                          # noqa: E402
import export_v6                                                 # noqa: E402
import fixtures_v6                                               # noqa: E402
import import_engine_v6 as I                                     # noqa: E402
import movement_sim as ms                                        # noqa: E402
import project_v6                                                # noqa: E402
from controller_v6 import EditorController                        # noqa: E402
from project_v6 import ProjectV6, Trigger                         # noqa: E402
from validation_v6 import validate                                # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
CANON = HERE / "levels" / "level1" / "level.v6.json"
LIB = HERE / "encounter_library.v6.json"

CANON_BYTES = CANON.read_bytes()
LIB_BYTES = LIB.read_bytes()

PASS, FAIL = [], []


def ok(m, x=""):
    PASS.append(m)
    print(f"ok  - {m}" + (f"  [{x}]" if x else ""))


def check(m, c, x=""):
    if c:
        ok(m, x)
    else:
        FAIL.append(m)
        print(f"FAIL- {m}" + (f"  [{x}]" if x else ""))


def dropper_fixture():
    """A project whose last trigger is a Dropper, with two programs to choose.

    SYNTHETIC, AND DELIBERATELY SO: the cases below need a Dropper trigger, a
    non-Dropper trigger and at least two movement programs, and none of that is
    the campaign's business. fixtures_v6 carries two programs already.
    """
    p = fixtures_v6.shared_wave()
    p.triggers[-1].species = "DROPPER"
    return p


def dropper_index(p):
    return next(i for i, t in enumerate(p.triggers)
                if C.identity_behaviour(t.species) == C.BEHAVIOUR_DROPPER)


def other_index(p):
    return next(i for i, t in enumerate(p.triggers)
                if C.identity_behaviour(t.species) != C.BEHAVIOUR_DROPPER)


# ===========================================================================
# 1. THE FIELD, AND WHO OWNS IT
# ===========================================================================
print("\n=== the Dropper's path is a trigger field ===")
t = Trigger(world_progress=10, wave_definition="w")
check("a Trigger owns a Dropper movement program", hasattr(t, "dropper_program"))
check("...and it defaults to the legacy flight", t.dropper_program is None)
check("...which it says in as many words", t.dropper_is_legacy)
d = project_v6.WaveDefinition(id="w", count=3, movement_program="p")
check("a WaveDefinition does NOT own one -- it paths the ESCORTS",
      not hasattr(d, "dropper_program"))
check("...and still owns exactly ONE movement program, so there is no second "
      "wave-definition selector",
      hasattr(d, "movement_program")
      and len([k for k in d.to_dict() if "rogram" in k]) == 1,
      ", ".join(k for k in d.to_dict() if "rogram" in k))

fmt = asm_decl.parse_files([REPO / "src" / "encounter_format.asm"])
check("the engine declares the same sentinel, readably",
      fmt.const("TRIG_DROP_LEGACY") == C.TRIG_DROP_LEGACY,
      f"${C.TRIG_DROP_LEGACY:02x}")
# THE SENTINEL CANNOT ALIAS A REAL OFFSET, and the proof is arithmetic rather
# than a promise: a program ends in a WM_STAGE_SIZE-byte EXIT record inside a
# LEVELPKG_MOVE_MAX-byte pool, so no program can START above MOVE_MAX - 4.
check("...and it is past the highest offset any program could start at",
      C.TRIG_DROP_LEGACY > C.LEVELPKG_MOVE_MAX - C.WM_STAGE_SIZE,
      f"${C.TRIG_DROP_LEGACY:02x} > {C.LEVELPKG_MOVE_MAX - C.WM_STAGE_SIZE}")

# ===========================================================================
# 2. MIGRATION -- a project written before a Dropper could be given a path
# ===========================================================================
print("\n=== a project with no dropperProgram key ===")
legacy = Trigger.from_dict(
    {"worldProgress": 20, "waveDefinition": "sweep", "species": "DROPPER"},
    "legacy")
check("a trigger with no key reads as the legacy flight",
      legacy.dropper_program is None and legacy.dropper_is_legacy)
check("...and an explicit null means the same thing",
      Trigger.from_dict({"dropperProgram": None}, "x").dropper_program is None)
check("...and so does an empty string, which is what a cleared control leaves",
      Trigger.from_dict({"dropperProgram": ""}, "x").dropper_program is None)
# THE KEY IS OMITTED WHEN THERE IS NOTHING TO SAY, which is what keeps every
# project authored before this field a byte-for-byte fixed point. See the note in
# project_v6.Trigger.to_dict for why this differs from colour/speed.
check("saving a legacy trigger writes no key at all",
      "dropperProgram" not in legacy.to_dict(),
      ", ".join(sorted(legacy.to_dict())))
legacy.dropper_program = "loop"
check("...and an authored one writes the program id",
      legacy.to_dict()["dropperProgram"] == "loop")

text = CANON.read_text(encoding="utf-8")
check("the canonical Level 1 document is a JSON fixed point, unmigrated",
      ProjectV6.from_json(text).to_level_json() == text, f"{len(text)} bytes")
ctl = EditorController.load(CANON, library_path=LIB)
check("...and every committed trigger opens as the legacy flight",
      all(t.dropper_is_legacy for t in ctl.project.triggers),
      f"{len(ctl.project.triggers)} triggers")
check("both production levels still validate",
      all(validate(EditorController.load(
          HERE / "levels" / lv / "level.v6.json", library_path=LIB).project).ok
          for lv in ("level1", "level2")))

# ===========================================================================
# 3. THE CONTROLLER -- selecting, returning, and changing species
# ===========================================================================
print("\n=== the controller round-trips the selection ===")
ctl = EditorController(dropper_fixture())
di = dropper_index(ctl.project)
progs = [p.id for p in ctl.project.movement_programs]
check("the fixture has a Dropper trigger and more than one program",
      len(progs) >= 2, ", ".join(progs))
ctl.update_trigger(di, dropper_program=progs[1])
check("an authored program is stored", ctl.project.triggers[di].dropper_program
      == progs[1], progs[1])
check("...and the trigger no longer says legacy",
      not ctl.project.triggers[di].dropper_is_legacy)
ctl.update_trigger(di, dropper_program=None)
check("...and Legacy can be returned to, which None has to mean to be a choice",
      ctl.project.triggers[di].dropper_is_legacy)
ctl.update_trigger(di, dropper_program="")
check("...an empty selection is the legacy flight too, never a program named ''",
      ctl.project.triggers[di].dropper_program is None)

# THE ESCORTS ARE NOT REACHED. Selecting a Dropper path must not touch the wave
# definition, which is what paths members 1..N-1.
before = ctl.project.triggers[di].wave_definition
defs_before = json.dumps([w.to_dict() for w in ctl.project.wave_definitions],
                         sort_keys=True)
ctl.update_trigger(di, dropper_program=progs[0])
check("choosing a Dropper path leaves the trigger's wave definition alone",
      ctl.project.triggers[di].wave_definition == before, before)
check("...and changes no wave definition at all",
      json.dumps([w.to_dict() for w in ctl.project.wave_definitions],
                 sort_keys=True) == defs_before)

# A SPECIES CHANGE IS SAFE IN BOTH DIRECTIONS. Leaving a Dropper path on a Ring
# wave would fail the engine's build-time check for a field the author can no
# longer see, so the controller clears it with the side beside it.
plain = next(n for n in C.level_identities(ctl.project)
             if C.identity_behaviour(n) != C.BEHAVIOUR_DROPPER)
ctl.update_trigger(di, dropper_program=progs[1], dropper_side="RIGHT")
ctl.update_trigger(di, species=plain)
check("switching species away from Dropper clears the Dropper path",
      ctl.project.triggers[di].dropper_program is None)
check("...and the side, to the canonical neutral, as it always did",
      ctl.project.triggers[di].dropper_side == "LEFT")
ctl.update_trigger(di, species="DROPPER")
check("...and switching back gives a plain legacy Dropper, inventing nothing",
      ctl.project.triggers[di].dropper_is_legacy
      and ctl.project.triggers[di].dropper_side == "LEFT")
check("...with the project still valid throughout",
      validate(ctl.project).ok,
      "; ".join(str(i) for i in validate(ctl.project).errors))

# BY BEHAVIOUR, NOT BY NAME. An identity carrying BEHAVIOUR_DROPPER under some
# other name is a Dropper, and used to have its side reset on every edit because
# the controller compared against the literal "DROPPER".
named = next((n for n in C.ROSTER_BEHAVIOUR
              if C.ROSTER_BEHAVIOUR[n] == C.BEHAVIOUR_DROPPER and n != "DROPPER"),
             None)
if named is not None and named in C.level_identities(ctl.project):
    ctl.update_trigger(di, species=named, dropper_program=progs[0],
                       dropper_side="RIGHT")
    ctl.update_trigger(di, dropper_side="RIGHT")
    check(f"a Dropper-behaviour identity named {named!r} keeps its path and side",
          ctl.project.triggers[di].dropper_program == progs[0]
          and ctl.project.triggers[di].dropper_side == "RIGHT")
    ctl.update_trigger(di, species="DROPPER")
else:
    ok("no second Dropper-behaviour identity in this level's slots to test with",
       str(named))

# ===========================================================================
# 4. VALIDATION
# ===========================================================================
print("\n=== the validator checks the reference ===")
v = EditorController(dropper_fixture())
vi = dropper_index(v.project)
vprogs = [p.id for p in v.project.movement_programs]
v.project.triggers[vi].dropper_program = vprogs[0]
check("a Dropper naming a program that exists is accepted",
      validate(v.project).ok,
      "; ".join(str(i) for i in validate(v.project).errors))
v.project.triggers[vi].dropper_program = "no such program"
codes = {i.code for i in validate(v.project).errors}
check("a dangling reference is an ERROR, not a warning or a guess",
      "trigger.dropper_program_missing" in codes, ", ".join(sorted(codes)))
# A RENAME AND A DELETE ARE THE SAME FAULT, reached two ways.
v.project.triggers[vi].dropper_program = vprogs[0]
v.project.movement_programs = [p for p in v.project.movement_programs
                               if p.id != vprogs[0]]
check("deleting the referenced program is caught the same way",
      "trigger.dropper_program_missing"
      in {i.code for i in validate(v.project).errors})

v = EditorController(dropper_fixture())
vi, oi = dropper_index(v.project), other_index(v.project)
vprogs = [p.id for p in v.project.movement_programs]
v.project.triggers[oi].dropper_program = vprogs[0]
codes = {i.code for i in validate(v.project).errors}
check("a NON-Dropper naming a Dropper path is an error: the column is not read "
      "for it and the path would never be flown",
      "trigger.dropper_program_ignored" in codes, ", ".join(sorted(codes)))
v.project.triggers[oi].dropper_program = None
check("...and clearing it fixes it", validate(v.project).ok)

# ===========================================================================
# 5. EXPORT, IMPORT, AND THE BYTES
# ===========================================================================
print("\n=== the generated column, and the round trip ===")
tmp = Path(tempfile.mkdtemp(prefix="dropmove-"))
try:
    p = dropper_fixture()
    di = dropper_index(p)
    prog = p.movement_programs[1].id
    p.triggers[di].dropper_program = prog

    files = export_v6.render_all(p, "fixture")
    enc = files[export_v6.ENCOUNTERS_NAME]
    check("the generated encounter file declares the tenth column",
          ".var trigDropProg" in enc)
    check("...naming the program by its CONSTANT rather than an index literal",
          export_v6.prog_const(prog) in enc.split("trigDropProg")[1]
          .split("\n")[0], export_v6.prog_const(prog))
    check("...and TRIG_DROP_LEGACY for every other trigger",
          enc.split("trigDropProg")[1].split("\n")[0].count("TRIG_DROP_LEGACY")
          == len(p.triggers) - 1)

    out = tmp / "gen"
    out.mkdir()
    for name, text in files.items():
        (out / name).write_text(text, encoding="utf-8")
    src = asm_decl.parse_files(
        [REPO / "src" / n for n in ("movement_format.asm",
                                    "encounter_format.asm")]
        + [out / "wave_programs.asm", out / "wave_encounters.asm"])
    col = src.list_("trigDropProg")
    check("the column is one entry per trigger", len(col) == len(p.triggers))
    check("...the Dropper's entry is the program's INDEX", col[di] == 1)
    check("...and every other entry is the sentinel",
          all(col[i] == C.TRIG_DROP_LEGACY
              for i in range(len(col)) if i != di))

    # THE FIXED POINT. Import the generated source back and re-export it: the
    # selection has to survive being written as an index and read back as an id.
    back = I.read_encounters(REPO / "src", out)
    check("re-importing resolves the index back to the program's id",
          back.triggers[di].dropper_program == prog,
          str(back.triggers[di].dropper_program))
    check("...and every other trigger back to the legacy flight",
          all(t.dropper_is_legacy for i, t in enumerate(back.triggers)
              if i != di))
    check("...and every trigger's placement reference came back unchanged",
          [t.wave_definition for t in back.triggers]
          == [t.wave_definition for t in p.triggers])

    p2 = dropper_fixture()
    p2.movement_programs = back.movement_programs
    p2.wave_definitions = back.wave_definitions
    p2.triggers = back.triggers
    again = export_v6.render_all(p2, "fixture")
    check("exporting the re-imported project is byte-identical",
          again[export_v6.ENCOUNTERS_NAME] == enc)

    # THE PACKAGE BYTES, through the reference encoder, which is what a runtime
    # test compares against the real build.
    cols = I.reference_encode_trigger_columns(
        p.triggers, p.wave_definitions, slots=C.MAX_TRIGGERS,
        identities=C.level_identities(p), programs=p.movement_programs)
    check("the reference encoding is every column at the package's slot count",
          len(cols) == C.LEVELPKG_TRIG_COLS * C.MAX_TRIGGERS,
          f"{len(cols)} bytes = {C.LEVELPKG_TRIG_COLS} x {C.MAX_TRIGGERS}")
    tenth = cols[9 * C.MAX_TRIGGERS:10 * C.MAX_TRIGGERS]
    want = sum(len(q.stages) for q in p.movement_programs[:1]) * C.WM_STAGE_SIZE
    check("...and the tenth carries the program's BYTE OFFSET, not its index",
          tenth[di] == want, f"{tenth[di]} wanted {want}")
    check("...padding the unused tail with the sentinel, because zero is the "
          "FIRST program's offset",
          set(tenth[len(p.triggers):]) == {C.TRIG_DROP_LEGACY},
          str(sorted(set(tenth[len(p.triggers):]))))

    # SAVE AND RELOAD, DETERMINISTICALLY.
    doc = tmp / "level.v6.json"
    doc.write_text(p.to_level_json(), encoding="utf-8")
    reloaded = ProjectV6.load(doc)
    check("save -> load preserves the Dropper selection",
          reloaded.triggers[di].dropper_program == prog)
    check("...and every legacy trigger stays legacy",
          all(t.dropper_is_legacy for i, t in enumerate(reloaded.triggers)
              if i != di))
    check("...and saving again is byte-identical",
          reloaded.to_level_json() == p.to_level_json())
finally:
    shutil.rmtree(tmp, ignore_errors=True)

# ===========================================================================
# 6. CAPACITY -- derived from the record size, at both ends
# ===========================================================================
print("\n=== the tenth column's cost is computed, not restated ===")
check("the editor derives the reservation from its own parts",
      C.LEVELPKG_TRIG_RESERVATION
      == C.LEVELPKG_ENC_MAX - C.LEVELPKG_STAGE_MAX - C.LEVELPKG_MOVE_MAX
         - C.LEVELPKG_WAVEDEF_MAX,
      str(C.LEVELPKG_TRIG_RESERVATION))
check("...and the slot count from the column count",
      C.LEVELPKG_TRIG_SLOTS
      == C.LEVELPKG_TRIG_RESERVATION // C.LEVELPKG_TRIG_COLS
      and C.MAX_TRIGGERS == C.LEVELPKG_TRIG_SLOTS,
      f"{C.LEVELPKG_TRIG_COLS} columns -> {C.LEVELPKG_TRIG_SLOTS} slots")
pkg = (REPO / "src" / "levelpkg.asm").read_text()
check("the ENGINE derives it the same way, with no literal to go stale",
      ".const LEVELPKG_TRIG_SLOTS  = floor(LEVELPKG_TRIG_MAX / LEVELPKG_TRIG_COLS)"
      in pkg)
_cols = re.search(r"\.const LEVELPKG_TRIG_COLS\s*=\s*(\d+)", pkg)
check("...and both ends agree how many columns there are",
      _cols is not None and int(_cols.group(1)) == C.LEVELPKG_TRIG_COLS,
      f"engine {_cols and _cols.group(1)}, editor {C.LEVELPKG_TRIG_COLS}")
# THE BOUNDARY MOVES WITH THE RECORD SIZE, and that is the property worth
# asserting: what the number IS today is content, what it FOLLOWS FROM is not.
for cols in (C.LEVELPKG_TRIG_COLS - 1, C.LEVELPKG_TRIG_COLS,
             C.LEVELPKG_TRIG_COLS + 1):
    check(f"a {cols}-column record would derive "
          f"{C.LEVELPKG_TRIG_RESERVATION // cols} slots",
          C.LEVELPKG_TRIG_RESERVATION // cols > 0)
check("adding the tenth column cost capacity and the editor knows the new "
      "figure without being told it",
      C.MAX_TRIGGERS == C.LEVELPKG_TRIG_RESERVATION // C.LEVELPKG_TRIG_COLS
      < C.LEVELPKG_TRIG_RESERVATION // (C.LEVELPKG_TRIG_COLS - 1),
      f"{C.LEVELPKG_TRIG_RESERVATION // (C.LEVELPKG_TRIG_COLS - 1)} -> "
      f"{C.MAX_TRIGGERS}")
# AT THE BOUNDARY, AND ONE PAST IT.
at = fixtures_v6.at_capacity(C.MAX_TRIGGERS)
check(f"a project with exactly {C.MAX_TRIGGERS} triggers validates",
      validate(at).ok, f"{len(at.triggers)} triggers")
over = fixtures_v6.at_capacity(C.MAX_TRIGGERS + 1)
check("...and one more is refused",
      "triggers.capacity" in {i.code for i in validate(over).errors}
      or not validate(over).ok,
      ", ".join(sorted({i.code for i in validate(over).errors})))

# ===========================================================================
# 7. THE PREVIEW -- both modes, and the cache
# ===========================================================================
print("\n=== the preview draws both modes ===")
p = dropper_fixture()
di = dropper_index(p)
wave = next(w for w in p.wave_definitions
            if w.id == p.triggers[di].wave_definition)

sim = ms.simulate_trigger(p, di)
# ONE OBJECT, WHATEVER THE DEFINITION SAYS. This section used to assert the
# composite encounter -- member 0 the Dropper, members 1..N-1 escorts, the
# escorts' paths and spawn frames preserved around a member-0 hole. That
# encounter is gone: a Dropper Trigger describes one object's placement and
# movement, and company is a second ordinary trigger authored nearby.
check("a LEGACY Dropper trigger draws exactly one object",
      sim is not None and sim.count == 1 and len(sim.paths) == 1,
      f"{sim.count} object(s); its definition sends {wave.count}")
check("...from a definition that nominally sends more, proving the count is "
      "not read", wave.count > 1, f"definition sends {wave.count}")
check("...and that object is on the legacy trajectory",
      all(f.stage_kind == "DROPPER" for f in sim.paths[0]))
check("...with no phantom escort on any frame",
      all(len(fr) <= 1 for fr in sim.frames),
      f"max {max(len(fr) for fr in sim.frames)} object(s) on a frame")
p.triggers[di].speed = C.TRIG_SPEED_1X
slow = ms.simulate_trigger(p, di).paths[0]
p.triggers[di].speed = 8
fast = ms.simulate_trigger(p, di).paths[0]
check("a legacy Dropper's path is identical at 1.00x and 2.00x, as dropperFly "
      "ignores trigger speed",
      [(f.x, f.y) for f in slow] == [(f.x, f.y) for f in fast],
      f"{len(slow)} vs {len(fast)} frames")
p.triggers[di].speed = C.TRIG_SPEED_1X

# A PROGRAM THAT STARTS ON AN ARC ASKING TO CONTINUE, because that is what makes
# the launch heading observable: a STRAIGHT leg carries an authored velocity and
# correctly ignores wmPhase, so a heading check against one would prove nothing.
p.movement_programs.append(project_v6.MovementProgram("dive", [
    project_v6.MovementStage("ARC", steps=24, frames_per_step=3,
                             entry_heading="CONT"),
    project_v6.MovementStage("EXIT"),
]))
prog = "dive"
p.triggers[di].dropper_program = prog
asim = ms.simulate_trigger(p, di)
check("an AUTHORED Dropper trigger also draws exactly one object",
      asim is not None and asim.count == 1 and len(asim.paths) == 1,
      f"{asim.count} object(s)")
check("...NOT on the legacy trajectory",
      all(f.stage_kind != "DROPPER" for f in asim.paths[0]),
      f"kinds {sorted({f.stage_kind for f in asim.paths[0]})}")
# ITS OWN START POSITION, which is the definition's start position -- the
# placement, with no per-member step applied because there is no second member.
check("...starting at its own authored placement, not a screen edge",
      asim.paths[0][0].x == (wave.start_x & 0x1FF)
      and asim.paths[0][0].y == (wave.start_y & 0xFF),
      f"({asim.paths[0][0].x}, {asim.paths[0][0].y}) wanted "
      f"({wave.start_x}, {wave.start_y})")
check("...and with no phantom escort on any frame",
      all(len(fr) <= 1 for fr in asim.frames),
      f"max {max(len(fr) for fr in asim.frames)} object(s) on a frame")

# SPEED REACHES AN AUTHORED DROPPER, and a faster loop is a WIDER loop.
p.triggers[di].speed = 8
fsim = ms.simulate_trigger(p, di)


def span(path):
    return (max(f.x for f in path) - min(f.x for f in path),
            max(f.y for f in path) - min(f.y for f in path))


check("trigger speed changes an authored Dropper's path",
      [(f.x, f.y) for f in fsim.paths[0]] != [(f.x, f.y) for f in asim.paths[0]])
check("...and the faster one covers more ground per frame, which is what makes "
      "an authored loop widen rather than tighten",
      span(fsim.paths[0])[0] >= span(asim.paths[0])[0]
      or span(fsim.paths[0])[1] >= span(asim.paths[0])[1],
      f"1x {span(asim.paths[0])} -> 2x {span(fsim.paths[0])}")
p.triggers[di].speed = C.TRIG_SPEED_1X

# THE HEADING REACHES IT, through the definition the trigger already references.
h0 = wave.heading
wave.heading = (h0 + C.WM_HEAD_LEN // 4) % C.WM_HEAD_LEN
turned = ms.simulate_trigger(p, di)
check("the launch heading changes an authored Dropper's path",
      [(f.x, f.y) for f in turned.paths[0]]
      != [(f.x, f.y) for f in asim.paths[0]])
wave.heading = h0

# LEFT/RIGHT REACHES THE LEGACY FLIGHT AND NOTHING ELSE.
p.triggers[di].dropper_program = None
p.triggers[di].dropper_side = "LEFT"
left = ms.simulate_trigger(p, di).paths[0]
p.triggers[di].dropper_side = "RIGHT"
right = ms.simulate_trigger(p, di).paths[0]
check("LEFT and RIGHT are different LEGACY flights",
      left[0].x != right[0].x and left[0].vx == -right[0].vx,
      f"x {left[0].x}/{right[0].x}, vx {left[0].vx}/{right[0].vx}")
p.triggers[di].dropper_program = prog
p.triggers[di].dropper_side = "LEFT"
aleft = ms.simulate_trigger(p, di).paths[0]
p.triggers[di].dropper_side = "RIGHT"
aright = ms.simulate_trigger(p, di).paths[0]
check("...and identical AUTHORED ones: the side is not given a new meaning",
      [(f.x, f.y) for f in aleft] == [(f.x, f.y) for f in aright])

# ===========================================================================
# 8. THE PREVIEW CACHE -- every parameter that changes the geometry
# ===========================================================================
# WITHOUT THIS THE SCALING WORKS AND THE SCREEN DOES NOT. PreviewPanel._signature
# is compared to decide whether to re-fly; a trigger field the simulation reads
# and the signature omits leaves a correct simulation nobody ever asks for. The
# previous pass added resolved_speed for exactly this reason, and it must stay.
print("\n=== the preview cache notices every Dropper parameter ===")
try:
    import tkinter as tk
    import preview_ui
    from encounters_ui import EncounterWorkspace            # noqa: F401
    _tk = tk.Tk()
    _tk.withdraw()
except Exception as exc:                                    # noqa: BLE001
    check("a real Tk is available for the widget checks", False, str(exc))
else:
    ctl = EditorController(dropper_fixture())
    di = dropper_index(ctl.project)
    progs = [q.id for q in ctl.project.movement_programs]

    class _WS:
        def __init__(self, controller):
            self.controller = controller

    panel = preview_ui.PreviewPanel(_tk, _WS(ctl))
    panel.source = ("trigger", di)
    panel.preview_heading = 0

    def sig():
        return panel._signature()

    base = sig()
    check("a signature is produced for a Dropper trigger", base is not None)
    check("...and is stable when nothing changes", sig() == base)

    ctl.project.triggers[di].dropper_program = progs[0]
    on = sig()
    check("selecting an authored program changes the signature",
          on != base, "Legacy -> authored")
    ctl.project.triggers[di].dropper_program = progs[1]
    check("...and so does changing WHICH program", sig() != on)
    ctl.project.triggers[di].dropper_program = None
    check("...and returning to Legacy changes it back", sig() == base)

    ctl.project.triggers[di].dropper_side = "RIGHT"
    check("changing LEFT/RIGHT changes the signature: it moves the legacy path",
          sig() != base)
    ctl.project.triggers[di].dropper_side = "LEFT"

    # THE PREVIOUS PASS'S FIX, STILL IN PLACE.
    was = ctl.project.triggers[di].speed
    ctl.project.triggers[di].speed = 8
    check("changing the trigger's movement speed still changes the signature",
          sig() != base)
    ctl.project.triggers[di].speed = was

    # THE DROPPER'S PROGRAM STAGES ARE PART OF IT TOO: editing the path the
    # Dropper flies must invalidate the cache exactly as editing the
    # definition's own program does.
    ctl.project.triggers[di].dropper_program = progs[1]
    armed = sig()
    dprog = next(q for q in ctl.project.movement_programs if q.id == progs[1])
    first = dprog.stages[0]
    if hasattr(first, "frames"):
        first.frames = first.frames + 1
    else:
        first.steps = first.steps + 1
    check("editing a stage of the DROPPER'S program changes the signature",
          sig() != armed)

    # ---- the widgets ---------------------------------------------------
    print("\n=== the control, against real Tk ===")
    ctl2 = EditorController(dropper_fixture())
    di2 = dropper_index(ctl2.project)
    oi2 = other_index(ctl2.project)
    progs2 = [q.id for q in ctl2.project.movement_programs]
    # THE LITTLE OF THE MAIN WINDOW THE WORKSPACE ACTUALLY USES, exactly as
    # test_editor_workspace.py stubs it. Constructing the real workspace is the
    # point: a previous editor refactor produced a constructor/callback failure
    # that a model-only test could not have seen.
    class _Host(tk.Toplevel):
        def __init__(self, master, controller):
            super().__init__(master)
            self.withdraw()
            self.controller = controller
            self.project = controller.view
            self._encounters = None

        def _push_undo(self, before):
            pass

        def _update_document_ui(self):
            pass

        def _draw_level(self):
            pass

    host = _Host(_tk, ctl2)
    ws = EncounterWorkspace(host)
    ws.withdraw()
    ws.update_idletasks()

    def pick(i):
        ws.sel_trigger = i
        ws._refresh_trigger_detail()
        ws.update_idletasks()

    check("the workspace has a Dropper movement control",
          hasattr(ws, "t_dropmove"))
    check("...offering Legacy first, then this level's programs",
          list(ws.t_dropmove["values"])
          == [C.DROPPER_MOVEMENT_LEGACY] + progs2,
          ", ".join(ws.t_dropmove["values"]))
    pick(di2)
    check("a legacy Dropper shows Legacy selected",
          ws.t_dropmove.get() == C.DROPPER_MOVEMENT_LEGACY, ws.t_dropmove.get())
    check("...with the movement control enabled",
          str(ws.t_dropmove.cget("state")) == "readonly")
    check("...and LEFT/RIGHT enabled, because the legacy flight reads it",
          str(ws.t_side.cget("state")) == "readonly")

    ctl2.update_trigger(di2, dropper_program=progs2[0])
    pick(di2)
    check("an authored Dropper shows its program",
          ws.t_dropmove.get() == progs2[0], ws.t_dropmove.get())
    check("...and LEFT/RIGHT is DISABLED, because nothing reads it",
          str(ws.t_side.cget("state")) == "disabled")
    check("...and says so rather than leaving the author to infer it",
          "not used" in ws.t_side_note.cget("text").lower(),
          ws.t_side_note.cget("text"))
    check("...while the movement control explains what it does",
          "member 0" in ws.t_dropmove_note.cget("text"),
          ws.t_dropmove_note.cget("text")[:60])

    pick(oi2)
    check("a NON-Dropper trigger has the movement control disabled",
          str(ws.t_dropmove.cget("state")) == "disabled")
    check("...and is told why",
          "does not drop a token" in ws.t_dropmove_note.cget("text"),
          ws.t_dropmove_note.cget("text"))

    # SELECTING BACK AND FORTH, which is where a constructor/callback fault
    # would show as a stale control rather than as an exception.
    for _ in range(3):
        pick(di2)
        pick(oi2)
    pick(di2)
    check("repeated selection leaves the control showing the trigger's own "
          "answer",
          ws.t_dropmove.get() == progs2[0]
          and str(ws.t_dropmove.cget("state")) == "readonly")
    ws.destroy()
    host.destroy()
    _tk.destroy()

# ===========================================================================
# 9. NOTHING PRODUCTION WAS TOUCHED
# ===========================================================================
print("\n=== the committed sources are untouched ===")
check("the canonical level 1 document is byte-identical",
      CANON.read_bytes() == CANON_BYTES)
check("the shared encounter library is byte-identical",
      LIB.read_bytes() == LIB_BYTES)

print()
if FAIL:
    print(f"{len(FAIL)} FAILURE(S):")
    for m in FAIL:
        print(f"  - {m}")
    sys.exit(1)
print(f"All {len(PASS)} Dropper-movement checks passed.")
