#!/usr/bin/env python3
"""Trigger-owned movement speed: model, migration, export, preview, widgets.

The runtime half is proved on the emulator in tests/test_trigger_speed.py and
the build-time flight validator in test_trigger_speed_validator.py. This proves
everything between the author's fingers and the generated bytes, and above all:

    THE SAME WAVE DEFINITION, USED BY TWO TRIGGERS, TRAVELS AT TWO
    DIFFERENT SPEEDS -- and is still ONE definition.

NOTHING PRODUCTION IS WRITTEN. Every save and export goes to a temporary
directory; the committed level documents and library are byte-compared at the
end.

THE WIDGET SECTION NEEDS A WORKING TK, which not every interpreter on a Mac
has. Run it with one that does:

    /usr/local/bin/python3 tools/level_editor/test_trigger_speed.py
"""
import json
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import asm_decl                                                  # noqa: E402
import contract_v2 as C                                          # noqa: E402
import export_v6                                                 # noqa: E402
import movement_sim as ms                                        # noqa: E402
import project_v6                                                # noqa: E402
from controller_v6 import EditorController                        # noqa: E402
from project_v6 import Trigger                                    # noqa: E402
from validation_v6 import validate                                # noqa: E402

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
CANON = HERE / "levels" / "level1" / "level.v6.json"
LIB = HERE / "encounter_library.v6.json"
PROD = REPO / "src" / "level1"

CANON_BYTES = CANON.read_bytes()
LIB_BYTES = LIB.read_bytes()

PASS, FAIL = [], []


def ok(m, x=""):
    PASS.append(m)
    print(f"ok  - {m}" + (f"  [{x}]" if x else ""))


def check(m, c, x=""):
    if c:
        ok(m, x)
    else:
        FAIL.append(m)
        print(f"FAIL- {m}" + (f"  [{x}]" if x else ""))


def trig_speeds(path):
    """The trigSpeed column of a generated wave_encounters.asm."""
    src = asm_decl.parse_files(
        [REPO / "src" / n for n in ("movement_format.asm", "encounter_format.asm")]
        + [Path(path) / "wave_programs.asm", Path(path) / "wave_encounters.asm"])
    return src.list_("trigSpeed")


# ===========================================================================
# 1. THE FIELD, AND WHO OWNS IT
# ===========================================================================
print("\n=== speed is a trigger field ===")

t = Trigger(world_progress=10, wave_definition="w")
check("a Trigger owns a movement speed", hasattr(t, "speed"))
check("...and serialises it", "speed" in t.to_dict())
d = project_v6.WaveDefinition(id="w", count=3, movement_program="p")
check("a WaveDefinition does NOT own one", not hasattr(d, "speed"))
check("...and serialises none",
      "speed" not in d.to_dict(), ", ".join(sorted(d.to_dict())))

check("the five authored choices are 1.00x..2.00x in quarters",
      C.SPEED_CHOICES == (4, 5, 6, 7, 8)
      and [C.SPEED_LABELS[v] for v in C.SPEED_CHOICES]
      == ["1.00x", "1.25x", "1.50x", "1.75x", "2.00x"])
check("the default is 1.00x", C.TRIG_SPEED_1X == 4)

fmt = (REPO / "src" / "encounter_format.asm").read_text()
# READ THROUGH THE SAME PARSER THE EXPORTER USES, not by grepping: if the
# editor's asm_decl cannot read these declarations then the two halves have no
# shared definition of what a 6 means, whatever the file looks like.
_fmt_src = asm_decl.parse_files([REPO / "src" / "encounter_format.asm"])
check("the engine declares the same five values, readably",
      [_fmt_src.const(n) for n in ("TRIG_SPEED_1X", "TRIG_SPEED_125X",
                                   "TRIG_SPEED_150X", "TRIG_SPEED_175X",
                                   "TRIG_SPEED_2X")] == list(C.SPEED_CHOICES),
      str(list(C.SPEED_CHOICES)))
check("...and the same bounds",
      (_fmt_src.const("TRIG_SPEED_MIN"), _fmt_src.const("TRIG_SPEED_MAX"))
      == (C.TRIG_SPEED_MIN, C.TRIG_SPEED_MAX))

# ===========================================================================
# 2. MIGRATION -- a project with no speed field
# ===========================================================================
print("\n=== a project written before speed existed ===")

legacy = Trigger.from_dict(
    {"worldProgress": 20, "waveDefinition": "sweep", "species": "RING"},
    "legacy")
check("a trigger with no speed key reads as 'not authored'", legacy.speed is None)
check("...and resolves to 1.00x", legacy.resolved_speed == C.TRIG_SPEED_1X)
check("...and saves as 1.00x outright", legacy.to_dict()["speed"] == 4)


class _Doc:
    def __init__(self, defs, trigs):
        self.wave_definitions, self.triggers = defs, trigs


doc = _Doc([project_v6.WaveDefinition(id="sweep", movement_program="p")],
           [Trigger(world_progress=20, wave_definition="sweep"),
            Trigger(world_progress=40, wave_definition="nope")])
project_v6.resolve_trigger_encounter_fields(doc)
check("migration gives every trigger the default",
      [t.speed for t in doc.triggers] == [4, 4])
check("...including one whose definition does not exist -- speed never came "
      "from the definition, so a dangling reference cannot withhold it",
      doc.triggers[1].speed == 4)
doc.triggers[0].speed = 8
project_v6.resolve_trigger_encounter_fields(doc)
check("resolving again never overwrites a trigger that already decided",
      doc.triggers[0].speed == 8)

# THE PROPERTY, NOT THE SNAPSHOT. This used to assert that every committed
# trigger was 1.00x, which was true the day it was written and false the moment
# the author used the feature -- the third time in this repo that a test has
# frozen live authored content. What must hold for ever is that every trigger
# HAS a speed and it is one the editor and the engine both accept.
ctl = EditorController.load(CANON, library_path=LIB)
speeds = [t.resolved_speed for t in ctl.project.triggers]
check("every committed Level 1 trigger resolves to a legal speed",
      all(sp in C.SPEED_CHOICES for sp in speeds),
      "; ".join(f"row {t.world_progress}={C.SPEED_LABELS[t.resolved_speed]}"
                for t in ctl.project.triggers))
check("...and 1.00x, wherever it is used, is bit-exact", True,
      "(v*4)>>2 == v -- asserted exhaustively below")
check("both production levels still validate",
      all(validate(EditorController.load(
          HERE / "levels" / lv / "level.v6.json", library_path=LIB).project).ok
          for lv in ("level1", "level2")))

# ===========================================================================
# 3. VALIDATION
# ===========================================================================
print("\n=== the validator knows the range ===")
v = EditorController.load(CANON, library_path=None)
for bad in (0, 3, 9, 255):
    v.project.triggers[0].speed = bad
    check(f"speed {bad} is refused",
          "trigger.speed" in {i.code for i in validate(v.project).errors})
for good in C.SPEED_CHOICES:
    v.project.triggers[0].speed = good
    check(f"speed {good} ({C.SPEED_LABELS[good]}) is accepted",
          "trigger.speed" not in {i.code for i in validate(v.project).errors})

# ===========================================================================
# 4. THE SCALING ARITHMETIC
# ===========================================================================
print("\n=== the scaling matches the 6502 ===")
check("1.00x is a bit-exact no-op for every representable velocity",
      all(C.scale_velocity(v, 4) == v for v in range(-128, 128)))
check("2.00x doubles",
      all(C.scale_velocity(v, 8) == 2 * v for v in range(-64, 64)))
check("scaling is SIGN-SYMMETRIC -- an ARC and its ARC_MIRROR must agree",
      all(C.scale_velocity(-v, n) == -C.scale_velocity(v, n)
          for v in range(0, 33) for n in C.SPEED_CHOICES))
check("zero components stay zero",
      all(C.scale_velocity(0, n) == 0 for n in C.SPEED_CHOICES))
check("the arc magnitude scales 6 -> 6,7,9,10,12",
      [C.scale_velocity(6, n) for n in C.SPEED_CHOICES] == [6, 7, 9, 10, 12])
check("nothing can overflow the byte the engine accumulates in",
      all(abs(v) * n <= 255
          for v in range(-C.MAX_ABS_VX, C.MAX_ABS_VX + 1)
          for n in C.SPEED_CHOICES))

# ---- and the assembler's copy agrees ---------------------------------
waves = (REPO / "src" / "waves.asm").read_text()
check("the assembler's simulator uses the same sign-magnitude rule",
      "wmScaleSim" in waves and "v < 0 ? -mag : mag" in waves)
mv = (REPO / "src" / "movement.asm").read_text()
check("the runtime scales at the two cold write points only",
      mv.count("jmp wmApplySpeed") == 2
      and "wmApplyVelocity" in mv.split("wmApplySpeed")[0])
check("...and wmClearSlot clears the speed to 1x, not to zero",
      "lda #TRIG_SPEED_1X\n    sta wmSpeed,x" in mv)

# ===========================================================================
# 5. PREVIEW PARITY -- the editor simulator honours the same scaling
# ===========================================================================
print("\n=== preview parity, per speed ===")
proj = EditorController.load(CANON, library_path=LIB).project


def distance(wave_id, speed, frames=60):
    """How far member 0 travels in `frames` frames at `speed`."""
    wave = ms.wave_by_id(proj, wave_id)
    sim = ms.simulate_wave(proj, wave, max_frames=frames + 2, speed=speed)
    path = sim.paths[0]
    a, b = path[0], path[min(frames, len(path) - 1)]
    return (b.x - a.x, b.y - a.y)


# PREDICTED FROM THE SCALED VELOCITY, NOT FROM THE SCALED DISTANCE. 1.25x of 6
# quarter pixels is 7, not 7.5 -- the engine has no half quarter-pixel -- so
# "the distance is 1.25x the distance" is false by design, and a test that
# checked it would be measuring the wrong thing and wanting a fudge factor.
# What must hold EXACTLY is that the wave travels at the velocity the scaling
# produces.
#
# THIRTY FRAMES KEEPS IT INSIDE THE FIRST LEG. `sweep` opens with a STRAIGHT of
# (6,0) for 34 frames; sampling past that mixes in the arc and the prediction
# stops being one multiplication.
STRAIGHT_FRAMES = 30
SWEEP_VX = 6
for n in C.SPEED_CHOICES:
    got = distance("sweep", n, frames=STRAIGHT_FRAMES)
    want_x = STRAIGHT_FRAMES * C.scale_velocity(SWEEP_VX, n) // 4
    check(f"{C.SPEED_LABELS[n]}: travels exactly its scaled velocity",
          got == (want_x, 0),
          f"got {got}, expected ({want_x}, 0) from "
          f"v={C.scale_velocity(SWEEP_VX, n)}")
check("1.00x is bit-identical to the unscaled engine",
      distance("sweep", 4, frames=STRAIGHT_FRAMES)
      == (STRAIGHT_FRAMES * SWEEP_VX // 4, 0))
check("2.00x travels exactly twice as far as 1.00x",
      distance("sweep", 8, frames=STRAIGHT_FRAMES)[0]
      == 2 * distance("sweep", 4, frames=STRAIGHT_FRAMES)[0],
      f"{distance('sweep', 4, frames=STRAIGHT_FRAMES)[0]} -> "
      f"{distance('sweep', 8, frames=STRAIGHT_FRAMES)[0]}")
check("the five speeds strictly increase in distance covered",
      all(distance("sweep", a, frames=STRAIGHT_FRAMES)[0]
          < distance("sweep", b, frames=STRAIGHT_FRAMES)[0]
          for a, b in zip(C.SPEED_CHOICES, C.SPEED_CHOICES[1:])),
      "; ".join(f"{C.SPEED_LABELS[n]}="
                f"{distance('sweep', n, frames=STRAIGHT_FRAMES)[0]}"
                for n in C.SPEED_CHOICES))

# an ARC, which has no authored velocity at all
arc = {n: distance("s", n, frames=40) for n in C.SPEED_CHOICES}
check("an ARC scales too, though it has no authored velocity",
      abs(arc[8][0]) + abs(arc[8][1]) > abs(arc[4][0]) + abs(arc[4][1]),
      f"1.00x {arc[4]} -> 2.00x {arc[8]}")
check("...monotonically across all five speeds",
      all(abs(arc[a][0]) + abs(arc[a][1]) <= abs(arc[b][0]) + abs(arc[b][1])
          for a, b in zip(C.SPEED_CHOICES, C.SPEED_CHOICES[1:])),
      "; ".join(f"{C.SPEED_LABELS[n]}={arc[n]}" for n in C.SPEED_CHOICES))

# ===========================================================================
# 6. THE WIDGETS
# ===========================================================================
print("\n=== the trigger UI ===")
gui = True
try:
    import tkinter as tk
    _r = tk.Tk()
    _r.destroy()
except Exception as exc:                                        # noqa: BLE001
    print(f"SKIP- the widget section needs a working Tk ({exc})")
    gui = False

if gui:
    import editor as ed
    ed.messagebox.showerror = lambda *a, **k: None
    ed.messagebox.showinfo = lambda *a, **k: None
    ed.messagebox.askyesno = lambda *a, **k: True
    import encounters_ui
    encounters_ui.messagebox.showerror = lambda *a, **k: None

    app = ed.LevelEditor(ed.find_repo_root())
    app.withdraw()                      # NEVER STEAL FOCUS
    app._open_encounters()
    w = app._encounters
    w.withdraw()
    app.update()

    def select(t):
        """Select THROUGH THE TREE, as a user does.

        Assigning w.sel_trigger directly does not survive the next
        app.update(): a pending <<TreeviewSelect>> re-derives it and overwrites
        the assignment.
        """
        i = w.controller.trigger_index_of(t)
        w.trig_tree.selection_set(str(i))
        w._trigger_selected()
        app.update()

    try:
        check("the trigger pane offers a movement speed", hasattr(w, "t_speed"))
        check("...showing the five friendly labels",
              list(w.t_speed["values"])
              == [C.SPEED_LABELS[v] for v in C.SPEED_CHOICES],
              str(list(w.t_speed["values"])))
        check("...and NOT the encoded integers",
              not any(x.strip().isdigit() for x in w.t_speed["values"]))
        check("the wave-definition pane offers no speed",
              "speed" not in w.w_fields and not hasattr(w, "w_speed"))

        # ---- TWO TRIGGERS, ONE DEFINITION, TWO SPEEDS ----------------
        trigs = w.controller.project.triggers
        groups = {}
        for i, t in enumerate(trigs):
            groups.setdefault(t.wave_definition, []).append(i)
        defn, group = next((k, v) for k, v in groups.items() if len(v) > 1)
        ta, tb = trigs[group[0]], trigs[group[1]]
        check(f"two triggers share the definition {defn!r}", True,
              f"rows {ta.world_progress} and {tb.world_progress}")

        select(ta)
        # ITS OWN SPEED, whatever the author has set it to -- not a literal.
        check("a trigger shows its own speed",
              w.t_speed.get() == C.SPEED_LABELS[ta.resolved_speed],
              f"shows {w.t_speed.get()!r}, is "
              f"{C.SPEED_LABELS[ta.resolved_speed]!r}")
        before_b = tb.resolved_speed
        w.t_speed.set("2.00x")
        w._trigger_apply()
        app.update()
        check("choosing 2.00x sets THIS trigger", ta.speed == 8, str(ta.speed))
        check("...AND LEAVES THE OTHER ON THE SAME DEFINITION ALONE",
              tb.resolved_speed == before_b,
              f"{before_b} -> {tb.resolved_speed}")
        check("...and the shared definition has no speed to change",
              not hasattr(next(x for x in w.controller.project.wave_definitions
                               if x.id == defn), "speed"))
        check("the edit marked the document dirty", app._is_dirty())

        select(tb)
        check("switching trigger shows the OTHER one's speed",
              w.t_speed.get() == C.SPEED_LABELS[before_b], w.t_speed.get())
        select(ta)
        check("...and switching back shows 2.00x again",
              w.t_speed.get() == "2.00x", w.t_speed.get())

        # ---- the workspace still works everywhere else ---------------
        for tab in range(3):
            w.tabs.select(tab)
            app.update()
        check("all three workspace tabs still select cleanly", True,
              "triggers / wave definitions / moves")
        check("the wave-definition pane still populates",
              bool(w.wave_list.size()))
        check("the movement-program pane still populates",
              bool(w.prog_list.size()))

        # ---- close and reopen, which is where the last regression hid
        w.destroy()
        app.update()
        app._open_encounters()
        w2 = app._encounters
        w2.withdraw()
        app.update()
        check("the Encounter window closes and reopens without a traceback",
              w2.winfo_exists() and hasattr(w2, "t_speed"))
        w2.destroy()
        app.update()
    finally:
        try:
            app.destroy()
        except Exception:                                       # noqa: BLE001
            pass

# ===========================================================================
# 7. SAVE / RELOAD / EXPORT
# ===========================================================================
print("\n=== the authoring round trip ===")
with tempfile.TemporaryDirectory() as tmp:
    tmp = Path(tmp)
    lvl_dir = tmp / "levels" / "level1"
    lvl_dir.mkdir(parents=True)
    shutil.copy2(CANON, lvl_dir / "level.v6.json")
    lib_path = tmp / "encounter_library.v6.json"
    shutil.copy2(LIB, lib_path)
    doc_path = lvl_dir / "level.v6.json"
    base_out, fast_out, back_out = tmp / "a", tmp / "b", tmp / "c"

    ctl = EditorController.load(doc_path, library_path=lib_path)
    ctl.export(base_out, carry_enemies_from=PROD)
    # WHATEVER IS AUTHORED, EXPORTED FAITHFULLY -- not a frozen expectation of
    # what the author happens to have chosen.
    original_speeds = [t.resolved_speed for t in ctl.project.triggers]
    check("the exported column is exactly what the project holds",
          list(trig_speeds(base_out)) == original_speeds,
          str(original_speeds))
    check("...and every value is a legal choice",
          all(sp in C.SPEED_CHOICES for sp in trig_speeds(base_out)))

    ids = [t.wave_definition for t in ctl.project.triggers]
    shared = next(i for i in ids if ids.count(i) > 1)
    idx = [i for i, t in enumerate(ctl.project.triggers)
           if t.wave_definition == shared]
    # ALL FIVE, so the round trip covers the whole range and not just the ends.
    for i, sp in zip(idx, C.SPEED_CHOICES):
        ctl.update_trigger(i, speed=sp)
    ctl.save()

    ctl2 = EditorController.load(doc_path, library_path=lib_path)
    got = [t.resolved_speed for t in ctl2.project.triggers
           if t.wave_definition == shared]
    check("save + reload preserves every value that was set",
          got == list(C.SPEED_CHOICES[:len(got)]), str(got))
    check("...and the definition they share is still ONE definition",
          len([d for d in ctl2.project.wave_definitions if d.id == shared]) == 1)
    saved = json.loads(doc_path.read_text())
    check("the saved document states each trigger's speed outright",
          all("speed" in t for t in saved["triggers"]))
    lib_saved = json.loads(lib_path.read_text())
    check("...and the saved library states none",
          not any("speed" in x for x in lib_saved["waveDefinitions"]))

    ctl2.export(fast_out, carry_enemies_from=PROD)
    exported = trig_speeds(fast_out)
    check("the generated column carries the different speeds",
          [exported[i] for i in idx] == list(C.SPEED_CHOICES[:len(idx)]),
          str([exported[i] for i in idx]))
    check("...and untouched triggers kept whatever they had",
          all(exported[i] == original_speeds[i]
              for i in range(len(exported)) if i not in idx))

    # RESTORED TO WHAT THEY WERE, not to the default: the author may well have
    # authored a speed, and "put it back" has to mean put it back.
    for i in idx:
        ctl2.update_trigger(i, speed=original_speeds[i])
    ctl2.save()
    ctl3 = EditorController.load(doc_path, library_path=lib_path)
    ctl3.export(back_out, carry_enemies_from=PROD)
    names = [n for n in export_v6.GENERATED_NAMES if (base_out / n).exists()]
    differing = [n for n in names
                 if (base_out / n).read_bytes() != (back_out / n).read_bytes()]
    check("EVERY generated file is byte-identical after the round trip",
          not differing, ", ".join(differing) or f"{len(names)} files compared")
    again = tmp / "d"
    ctl3.export(again, carry_enemies_from=PROD)
    check("exporting twice is byte-identical",
          all((again / n).read_bytes() == (back_out / n).read_bytes()
              for n in names))

# ===========================================================================
# 8. CAPACITY -- derived, never restated
# ===========================================================================
print("\n=== trigger capacity ===")
check("the editor derives the reservation from its own parts",
      C.LEVELPKG_TRIG_RESERVATION
      == C.LEVELPKG_ENC_MAX - C.LEVELPKG_STAGE_MAX - C.LEVELPKG_MOVE_MAX
         - C.LEVELPKG_WAVEDEF_MAX,
      str(C.LEVELPKG_TRIG_RESERVATION))
check("...and the slot count from the column count",
      C.LEVELPKG_TRIG_SLOTS
      == C.LEVELPKG_TRIG_RESERVATION // C.LEVELPKG_TRIG_COLS,
      f"{C.LEVELPKG_TRIG_COLS} columns -> {C.LEVELPKG_TRIG_SLOTS} slots")
pkg = (REPO / "src" / "levelpkg.asm").read_text()
check("the ENGINE derives it the same way, with no literal to go stale",
      ".const LEVELPKG_TRIG_SLOTS  = floor(LEVELPKG_TRIG_MAX / LEVELPKG_TRIG_COLS)"
      in pkg and "LEVELPKG_TRIG_COLS   = 9" in pkg)
for lv in ("level1", "level2"):
    p = EditorController.load(HERE / "levels" / lv / "level.v6.json",
                              library_path=LIB).project
    check(f"{lv} uses {len(p.triggers)} of {C.MAX_TRIGGERS} trigger slots",
          len(p.triggers) <= C.MAX_TRIGGERS)

# ===========================================================================
# 9. NOTHING PRODUCTION WAS TOUCHED
# ===========================================================================
print("\n=== the committed sources are untouched ===")
check("the canonical level 1 document is byte-identical",
      CANON.read_bytes() == CANON_BYTES)
check("the shared encounter library is byte-identical",
      LIB.read_bytes() == LIB_BYTES)

print(f"\n{len(PASS)} passed, {len(FAIL)} failed")
for m in FAIL:
    print(f"  FAILED: {m}")
sys.exit(1 if FAIL else 0)
