// ==========================================================================
// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.
// Level: level3
//
// Authored turret PLACEMENT layer. Constants + assembler lists only.
// PLACEMENT is editor-owned; BEHAVIOUR stays engine-owned (src/turrets.asm).
//
//   world row = metatileRow * 4 + 1
//   world col = metatileCol * 4 + 1
//
// Rows are 16-bit and sorted DESCENDING -- the order the downward-scrolling
// stage crosses them.
//
// CONTRACT v2 TEMPORARY LIMITS: at most 8 turrets (trtDeadPending is one
// byte, one bit per turret) and at most one per metatile row (turretAtMetaRow
// holds a single index). Both are scheduled to be lifted.
// ==========================================================================
.const TURRET_TOTAL = 2
.var turretCols = List().add(21, 9)
.var turretRows = List().add(129, 65)
