// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// this level's claim on the SPRITE artwork -- level3
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// The enemy sprite window is level-owned artwork: the package carries
// the bytes and levelApplySprites copies them into LEVEL_SPRITES at
// level init. This names which generated blocks fill the window, in
// WINDOW ORDER -- slot 0 first, contiguously.
//
// IT IS A MANIFEST, NOT ARTWORK. Every block comes from
// src/generated_sprites/, produced by tools/sprite_export/import_spd.py
// from assets/sprites/19656-sprites.spd.
//
// ONLY THE CHOSEN IDENTITIES ARE SHIPPED, which is what keeps a level
// inside the engine's twenty-block window.
// ==========================================================================

#importonce

#import "generated_sprites/enemy_ring_3_art.asm"                          // slots 0-7  Ring 3
#import "generated_sprites/enemy_dropper_art.asm"                         // slots 8-11  Dropper
#import "generated_sprites/enemy_square_art.asm"                          // slots 12-15  Square
