// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the boss, four cells of one machine
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// The caller owns nothing: this file pins itself at BOSS_SPRITES, as
// the hand-authored one did.
// ==========================================================================

* = BOSS_SPRITES "boss cells"
bossArt:
bossCell0:
    .byte $00, $55, $00
    .byte $01, $55, $40
    .byte $05, $7d, $50
    .byte $05, $7d, $54
    .byte $05, $55, $55
    .byte $15, $55, $55
    .byte $15, $55, $55
    .byte $55, $55, $55
    .byte $57, $d5, $55
    .byte $57, $d5, $55
    .byte $55, $55, $55
    .byte $55, $55, $aa
    .byte $55, $56, $aa
    .byte $55, $5a, $aa
    .byte $55, $6a, $af
    .byte $55, $aa, $bf
    .byte $55, $aa, $ff
    .byte $56, $aa, $ff
    .byte $56, $ab, $ff
    .byte $56, $ab, $ff
    .byte $56, $ab, $ff
    .byte $00          // the 64th byte: alignment, never fetched
bossCell1:
    .byte $00, $55, $00
    .byte $01, $55, $40
    .byte $05, $7d, $50
    .byte $15, $7d, $50
    .byte $55, $55, $50
    .byte $55, $55, $54
    .byte $55, $55, $54
    .byte $55, $55, $55
    .byte $55, $57, $d5
    .byte $55, $57, $d5
    .byte $55, $55, $55
    .byte $aa, $55, $55
    .byte $aa, $95, $55
    .byte $aa, $a5, $55
    .byte $fa, $a9, $55
    .byte $fe, $aa, $55
    .byte $ff, $aa, $55
    .byte $ff, $aa, $95
    .byte $ff, $ea, $95
    .byte $ff, $ea, $95
    .byte $ff, $ea, $95
    .byte $00          // the 64th byte: alignment, never fetched
bossCell2:
    .byte $56, $ab, $ff
    .byte $56, $ab, $ff
    .byte $56, $aa, $ff
    .byte $55, $aa, $ff
    .byte $55, $aa, $bf
    .byte $55, $6a, $af
    .byte $55, $5a, $aa
    .byte $55, $56, $aa
    .byte $55, $55, $aa
    .byte $55, $55, $55
    .byte $57, $d5, $55
    .byte $57, $d5, $55
    .byte $55, $55, $55
    .byte $15, $55, $55
    .byte $15, $55, $55
    .byte $05, $55, $50
    .byte $05, $55, $40
    .byte $05, $f5, $40
    .byte $05, $f5, $00
    .byte $01, $54, $00
    .byte $01, $50, $00
    .byte $00          // the 64th byte: alignment, never fetched
bossCell3:
    .byte $ff, $ea, $95
    .byte $ff, $ea, $95
    .byte $ff, $aa, $95
    .byte $ff, $aa, $55
    .byte $fe, $aa, $55
    .byte $fa, $a9, $55
    .byte $aa, $a5, $55
    .byte $aa, $95, $55
    .byte $aa, $55, $55
    .byte $55, $55, $55
    .byte $55, $57, $d5
    .byte $55, $57, $d5
    .byte $55, $55, $55
    .byte $55, $55, $54
    .byte $55, $55, $54
    .byte $05, $55, $50
    .byte $01, $55, $50
    .byte $01, $5f, $50
    .byte $00, $5f, $50
    .byte $00, $15, $40
    .byte $00, $05, $40
    .byte $00          // the 64th byte: alignment, never fetched
bossArtEnd:
