// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the hostile projectile
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// The caller owns the address and the labels: src/ebullet.asm sets
// * = EBULLET_SPRITE.
// ==========================================================================

    .byte $14, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $14, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
