// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the hostile projectile
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $26.
//
// The caller owns the address and the labels: src/ebullet.asm sets
// * = EBULLET_SPRITE.
// ==========================================================================

    .byte $14, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $69, $00, $00
    .byte $14, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
