// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Spinny Thing: 6 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $54 $55 $56 $57 $58 $59 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 3, 4, 5, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

spinnyFrames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $3c, $00
    .byte $00, $28, $00
    .byte $00, $28, $00
    .byte $00, $14, $00
    .byte $00, $00, $0f
    .byte $f0, $00, $0a
    .byte $a0, $00, $0a
    .byte $a0, $00, $05
    .byte $50, $00, $00
    .byte $00, $0f, $00
    .byte $00, $0a, $00
    .byte $00, $0a, $00
    .byte $00, $05, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $f0, $00
    .byte $00, $a0, $00
    .byte $00, $a0, $3c
    .byte $00, $50, $28
    .byte $00, $00, $28
    .byte $3c, $00, $14
    .byte $28, $00, $00
    .byte $28, $03, $c0
    .byte $14, $02, $80
    .byte $00, $02, $80
    .byte $00, $01, $40
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $03, $c0, $00
    .byte $02, $80, $3c
    .byte $02, $80, $28
    .byte $01, $40, $28
    .byte $00, $00, $14
    .byte $00, $00, $00
    .byte $0f, $00, $00
    .byte $0a, $00, $f0
    .byte $0a, $00, $a0
    .byte $05, $00, $a0
    .byte $00, $00, $50
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $f0
    .byte $0f, $00, $a0
    .byte $0a, $00, $a0
    .byte $0a, $00, $50
    .byte $05, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $3c
    .byte $03, $c0, $28
    .byte $02, $80, $28
    .byte $02, $80, $14
    .byte $01, $40, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $03, $c0
    .byte $00, $02, $80
    .byte $3c, $02, $80
    .byte $28, $01, $40
    .byte $28, $00, $00
    .byte $14, $00, $0f
    .byte $00, $00, $0a
    .byte $00, $f0, $0a
    .byte $00, $a0, $05
    .byte $00, $a0, $00
    .byte $00, $50, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $0f, $00
    .byte $00, $0a, $00
    .byte $00, $0a, $00
    .byte $00, $05, $00
    .byte $f0, $00, $00
    .byte $a0, $00, $0f
    .byte $a0, $00, $0a
    .byte $50, $00, $0a
    .byte $00, $00, $05
    .byte $00, $3c, $00
    .byte $00, $28, $00
    .byte $00, $28, $00
    .byte $00, $14, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
spinnyFramesEnd:
