// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the Sonic Ring: four multicolour frames
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// Rotation order: north -> east -> south -> west. src/enemy.asm asserts
// each frame label lands on its own block, so the labels are part of the
// contract and not decoration.
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- THIS enemy's own colour, which is
//                                  the wave's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: src/enemy.asm sets * = ENEMY_SPRITES.
// ==========================================================================

sonicRingFrames:
sonicRing_north:
    .byte $01, $7d, $40
    .byte $05, $df, $50
    .byte $16, $ff, $94
    .byte $1a, $be, $a4
    .byte $5a, $aa, $a5
    .byte $6a, $aa, $a9
    .byte $6a, $96, $a9
    .byte $6a, $41, $a9
    .byte $6a, $28, $a9
    .byte $6a, $28, $a9
    .byte $6a, $28, $a9
    .byte $6a, $28, $a9
    .byte $6a, $41, $a9
    .byte $6a, $96, $a9
    .byte $6a, $aa, $a9
    .byte $5a, $aa, $a5
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched
sonicRing_east:
    .byte $01, $55, $40
    .byte $05, $aa, $50
    .byte $16, $aa, $94
    .byte $1a, $aa, $a4
    .byte $5a, $aa, $a5
    .byte $6a, $aa, $a9
    .byte $6a, $96, $a9
    .byte $6a, $41, $bd
    .byte $6a, $28, $df
    .byte $6a, $28, $ff
    .byte $6a, $28, $bd
    .byte $6a, $28, $a9
    .byte $6a, $41, $a9
    .byte $6a, $96, $a9
    .byte $6a, $aa, $a9
    .byte $5a, $aa, $a5
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched
sonicRing_south:
    .byte $01, $55, $40
    .byte $05, $aa, $50
    .byte $16, $aa, $94
    .byte $1a, $aa, $a4
    .byte $5a, $aa, $a5
    .byte $6a, $aa, $a9
    .byte $6a, $96, $a9
    .byte $6a, $41, $a9
    .byte $6a, $28, $a9
    .byte $6a, $28, $a9
    .byte $6a, $28, $a9
    .byte $6a, $28, $a9
    .byte $6a, $41, $a9
    .byte $6a, $96, $a9
    .byte $6a, $aa, $a9
    .byte $5a, $aa, $a5
    .byte $1a, $be, $a4
    .byte $16, $df, $94
    .byte $05, $ff, $50
    .byte $01, $7d, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched
sonicRing_west:
    .byte $01, $55, $40
    .byte $05, $aa, $50
    .byte $16, $aa, $94
    .byte $1a, $aa, $a4
    .byte $5a, $aa, $a5
    .byte $6a, $aa, $a9
    .byte $6a, $96, $a9
    .byte $7e, $41, $a9
    .byte $df, $28, $a9
    .byte $ff, $28, $a9
    .byte $7e, $28, $a9
    .byte $6a, $28, $a9
    .byte $6a, $41, $a9
    .byte $6a, $96, $a9
    .byte $6a, $aa, $a9
    .byte $5a, $aa, $a5
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched
sonicRingFramesEnd:
