// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Spinner: 6 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $44 $45 $46 $47 $48 $49 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 3, 4, 5, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

spinnerFrames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $08, $00
    .byte $00, $19, $00
    .byte $00, $19, $00
    .byte $00, $59, $40
    .byte $00, $59, $40
    .byte $01, $59, $50
    .byte $01, $59, $50
    .byte $05, $7b, $54
    .byte $2a, $ae, $aa
    .byte $05, $7b, $54
    .byte $01, $59, $50
    .byte $01, $59, $50
    .byte $00, $59, $40
    .byte $00, $59, $40
    .byte $00, $19, $00
    .byte $00, $19, $00
    .byte $00, $08, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $a8, $00
    .byte $00, $20, $00
    .byte $00, $24, $00
    .byte $00, $65, $00
    .byte $00, $65, $00
    .byte $00, $59, $40
    .byte $01, $59, $50
    .byte $01, $59, $56
    .byte $01, $59, $6a
    .byte $05, $aa, $96
    .byte $8a, $59, $50
    .byte $a5, $59, $50
    .byte $81, $59, $50
    .byte $00, $59, $40
    .byte $00, $16, $40
    .byte $00, $16, $40
    .byte $00, $06, $00
    .byte $00, $02, $00
    .byte $00, $0a, $80
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $02, $00, $00
    .byte $01, $94, $00
    .byte $01, $95, $40
    .byte $01, $95, $56
    .byte $01, $65, $58
    .byte $05, $65, $a4
    .byte $05, $5a, $54
    .byte $05, $59, $54
    .byte $05, $69, $54
    .byte $06, $96, $54
    .byte $09, $56, $50
    .byte $25, $55, $90
    .byte $00, $55, $90
    .byte $00, $05, $90
    .byte $00, $00, $20
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $08, $00, $08
    .byte $02, $55, $60
    .byte $02, $55, $60
    .byte $01, $95, $90
    .byte $01, $95, $90
    .byte $01, $66, $50
    .byte $01, $66, $50
    .byte $01, $51, $50
    .byte $01, $66, $50
    .byte $01, $66, $50
    .byte $01, $95, $90
    .byte $01, $95, $90
    .byte $02, $55, $60
    .byte $02, $55, $60
    .byte $08, $00, $08
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $20
    .byte $00, $05, $90
    .byte $00, $55, $90
    .byte $25, $55, $90
    .byte $09, $56, $50
    .byte $06, $96, $54
    .byte $05, $69, $54
    .byte $05, $59, $54
    .byte $05, $5a, $54
    .byte $05, $65, $a4
    .byte $01, $65, $58
    .byte $01, $95, $56
    .byte $01, $95, $40
    .byte $01, $94, $00
    .byte $02, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $0a, $80
    .byte $00, $02, $00
    .byte $00, $06, $00
    .byte $00, $16, $40
    .byte $00, $16, $40
    .byte $00, $59, $40
    .byte $81, $59, $50
    .byte $a9, $59, $50
    .byte $86, $99, $50
    .byte $05, $6a, $56
    .byte $01, $59, $aa
    .byte $01, $59, $56
    .byte $01, $59, $52
    .byte $00, $59, $40
    .byte $00, $65, $00
    .byte $00, $65, $00
    .byte $00, $24, $00
    .byte $00, $20, $00
    .byte $00, $a8, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
spinnerFramesEnd:
