// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Space Mine: 3 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $50 $51 $52 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 0, 1, 2, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

spaceMineFrames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $c0, $fc, $0c
    .byte $73, $ff, $34
    .byte $1f, $ff, $d0
    .byte $07, $ef, $40
    .byte $3f, $fe, $50
    .byte $3f, $ea, $50
    .byte $fe, $ea, $54
    .byte $ff, $99, $54
    .byte $ff, $a9, $54
    .byte $fe, $a9, $54
    .byte $fe, $99, $54
    .byte $fe, $a6, $54
    .byte $fe, $a5, $54
    .byte $3e, $99, $50
    .byte $35, $55, $50
    .byte $0d, $95, $40
    .byte $35, $55, $70
    .byte $d1, $55, $1c
    .byte $40, $54, $04
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $fc, $00
    .byte $33, $ff, $30
    .byte $1f, $ff, $d0
    .byte $07, $ef, $40
    .byte $3f, $fe, $50
    .byte $3f, $ea, $50
    .byte $fe, $ea, $54
    .byte $ff, $99, $54
    .byte $ff, $a9, $54
    .byte $fe, $a9, $54
    .byte $fe, $99, $54
    .byte $fe, $a6, $54
    .byte $fe, $a5, $54
    .byte $3e, $99, $50
    .byte $35, $55, $50
    .byte $0d, $95, $40
    .byte $35, $55, $70
    .byte $11, $55, $10
    .byte $00, $54, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $fc, $00
    .byte $03, $ff, $00
    .byte $03, $ff, $00
    .byte $0f, $ef, $c0
    .byte $3f, $fe, $50
    .byte $3f, $ea, $50
    .byte $fe, $ea, $54
    .byte $ff, $99, $54
    .byte $ff, $a9, $54
    .byte $fe, $a9, $54
    .byte $fe, $99, $54
    .byte $fe, $a6, $54
    .byte $fe, $a5, $54
    .byte $3e, $99, $50
    .byte $35, $55, $50
    .byte $05, $95, $40
    .byte $01, $55, $00
    .byte $01, $55, $00
    .byte $00, $54, $00
    .byte $00          // the 64th byte: alignment, never fetched
spaceMineFramesEnd:
