// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the Orbital Dropper: four frames
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// Same four-pair palette as the Ring; pair 10 is the wave's authored
// colour and carries the orb itself.
//
// The caller owns the address: src/enemy.asm sets * = DROPPER_SPRITES.
// ==========================================================================

orbitalDropperFrames:
orbitalDropper_0_wide:
    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $ea, $aa, $6f
    .byte $ea, $aa, $6f
    .byte $2a, $aa, $68
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
orbitalDropper_1_front_right:
    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $2a, $aa, $f8
    .byte $2a, $aa, $f8
    .byte $2a, $aa, $68
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
orbitalDropper_2_front:
    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $2a, $be, $68
    .byte $2a, $be, $68
    .byte $2a, $aa, $68
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
orbitalDropper_3_front_left:
    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $2f, $aa, $68
    .byte $2f, $aa, $68
    .byte $2a, $aa, $68
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
orbitalDropperFramesEnd:
