// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Ring 1: 3 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $3E $3F $40 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 0, 1, 2, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

ring1Frames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $55, $00
    .byte $01, $aa, $40
    .byte $06, $ff, $90
    .byte $1b, $aa, $e4
    .byte $1b, $96, $e4
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $1b, $96, $e4
    .byte $1b, $aa, $e4
    .byte $06, $ff, $90
    .byte $01, $aa, $40
    .byte $00, $55, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $14, $00
    .byte $01, $69, $40
    .byte $06, $be, $90
    .byte $06, $eb, $90
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $6e, $41, $b9
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $06, $eb, $90
    .byte $06, $eb, $90
    .byte $01, $be, $40
    .byte $00, $69, $00
    .byte $00, $14, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $14, $00
    .byte $00, $69, $00
    .byte $01, $be, $40
    .byte $06, $eb, $90
    .byte $06, $eb, $90
    .byte $06, $eb, $90
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $1b, $96, $e4
    .byte $06, $eb, $90
    .byte $06, $eb, $90
    .byte $06, $eb, $90
    .byte $01, $be, $40
    .byte $00, $69, $00
    .byte $00, $14, $00
    .byte $00          // the 64th byte: alignment, never fetched
ring1FramesEnd:
