// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Modded Alleykat A: 3 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $34 $35 $36 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 0, 1, 2, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

alleykatAFrames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $0c, $ff, $30
    .byte $0f, $aa, $f0
    .byte $3e, $aa, $bc
    .byte $3c, $ff, $3c
    .byte $fc, $aa, $3f
    .byte $fc, $aa, $3f
    .byte $fc, $ff, $3f
    .byte $fc, $aa, $3f
    .byte $fc, $aa, $3f
    .byte $fc, $ff, $3f
    .byte $7c, $aa, $3d
    .byte $3c, $aa, $3c
    .byte $3f, $ff, $fc
    .byte $1e, $55, $b4
    .byte $0d, $55, $70
    .byte $0c, $55, $30
    .byte $04, $ff, $10
    .byte $04, $55, $10
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $0c, $aa, $30
    .byte $0f, $aa, $f0
    .byte $3e, $ff, $bc
    .byte $3c, $aa, $3c
    .byte $3c, $aa, $3c
    .byte $3c, $ff, $3c
    .byte $3c, $aa, $3c
    .byte $3c, $aa, $3c
    .byte $3c, $ff, $3c
    .byte $3c, $aa, $3c
    .byte $3c, $aa, $3c
    .byte $3c, $ff, $3c
    .byte $3f, $55, $fc
    .byte $1e, $55, $b4
    .byte $0d, $55, $70
    .byte $0c, $ff, $30
    .byte $04, $55, $10
    .byte $04, $ff, $10
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $0c, $aa, $30
    .byte $0f, $ff, $f0
    .byte $0e, $aa, $b0
    .byte $0c, $aa, $30
    .byte $0c, $ff, $30
    .byte $0c, $aa, $30
    .byte $0c, $aa, $30
    .byte $0c, $ff, $30
    .byte $0c, $aa, $30
    .byte $0c, $aa, $30
    .byte $0c, $ff, $30
    .byte $0c, $aa, $30
    .byte $0f, $55, $f0
    .byte $0e, $ff, $b0
    .byte $0d, $55, $70
    .byte $0c, $55, $30
    .byte $04, $ff, $10
    .byte $04, $55, $10
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
alleykatAFramesEnd:
