// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the Square: four multicolour frames
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// THE THIRD ORDINARY SPECIES. Appended to the .spd in Spritemate and
// imported here like any other artwork -- there is nothing special
// about it beyond being newer.
//
// The four frames are a spin: the silhouette narrows from a full
// square to an edge-on bar and the shading follows it round.
//
// Same four-pair palette as the Ring and the Dropper, so a wave's
// authored colour reaches pair 10 exactly as it does for them.
//
// The caller owns the address: src/enemy.asm sets * = SQUARE_SPRITES.
// ==========================================================================

squareFrames:
square_0_full:
    .byte $55, $55, $55
    .byte $6a, $aa, $a9
    .byte $6a, $aa, $a9
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $00, $29
    .byte $69, $55, $69
    .byte $6a, $aa, $a9
    .byte $6a, $aa, $a9
    .byte $55, $55, $55
    .byte $00          // the 64th byte: alignment, never fetched
square_1_turn:
    .byte $15, $55, $54
    .byte $1a, $aa, $a4
    .byte $1a, $aa, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $40, $a4
    .byte $1a, $55, $a4
    .byte $1a, $aa, $a4
    .byte $1a, $aa, $a4
    .byte $15, $55, $54
    .byte $00          // the 64th byte: alignment, never fetched
square_2_narrow:
    .byte $05, $55, $50
    .byte $06, $aa, $90
    .byte $06, $aa, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $92, $90
    .byte $06, $96, $90
    .byte $06, $aa, $90
    .byte $06, $aa, $90
    .byte $05, $55, $50
    .byte $00          // the 64th byte: alignment, never fetched
square_3_edge:
    .byte $00, $55, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $69, $00
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched
squareFramesEnd:
