// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Dropper: 4 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $1E $1F $20 $21 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 3, 3, 2, 1, 0)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

dropperFrames:
    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $ea, $aa, $6f
    .byte $ea, $aa, $6f
    .byte $6a, $aa, $65
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $2a, $aa, $f8
    .byte $2a, $aa, $f8
    .byte $2a, $aa, $58
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $2a, $be, $68
    .byte $2a, $be, $68
    .byte $2a, $96, $68
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $00, $aa, $00
    .byte $02, $be, $80
    .byte $0a, $ff, $a0
    .byte $0b, $ff, $a0
    .byte $2a, $fe, $a8
    .byte $2a, $be, $a8
    .byte $2a, $aa, $68
    .byte $2f, $aa, $68
    .byte $2f, $aa, $68
    .byte $25, $aa, $68
    .byte $2a, $a9, $68
    .byte $2a, $a9, $68
    .byte $0a, $a5, $a0
    .byte $0a, $a6, $a0
    .byte $02, $9a, $80
    .byte $00, $aa, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
dropperFramesEnd:
