// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Ring 3: 8 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $60 $61 $62 $63 $64 $65 $66 $67 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 3, 4, 5, 6, 7)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

ring3Frames:
    .byte $00, $3c, $00
    .byte $00, $df, $00
    .byte $02, $ff, $80
    .byte $0a, $be, $a0
    .byte $0a, $aa, $a0
    .byte $2a, $96, $a8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $28, $28, $28
    .byte $28, $9a, $28
    .byte $28, $aa, $28
    .byte $28, $69, $28
    .byte $28, $69, $28
    .byte $2a, $14, $a8
    .byte $2a, $82, $a8
    .byte $1a, $aa, $a4
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $aa, $00
    .byte $02, $aa, $f0
    .byte $0a, $ab, $7c
    .byte $0a, $ab, $fc
    .byte $2a, $96, $f8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $28, $28, $28
    .byte $28, $a6, $28
    .byte $28, $aa, $28
    .byte $28, $69, $28
    .byte $28, $69, $28
    .byte $2a, $14, $a8
    .byte $2a, $82, $a8
    .byte $1a, $aa, $a4
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $aa, $00
    .byte $02, $aa, $80
    .byte $0a, $aa, $a0
    .byte $0a, $aa, $a0
    .byte $2a, $96, $a8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $28, $28, $3c
    .byte $28, $aa, $df
    .byte $28, $a6, $ff
    .byte $28, $69, $3c
    .byte $28, $69, $28
    .byte $2a, $14, $a8
    .byte $2a, $82, $a8
    .byte $1a, $aa, $a4
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $aa, $00
    .byte $02, $aa, $80
    .byte $0a, $aa, $a0
    .byte $0a, $aa, $a0
    .byte $2a, $96, $a8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $28, $28, $28
    .byte $28, $aa, $28
    .byte $28, $9a, $28
    .byte $28, $69, $28
    .byte $28, $69, $28
    .byte $2a, $14, $bc
    .byte $2a, $82, $df
    .byte $1a, $aa, $ff
    .byte $1a, $aa, $bc
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $aa, $00
    .byte $02, $aa, $80
    .byte $0a, $aa, $a0
    .byte $0a, $aa, $a0
    .byte $2a, $96, $a8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $28, $28, $28
    .byte $28, $9a, $28
    .byte $28, $aa, $28
    .byte $28, $69, $28
    .byte $28, $69, $28
    .byte $2a, $14, $a8
    .byte $2a, $82, $a8
    .byte $1a, $aa, $a4
    .byte $1a, $be, $a4
    .byte $16, $df, $94
    .byte $05, $ff, $50
    .byte $01, $7d, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $aa, $00
    .byte $02, $aa, $80
    .byte $0a, $aa, $a0
    .byte $0a, $aa, $a0
    .byte $2a, $96, $a8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $28, $28, $28
    .byte $28, $a6, $28
    .byte $28, $aa, $28
    .byte $28, $69, $28
    .byte $28, $69, $28
    .byte $3e, $14, $a8
    .byte $df, $82, $a8
    .byte $ff, $aa, $a4
    .byte $3e, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $aa, $00
    .byte $02, $aa, $80
    .byte $0a, $aa, $a0
    .byte $0a, $aa, $a0
    .byte $2a, $96, $a8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $3c, $28, $28
    .byte $df, $aa, $28
    .byte $ff, $a6, $28
    .byte $3c, $69, $28
    .byte $28, $69, $28
    .byte $2a, $14, $a8
    .byte $2a, $82, $a8
    .byte $1a, $aa, $a4
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $aa, $00
    .byte $0f, $aa, $80
    .byte $37, $ea, $a0
    .byte $3f, $ea, $a0
    .byte $2f, $96, $a8
    .byte $2a, $41, $a8
    .byte $29, $28, $68
    .byte $28, $28, $28
    .byte $28, $aa, $28
    .byte $28, $9a, $28
    .byte $28, $69, $28
    .byte $28, $69, $28
    .byte $2a, $14, $a8
    .byte $2a, $82, $a8
    .byte $1a, $aa, $a4
    .byte $1a, $aa, $a4
    .byte $16, $aa, $94
    .byte $05, $aa, $50
    .byte $01, $55, $40
    .byte $00, $55, $00
    .byte $00          // the 64th byte: alignment, never fetched
ring3FramesEnd:
