// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Modded Alleykat B: 3 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $3B $3C $3D -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 0, 1, 2, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

alleykatBFrames:
    .byte $00, $00, $00
    .byte $00, $3c, $00
    .byte $30, $ff, $0c
    .byte $33, $ff, $cc
    .byte $3f, $d7, $fc
    .byte $37, $d7, $dc
    .byte $31, $ff, $4c
    .byte $10, $7d, $04
    .byte $ff, $3c, $ff
    .byte $aa, $3c, $aa
    .byte $aa, $3c, $aa
    .byte $aa, $3c, $aa
    .byte $aa, $ff, $aa
    .byte $aa, $be, $aa
    .byte $aa, $69, $aa
    .byte $aa, $28, $aa
    .byte $aa, $28, $aa
    .byte $aa, $28, $aa
    .byte $55, $00, $55
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $3c, $00
    .byte $00, $ff, $00
    .byte $33, $ff, $cc
    .byte $3f, $d7, $fc
    .byte $37, $d7, $dc
    .byte $11, $ff, $44
    .byte $00, $7d, $00
    .byte $00, $3c, $00
    .byte $ff, $3c, $ff
    .byte $aa, $3c, $aa
    .byte $aa, $3c, $aa
    .byte $aa, $ff, $aa
    .byte $aa, $be, $aa
    .byte $aa, $69, $aa
    .byte $aa, $28, $aa
    .byte $aa, $28, $aa
    .byte $55, $28, $55
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $3c, $00
    .byte $00, $ff, $00
    .byte $03, $ff, $c0
    .byte $0f, $d7, $f0
    .byte $07, $d7, $d0
    .byte $01, $ff, $40
    .byte $00, $7d, $00
    .byte $00, $3c, $00
    .byte $00, $3c, $00
    .byte $ff, $3c, $ff
    .byte $ff, $3c, $ff
    .byte $ff, $ff, $ff
    .byte $ff, $be, $ff
    .byte $ff, $69, $ff
    .byte $ff, $28, $ff
    .byte $55, $28, $55
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
alleykatBFramesEnd:
