// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Ring 2: 3 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $41 $42 $43 -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 0, 1, 2, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

ring2Frames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $14, $00
    .byte $01, $41, $40
    .byte $04, $00, $10
    .byte $04, $00, $10
    .byte $10, $00, $04
    .byte $10, $00, $04
    .byte $10, $00, $04
    .byte $10, $00, $04
    .byte $10, $00, $04
    .byte $10, $00, $04
    .byte $04, $00, $10
    .byte $04, $00, $10
    .byte $01, $41, $40
    .byte $00, $14, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $14, $00
    .byte $01, $69, $40
    .byte $06, $96, $90
    .byte $19, $41, $64
    .byte $19, $00, $64
    .byte $64, $00, $19
    .byte $64, $00, $19
    .byte $64, $00, $19
    .byte $64, $00, $19
    .byte $64, $00, $19
    .byte $64, $00, $19
    .byte $19, $00, $64
    .byte $19, $41, $64
    .byte $06, $96, $90
    .byte $01, $69, $40
    .byte $00, $14, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $28, $00
    .byte $02, $be, $80
    .byte $0b, $eb, $e0
    .byte $2e, $82, $b8
    .byte $2e, $00, $b8
    .byte $b8, $00, $2e
    .byte $b8, $00, $2e
    .byte $b8, $00, $2e
    .byte $b8, $00, $2e
    .byte $b8, $00, $2e
    .byte $b8, $00, $2e
    .byte $2e, $00, $b8
    .byte $2e, $82, $b8
    .byte $0b, $eb, $e0
    .byte $02, $be, $80
    .byte $00, $2a, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
ring2FramesEnd:
