// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Spinny Rotatey: 5 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $68 $69 $6A $6B $6C -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 3, 4, 0, 1, 2)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

spinnyRotFrames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $bb, $00
    .byte $00, $ee, $00
    .byte $c0, $bb, $03
    .byte $b2, $ee, $8e
    .byte $ae, $55, $ba
    .byte $ab, $43, $ea
    .byte $aa, $43, $aa
    .byte $a9, $43, $6a
    .byte $a6, $7f, $9a
    .byte $92, $66, $86
    .byte $40, $99, $01
    .byte $00, $66, $00
    .byte $00, $99, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $bb, $00
    .byte $00, $ff, $00
    .byte $00, $93, $00
    .byte $02, $de, $80
    .byte $f2, $bb, $8f
    .byte $af, $ee, $fa
    .byte $aa, $bb, $aa
    .byte $a5, $ee, $5a
    .byte $52, $bb, $85
    .byte $02, $66, $80
    .byte $00, $99, $00
    .byte $00, $66, $00
    .byte $00, $99, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $bb, $00
    .byte $00, $57, $00
    .byte $00, $7f, $00
    .byte $02, $ee, $80
    .byte $02, $aa, $80
    .byte $02, $aa, $80
    .byte $ff, $aa, $ff
    .byte $02, $aa, $80
    .byte $02, $aa, $80
    .byte $02, $66, $80
    .byte $00, $99, $00
    .byte $00, $66, $00
    .byte $00, $99, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $bb, $00
    .byte $00, $ee, $00
    .byte $00, $bb, $00
    .byte $02, $ee, $80
    .byte $52, $aa, $85
    .byte $a5, $aa, $5a
    .byte $aa, $aa, $aa
    .byte $af, $aa, $fa
    .byte $f2, $aa, $8f
    .byte $02, $66, $80
    .byte $00, $99, $00
    .byte $00, $66, $00
    .byte $00, $99, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $bb, $00
    .byte $00, $ee, $00
    .byte $40, $bb, $01
    .byte $92, $ee, $86
    .byte $a6, $aa, $9a
    .byte $a9, $aa, $6a
    .byte $aa, $aa, $aa
    .byte $ab, $aa, $ea
    .byte $ae, $aa, $ba
    .byte $b2, $66, $8e
    .byte $c0, $55, $03
    .byte $00, $7f, $00
    .byte $00, $99, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
spinnyRotFramesEnd:
