// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the enemy artwork roster: frame counts
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// Generated from the roster in import_spd.py. A level
// package uses these to prove its chosen artwork fits the
// engine's enemy sprite window.
//
// A ROSTER ENTRY IS ARTWORK, NOT A SPECIES. The engine has
// three behavioural species; a level chooses which artwork
// each of them wears.
// ==========================================================================

.const ENEMY_ROSTER_COUNT = 12
.const ENEMY_ANIM_STEPS_GEN = 8

.const ROSTER_DROPPER = 0               // Dropper, $1E-$21
.const ROSTER_DROPPER_FRAMES = 4
.const ROSTER_SQUARE = 1                // Square, $27-$2A
.const ROSTER_SQUARE_FRAMES = 4
.const ROSTER_ALLEYKAT_A = 2            // Modded Alleykat A, $34-$36
.const ROSTER_ALLEYKAT_A_FRAMES = 3
.const ROSTER_ALLEYKAT_B = 3            // Modded Alleykat B, $3B-$3D
.const ROSTER_ALLEYKAT_B_FRAMES = 3
.const ROSTER_RING_1 = 4                // Ring 1, $3E-$40
.const ROSTER_RING_1_FRAMES = 3
.const ROSTER_RING_2 = 5                // Ring 2, $41-$43
.const ROSTER_RING_2_FRAMES = 3
.const ROSTER_SPINNER = 6               // Spinner, $44-$49
.const ROSTER_SPINNER_FRAMES = 6
.const ROSTER_SPACE_MINE = 7            // Space Mine, $50-$52
.const ROSTER_SPACE_MINE_FRAMES = 3
.const ROSTER_SPINNY = 8                // Spinny Thing, $54-$59
.const ROSTER_SPINNY_FRAMES = 6
.const ROSTER_SPACE_WHISK = 9           // Space Whisk, $5A-$5F
.const ROSTER_SPACE_WHISK_FRAMES = 6
.const ROSTER_RING_3 = 10                // Ring 3, $60-$67
.const ROSTER_RING_3_FRAMES = 8
.const ROSTER_SPINNY_ROT = 11            // Spinny Rotatey, $68-$6C
.const ROSTER_SPINNY_ROT_FRAMES = 5
