// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Square: 4 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $27 $28 $29 $2A -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 3, 3, 2, 1, 0)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

squareFrames:
    .byte $ff, $ff, $fd
    .byte $ea, $aa, $a9
    .byte $ea, $aa, $a9
    .byte $eb, $ff, $e9
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $00, $69
    .byte $eb, $55, $69
    .byte $ea, $aa, $a9
    .byte $ea, $aa, $a9
    .byte $d5, $55, $55
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $3f, $ff, $fc
    .byte $3a, $aa, $a4
    .byte $3a, $aa, $a4
    .byte $3a, $ff, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $c1, $a4
    .byte $3a, $d5, $a4
    .byte $3a, $aa, $a4
    .byte $3a, $aa, $a4
    .byte $35, $55, $54
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $0f, $ff, $f0
    .byte $0e, $aa, $90
    .byte $0e, $aa, $90
    .byte $0e, $be, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $b6, $90
    .byte $0e, $aa, $90
    .byte $0e, $aa, $90
    .byte $0d, $55, $50
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $ff, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $d5, $00
    .byte $00          // the 64th byte: alignment, never fetched
squareFramesEnd:
