// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// Space Whisk: 6 multicolour frame(s)
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// SpritePad $5A $5B $5C $5D $5E $5F -- every frame, in source order.
//
// Animation steps for this artwork: (0, 1, 2, 3, 4, 5, 0, 1)
// (eight steps because the engine masks its phase out of a
// free-running frame counter; see src/enemy.asm.)
//
//     %00  transparent
//     %01  $d025, SPR_MC_DARK   -- shared dark grey
//     %10  $d027+n              -- the TRIGGER's authored colour
//     %11  $d026, SPR_MC_LIGHT  -- shared white
//
// The caller owns the address: a level package pins the window.
// ==========================================================================

spaceWhiskFrames:
    .byte $00, $00, $00
    .byte $00, $34, $00
    .byte $00, $e9, $3f
    .byte $fc, $f9, $15
    .byte $af, $e5, $d0
    .byte $fe, $e9, $90
    .byte $a8, $e9, $1f
    .byte $00, $f9, $15
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $fc, $e9, $00
    .byte $54, $f9, $3f
    .byte $07, $e5, $fa
    .byte $06, $e9, $bf
    .byte $f4, $e9, $2a
    .byte $54, $f9, $00
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $34, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $34, $00
    .byte $00, $e9, $3f
    .byte $00, $f9, $3a
    .byte $ff, $e5, $f0
    .byte $aa, $e9, $b0
    .byte $00, $e9, $3f
    .byte $00, $f9, $2a
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $fc, $e9, $00
    .byte $ac, $f9, $00
    .byte $0f, $e5, $ff
    .byte $0e, $e9, $ff
    .byte $fc, $e9, $00
    .byte $a8, $f9, $00
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $34, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $34, $00
    .byte $00, $e9, $3f
    .byte $a8, $f9, $3a
    .byte $57, $e5, $f0
    .byte $a6, $e9, $b0
    .byte $54, $e9, $3f
    .byte $00, $f9, $2a
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $fc, $e9, $00
    .byte $ac, $f9, $2a
    .byte $0f, $e5, $d5
    .byte $0e, $e9, $9a
    .byte $fc, $e9, $15
    .byte $a8, $f9, $00
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $34, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $34, $00
    .byte $fc, $e9, $00
    .byte $54, $f9, $3f
    .byte $07, $e5, $fa
    .byte $06, $e9, $bf
    .byte $f4, $e9, $2a
    .byte $54, $f9, $00
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $3f
    .byte $fc, $f9, $15
    .byte $af, $e5, $d0
    .byte $fe, $e9, $90
    .byte $a8, $e9, $1f
    .byte $00, $f9, $15
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $34, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $34, $00
    .byte $fc, $e9, $00
    .byte $ac, $f9, $00
    .byte $0f, $e5, $ff
    .byte $0e, $e9, $aa
    .byte $fc, $e9, $00
    .byte $a8, $f9, $00
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $3f
    .byte $00, $f9, $3a
    .byte $ff, $e5, $f0
    .byte $aa, $e9, $b0
    .byte $00, $e9, $3f
    .byte $00, $f9, $2a
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $34, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $34, $00
    .byte $fc, $e9, $00
    .byte $ac, $f9, $2a
    .byte $0f, $e5, $d5
    .byte $0e, $e9, $9a
    .byte $fc, $e9, $15
    .byte $a8, $f9, $00
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $00
    .byte $00, $e9, $3f
    .byte $a8, $f9, $3a
    .byte $57, $e5, $f0
    .byte $a6, $e9, $b0
    .byte $54, $e9, $3f
    .byte $00, $f9, $2a
    .byte $00, $e5, $00
    .byte $00, $e9, $00
    .byte $00, $34, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
spaceWhiskFramesEnd:
