// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the player's death fireball, eight frames
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// Eight 24x21 multicolour blocks that replace the ship's silhouette on
// HW0 the instant the craft dies, so the explosion costs no mux slot.
//
// This file pins itself, as the hand-authored one did.
// ==========================================================================

* = PLAYER_BOOM_SPRITES "player fireball"
playerBoomArt:
playerBoomFrame0:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $20, $00
    .byte $00, $b8, $00
    .byte $02, $fe, $00
    .byte $00, $be, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomFrame1:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $18, $00
    .byte $00, $be, $00
    .byte $02, $ff, $80
    .byte $0b, $ff, $80
    .byte $02, $ff, $e0
    .byte $02, $ff, $80
    .byte $00, $be, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomFrame2:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $24, $00
    .byte $00, $ae, $00
    .byte $02, $ff, $a0
    .byte $0b, $ff, $e0
    .byte $2b, $7d, $f8
    .byte $2f, $ff, $f8
    .byte $2f, $ff, $e0
    .byte $0b, $fd, $e0
    .byte $0a, $ff, $80
    .byte $02, $fe, $80
    .byte $00, $a8, $00
    .byte $00, $20, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomFrame3:
    .byte $00, $00, $00
    .byte $00, $80, $00
    .byte $02, $b2, $00
    .byte $0b, $fe, $80
    .byte $2f, $ff, $e0
    .byte $af, $ff, $f8
    .byte $2f, $f7, $fa
    .byte $bd, $ff, $fe
    .byte $2f, $ff, $78
    .byte $af, $ff, $fe
    .byte $2f, $ff, $f8
    .byte $0b, $7d, $f8
    .byte $2b, $ff, $e0
    .byte $0b, $ff, $80
    .byte $02, $be, $80
    .byte $00, $b8, $00
    .byte $00, $20, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomFrame4:
    .byte $02, $40, $00
    .byte $0a, $d2, $40
    .byte $2f, $ea, $e0
    .byte $af, $ff, $f8
    .byte $bf, $ff, $7a
    .byte $bd, $ff, $fe
    .byte $af, $ff, $fe
    .byte $bf, $dd, $fe
    .byte $bf, $ff, $fe
    .byte $af, $ff, $7e
    .byte $bd, $ff, $fe
    .byte $bf, $ff, $fa
    .byte $af, $ff, $f8
    .byte $2f, $fd, $e0
    .byte $2b, $ff, $a0
    .byte $0b, $fe, $00
    .byte $02, $ba, $00
    .byte $00, $98, $00
    .byte $00, $08, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomFrame5:
    .byte $08, $00, $80
    .byte $22, $02, $80
    .byte $8b, $8b, $82
    .byte $2f, $2f, $28
    .byte $8f, $3f, $32
    .byte $2c, $bc, $b0
    .byte $83, $cf, $08
    .byte $2c, $f3, $c8
    .byte $83, $c3, $0a
    .byte $2c, $f3, $c8
    .byte $83, $3c, $c8
    .byte $23, $c3, $c8
    .byte $83, $3c, $20
    .byte $28, $f2, $80
    .byte $08, $f2, $00
    .byte $02, $88, $00
    .byte $08, $20, $20
    .byte $20, $08, $00
    .byte $00, $08, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomFrame6:
    .byte $08, $00, $20
    .byte $00, $00, $00
    .byte $80, $c0, $c2
    .byte $04, $01, $00
    .byte $20, $cc, $08
    .byte $00, $00, $00
    .byte $80, $4c, $02
    .byte $0c, $00, $30
    .byte $00, $00, $00
    .byte $20, $c1, $08
    .byte $00, $00, $00
    .byte $80, $30, $08
    .byte $04, $00, $c0
    .byte $20, $00, $20
    .byte $00, $00, $00
    .byte $0c, $04, $00
    .byte $20, $40, $80
    .byte $00, $00, $00
    .byte $00, $82, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomFrame7:
    .byte $10, $00, $20
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $08, $01, $00
    .byte $00, $00, $00
    .byte $00, $10, $00
    .byte $00, $00, $00
    .byte $10, $00, $20
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $01, $00, $80
    .byte $00, $00, $00
    .byte $00, $10, $00
    .byte $20, $00, $10
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $04, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
playerBoomArtEnd:
