// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the muzzle flash, one per attitude
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// The caller owns the address: src/player.asm sets
// * = PLAYER_FLASH_SPRITES and wraps this in its own labels.
// ==========================================================================

player_muzzle_flash_frames:
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $80
    .byte $00, $00, $80
    .byte $00, $02, $a0
    .byte $00, $02, $e0
    .byte $08, $02, $e0
    .byte $08, $02, $e0
    .byte $2a, $01, $50
    .byte $2e, $00, $00
    .byte $2e, $00, $00
    .byte $2e, $00, $00
    .byte $15, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $20
    .byte $00, $00, $20
    .byte $08, $00, $a8
    .byte $08, $00, $b8
    .byte $2a, $00, $b8
    .byte $2e, $00, $b8
    .byte $2e, $00, $54
    .byte $2e, $00, $00
    .byte $15, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $08, $00, $20
    .byte $08, $00, $20
    .byte $2a, $00, $a8
    .byte $2e, $00, $b8
    .byte $2e, $00, $b8
    .byte $2e, $00, $b8
    .byte $15, $00, $54
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $08, $00, $00
    .byte $08, $00, $00
    .byte $2a, $00, $20
    .byte $2e, $00, $20
    .byte $2e, $00, $a8
    .byte $2e, $00, $b8
    .byte $15, $00, $b8
    .byte $00, $00, $b8
    .byte $00, $00, $54
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $02, $00, $00
    .byte $02, $00, $00
    .byte $0a, $80, $00
    .byte $0b, $80, $00
    .byte $0b, $80, $20
    .byte $0b, $80, $20
    .byte $05, $40, $a8
    .byte $00, $00, $b8
    .byte $00, $00, $b8
    .byte $00, $00, $b8
    .byte $00, $00, $54
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched
