// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the player ship, fifteen multicolour frames
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// Five banking attitudes x three engine frames, bank-major:
//     index = bank * 3 + engine
//     bank 0..4 = hard left .. hard right
//     engine 0..2 = flame full, small, out
//
// The SIXTEENTH block is NOT here. src/player.asm emits it itself as
// playerBlankBitmap -- the blank HW1 draws -- and this importer checks
// that the .spd's slot 15 is still blank so the two cannot disagree.
//
// The caller owns the address: src/player.asm sets * = PLAYER_SPRITES.
// ==========================================================================

player_art_frames:
    .byte $00, $30, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $c0
    .byte $00, $b8, $c0
    .byte $00, $a8, $80
    .byte $00, $af, $80
    .byte $0c, $bd, $c0
    .byte $08, $ee, $ac
    .byte $08, $ee, $ac
    .byte $0b, $ed, $ac
    .byte $0d, $75, $ab
    .byte $0a, $de, $eb
    .byte $0a, $de, $eb
    .byte $09, $ee, $00
    .byte $39, $54, $00
    .byte $2e, $b8, $00
    .byte $2e, $b8, $00
    .byte $e0, $20, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $30, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $c0
    .byte $00, $b8, $c0
    .byte $00, $a8, $80
    .byte $00, $af, $80
    .byte $0c, $bd, $c0
    .byte $08, $ee, $ac
    .byte $08, $ee, $ac
    .byte $0b, $ed, $ac
    .byte $0d, $75, $ab
    .byte $0a, $de, $eb
    .byte $0a, $de, $eb
    .byte $09, $ee, $00
    .byte $39, $54, $00
    .byte $2e, $20, $00
    .byte $2e, $20, $00
    .byte $e0, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $30, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $00
    .byte $00, $b8, $c0
    .byte $00, $b8, $c0
    .byte $00, $a8, $80
    .byte $00, $af, $80
    .byte $0c, $bd, $c0
    .byte $08, $ee, $ac
    .byte $08, $ee, $ac
    .byte $0b, $ed, $ac
    .byte $0d, $75, $ab
    .byte $0a, $de, $eb
    .byte $0a, $de, $eb
    .byte $09, $ee, $00
    .byte $39, $54, $00
    .byte $2e, $00, $00
    .byte $2e, $00, $00
    .byte $e0, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $9e, $00
    .byte $00, $ae, $00
    .byte $00, $aa, $30
    .byte $00, $eb, $20
    .byte $0c, $ff, $e0
    .byte $08, $eb, $70
    .byte $08, $eb, $70
    .byte $0b, $eb, $ac
    .byte $0d, $7d, $6c
    .byte $0a, $d7, $6b
    .byte $0a, $d7, $6b
    .byte $39, $eb, $bb
    .byte $29, $55, $80
    .byte $ee, $be, $00
    .byte $ee, $be, $00
    .byte $00, $28, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $9e, $00
    .byte $00, $ae, $00
    .byte $00, $aa, $30
    .byte $00, $eb, $20
    .byte $0c, $ff, $e0
    .byte $08, $eb, $70
    .byte $08, $eb, $70
    .byte $0b, $eb, $ac
    .byte $0d, $7d, $6c
    .byte $0a, $d7, $6b
    .byte $0a, $d7, $6b
    .byte $39, $eb, $bb
    .byte $29, $55, $80
    .byte $ee, $28, $00
    .byte $ee, $28, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $9e, $00
    .byte $00, $ae, $00
    .byte $00, $aa, $30
    .byte $00, $eb, $20
    .byte $0c, $ff, $e0
    .byte $08, $eb, $70
    .byte $08, $eb, $70
    .byte $0b, $eb, $ac
    .byte $0d, $7d, $6c
    .byte $0a, $d7, $6b
    .byte $0a, $d7, $6b
    .byte $39, $eb, $bb
    .byte $29, $55, $80
    .byte $ee, $00, $00
    .byte $ee, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $aa, $00
    .byte $0c, $eb, $30
    .byte $08, $ff, $20
    .byte $0b, $eb, $e0
    .byte $0b, $eb, $e0
    .byte $0d, $eb, $70
    .byte $3a, $7d, $ac
    .byte $39, $d7, $6c
    .byte $39, $d7, $6c
    .byte $e9, $eb, $6b
    .byte $ee, $55, $bb
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $28, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $aa, $00
    .byte $0c, $eb, $30
    .byte $08, $ff, $20
    .byte $0b, $eb, $e0
    .byte $0b, $eb, $e0
    .byte $0d, $eb, $70
    .byte $3a, $7d, $ac
    .byte $39, $d7, $6c
    .byte $39, $d7, $6c
    .byte $e9, $eb, $6b
    .byte $ee, $55, $bb
    .byte $00, $28, $00
    .byte $00, $28, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $aa, $00
    .byte $0c, $eb, $30
    .byte $08, $ff, $20
    .byte $0b, $eb, $e0
    .byte $0b, $eb, $e0
    .byte $0d, $eb, $70
    .byte $3a, $7d, $ac
    .byte $39, $d7, $6c
    .byte $39, $d7, $6c
    .byte $e9, $eb, $6b
    .byte $ee, $55, $bb
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $b6, $00
    .byte $00, $ba, $00
    .byte $0c, $aa, $00
    .byte $08, $eb, $00
    .byte $0b, $ff, $30
    .byte $0d, $eb, $20
    .byte $0d, $eb, $20
    .byte $3a, $eb, $e0
    .byte $39, $7d, $70
    .byte $e9, $d7, $a0
    .byte $e9, $d7, $a0
    .byte $ee, $eb, $6c
    .byte $02, $55, $68
    .byte $00, $be, $bb
    .byte $00, $be, $bb
    .byte $00, $28, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $b6, $00
    .byte $00, $ba, $00
    .byte $0c, $aa, $00
    .byte $08, $eb, $00
    .byte $0b, $ff, $30
    .byte $0d, $eb, $20
    .byte $0d, $eb, $20
    .byte $3a, $eb, $e0
    .byte $39, $7d, $70
    .byte $e9, $d7, $a0
    .byte $e9, $d7, $a0
    .byte $ee, $eb, $6c
    .byte $02, $55, $68
    .byte $00, $28, $bb
    .byte $00, $28, $bb
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $3c, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $be, $00
    .byte $00, $b6, $00
    .byte $00, $ba, $00
    .byte $0c, $aa, $00
    .byte $08, $eb, $00
    .byte $0b, $ff, $30
    .byte $0d, $eb, $20
    .byte $0d, $eb, $20
    .byte $3a, $eb, $e0
    .byte $39, $7d, $70
    .byte $e9, $d7, $a0
    .byte $e9, $d7, $a0
    .byte $ee, $eb, $6c
    .byte $02, $55, $68
    .byte $00, $00, $bb
    .byte $00, $00, $bb
    .byte $00, $00, $00
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $0c, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $03, $2e, $00
    .byte $03, $2e, $00
    .byte $02, $2a, $00
    .byte $02, $fa, $00
    .byte $03, $7e, $30
    .byte $3a, $bb, $20
    .byte $3a, $bb, $20
    .byte $3a, $7b, $e0
    .byte $ea, $5d, $70
    .byte $eb, $b7, $a0
    .byte $eb, $b7, $a0
    .byte $00, $bb, $60
    .byte $00, $15, $6c
    .byte $00, $2e, $b8
    .byte $00, $2e, $b8
    .byte $00, $08, $0b
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $0c, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $03, $2e, $00
    .byte $03, $2e, $00
    .byte $02, $2a, $00
    .byte $02, $fa, $00
    .byte $03, $7e, $30
    .byte $3a, $bb, $20
    .byte $3a, $bb, $20
    .byte $3a, $7b, $e0
    .byte $ea, $5d, $70
    .byte $eb, $b7, $a0
    .byte $eb, $b7, $a0
    .byte $00, $bb, $60
    .byte $00, $15, $6c
    .byte $00, $08, $b8
    .byte $00, $08, $b8
    .byte $00, $00, $0b
    .byte $00          // the 64th byte: alignment, never fetched

    .byte $00, $0c, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $00, $2e, $00
    .byte $03, $2e, $00
    .byte $03, $2e, $00
    .byte $02, $2a, $00
    .byte $02, $fa, $00
    .byte $03, $7e, $30
    .byte $3a, $bb, $20
    .byte $3a, $bb, $20
    .byte $3a, $7b, $e0
    .byte $ea, $5d, $70
    .byte $eb, $b7, $a0
    .byte $eb, $b7, $a0
    .byte $00, $bb, $60
    .byte $00, $15, $6c
    .byte $00, $00, $b8
    .byte $00, $00, $b8
    .byte $00, $00, $0b
    .byte $00          // the 64th byte: alignment, never fetched
