// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the stamp that makes a stale sprite tree impossible to miss
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// Nothing imports this file for its contents -- it has none. It
// records which .spd the generated art beside it came from, and
// tools/sprite_export/import_spd.py --check compares it with the
// file on disk. `make build` runs that check, so editing the .spd
// and forgetting to regenerate fails the build instead of quietly
// shipping the previous artwork.
// ==========================================================================
