// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// the collectible token
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: f70e5a967d7acff2a7f6293a86387141ad1ce4073ecd0dab5ce31168e5ff31c9
//
// The caller owns the address and the labels: src/pickup.asm pins
// this between the muzzle flash and the fireball.
// ==========================================================================

    .byte $15, $55, $54
    .byte $55, $55, $55
    .byte $55, $55, $55
    .byte $5a, $aa, $95
    .byte $5a, $aa, $a5
    .byte $5a, $55, $a5
    .byte $5a, $55, $a5
    .byte $5a, $55, $a5
    .byte $5a, $55, $a5
    .byte $5a, $aa, $a5
    .byte $5a, $aa, $95
    .byte $5a, $55, $55
    .byte $5a, $55, $55
    .byte $5a, $55, $55
    .byte $5a, $55, $55
    .byte $5a, $55, $55
    .byte $5a, $55, $55
    .byte $5a, $55, $55
    .byte $55, $55, $55
    .byte $55, $55, $55
    .byte $15, $55, $54
    .byte $00          // the 64th byte: alignment, never fetched
