// ============================================================================
// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.
// Level: level1
//
// CONSTANTS-ONLY level-config include. Emits no bytes, no memory segment,
// no program-counter change. Imported very early so every level-owned
// constant exists before the engine constants/code that consume them.
//
// Ownership: these values belong to the level package, NOT to the engine.
// The engine derives STAGE_LOGICAL_ROWS = STAGE_METATILE_ROWS * METATILE_H
// and METATILE_DEF_COUNT = STAGE_METATILE_COUNT (the level's metatile-def
// table is variable length: STAGE_METATILE_COUNT * 16 bytes, 1..64).
//   TERRAIN_BACKGROUND_COLOUR -> $D021
//   TERRAIN_MC_COLOUR_1       -> $D022   (multicolour bit-pair 01)
//   TERRAIN_MC_COLOUR_2       -> $D023   (multicolour bit-pair 10)
//   TERRAIN_CHARACTER_COLOUR  -> colour RAM low 3 bits (bit-pair 11)
// TERRAIN_GLYPH_COUNT is level-owned too (the tileset lives in
// stage_charset.asm); it is declared here so the engine's early glyph-
// namespace guards resolve before the byte block is imported.
// ============================================================================
.const STAGE_METATILE_ROWS     = 105

// THE BOSS APPROACH. No ordinary authored encounter may START at or after this
// world-progress row, which is what turns the run-in to the boss from "whatever
// happened to be left over" into an authored, deterministic clearance.
//
// SAME COORDINATE DOMAIN AS A TRIGGER ROW: coarse rows of worldProgress, 16-bit,
// counted from the start of the stage. The stage's own last complete view is
// STAGE_METATILE_ROWS * 4 - 25 = 395, so this leaves 55 rows of approach.
//
// FIFTY-FIVE IS DERIVED, NOT PICKED. The longest authored wave in this level --
// the loop -- occupies 48 coarse rows from its first member leaving the spawn
// line to its last member reaching a despawn edge (see the footprint table in
// src/wave_encounters.asm). A clearance shorter than that could let a wave
// started on the last legal row still be on screen when the stage ends, which
// is precisely the situation ARENA_CLEAR_DEADLINE exists to mop up. Making the
// zone longer than the worst footprint means the deadline stays a backstop
// rather than the mechanism.
//
// IT FORBIDS, IT DOES NOT DESCRIBE. Rows 127..339 are perfectly legal to author
// in; this level simply has no content there yet. The value says where authoring
// STOPS, not where the action happens to stop.
.const STAGE_NO_SPAWN_ROW      = 340
.const SCROLL_FRAME_DIVIDER    = 2
.const STAGE_METATILE_COUNT   = 34
.const TERRAIN_BACKGROUND_COLOUR = 12
.const TERRAIN_MC_COLOUR_1     = 15
.const TERRAIN_MC_COLOUR_2     = 11
.const TERRAIN_CHARACTER_COLOUR = 1
.const TERRAIN_COLOUR_RAM      = 8 | TERRAIN_CHARACTER_COLOUR
.const TERRAIN_GLYPH_COUNT     = 72
