// ==========================================================================
// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.
// Level: level1
//
// Authored turret PLACEMENT layer. Constants + assembler lists only.
// PLACEMENT is editor-owned; BEHAVIOUR stays engine-owned (src/turrets.asm).
//
//   world row = metatileRow * 4 + 1
//   world col = metatileCol * 4 + 1
//
// Rows are 16-bit and sorted DESCENDING -- the order the downward-scrolling
// stage crosses them.
//
// CONTRACT v2 TEMPORARY LIMITS: at most 8 turrets (trtDeadPending is one
// byte, one bit per turret) and at most one per metatile row (turretAtMetaRow
// holds a single index). Both are scheduled to be lifted.
// ==========================================================================
.const TURRET_TOTAL = 8
.var turretCols = List().add(17, 25, 29, 9, 25, 13, 25, 13)
.var turretRows = List().add(345, 337, 225, 217, 117, 109, 25, 5)
