// ==========================================================================
// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.
// Level: level1
//
// this level's claim on the SPRITE artwork
// ==========================================================================

// The enemy sprite window is level-owned artwork: the package carries
// the bytes and levelApplySprites copies them into LEVEL_SPRITES at
// level init. This names which generated blocks fill the window, in
// WINDOW ORDER -- slot 0 first, contiguously.
//
// IT IS A MANIFEST, NOT ARTWORK. Every block comes from
// src/generated_sprites/, produced by tools/sprite_export/import_spd.py
// from assets/sprites/19656-sprites.spd. SpritePad remains the
// authority; this only says which of its output this level ships.
//
// ONLY THE CHOSEN ARTWORK IS SHIPPED. The roster has twelve sequences;
// a level carries the three it uses, which is what keeps it inside the
// engine's 20-block window.

#importonce

#import "generated_sprites/enemy_ring_3_art.asm"                          // slots 0-7  Ring 3
#import "generated_sprites/enemy_dropper_art.asm"                         // slots 8-11  Dropper
#import "generated_sprites/enemy_space_whisk_art.asm"                     // slots 12-17  Space Whisk
