// ==========================================================================
// AUTO-GENERATED by tools/sprite_export/import_spd.py.
// DO NOT EDIT BY HAND -- the next import overwrites this file.
//
// which enemy identities this level's three slots hold -- level2
//
// Source of truth: assets/sprites/19656-sprites.spd, edited in
// Spritemate. Regenerate with `make sprites`.
// spd sha256: b1d8ef40fc6867ce26e64a3131867da3ebd6c2701bc19fdd51c1efa508ca351f
//
// A ROSTER ENTRY IS ARTWORK, NOT A SPECIES. The engine has
// three behavioural species -- RING, DROPPER, SQUARE -- and
// this file says which artwork each of them wears here, and
// where in the enemy sprite window that artwork was loaded.
//
// levelAnimOffsets is the whole animation contract: one byte
// per (species, step), holding the WINDOW-RELATIVE BLOCK that
// step shows. The engine adds its window base and nothing
// else. A species wearing eight-frame artwork simply names
// eight different blocks; nothing counts frames at run time.
// ==========================================================================

.const LVL_SLOT_RING     = 0  // Ring 3, 8 frame(s), $60-$67
.const LVL_SLOT_DROPPER  = 8  // Dropper, 4 frame(s), $1E-$21
.const LVL_SLOT_SQUARE   = 12 // Square, 4 frame(s), $27-$2A

.const LVL_SPR_BLOCKS = 16   // of 20

.const LVL_DROP_ROW  = $08   // DROPPER slot carries the token
.const LVL_PLAIN_ROW = $00   // RING slot, ordinary behaviour

.var LVL_ANIM = List()
    .eval LVL_ANIM.add(0).add(1).add(2).add(3).add(4).add(5).add(6).add(7)   // RING: Ring 3
    .eval LVL_ANIM.add(8).add(9).add(10).add(11).add(11).add(10).add(9).add(8)   // DROPPER: Dropper
    .eval LVL_ANIM.add(12).add(13).add(14).add(15).add(15).add(14).add(13).add(12)   // SQUARE: Square
