// ==========================================================================
// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.
// Level: level2
//
// THE AUTHORED ENCOUNTER SCHEDULE, as data. Constants and .var data only:
// this file emits no bytes and moves no program counter.
//
// Both builds import it -- src/waves.asm validates it and flies every member
// of every wave at assembly time, and src/level_package.asm emits the bytes
// into the level package. The vocabulary is engine-owned and lives in
// src/encounter_format.asm.
//
// WHAT IS DELIBERATELY NOT HERE: anything the engine owns. The Dropper's
// flight, the P-token, the protector conscription and the boss lifecycle are
// engine state machines a level does not author; the only thing a level says
// about the Dropper is which trigger carries it and which side it enters
// from.
// ==========================================================================
#importonce
#import "encounter_format.asm"
#import "wave_programs.asm"

// --- the wave definitions -------------------------------------------
// Ten bytes each, read by the director with one indexed load per field:
//   0 count      how many enemies this wave sends
//   1 interval   frames between one member and the next
//   2 startXLo   nine-bit spawn X...
//   3 startXHi
//   4 startY     spawn line
//   5 xStep      signed, added to X per member
//   6 yStep      signed, added to Y per member
//   7 colour     every member of a wave shares one
//   8 heading    launch heading, 0..WM_HEAD_LEN-1
//   9 program    a program INDEX here; src/level_package.asm emits it as
//                that program's BYTE OFFSET via progAt
.const WAVEDEF_SIZE = 10

.var defSweep = List().add(
    4, 22,                    // count, interval
    0, 0,                     // startX = 0, nine bits split low/high
    64,                       // startY
    0, 20,                    // xStep, yStep -- signed, per member
    10,                       // colour
    0,                        // launch heading
    PROG_SWEEP)               // movement program INDEX

.var defS = List().add(
    3, 26,                    // count, interval
    90, 0,                    // startX = 90, nine bits split low/high
    30,                       // startY
    28, 0,                    // xStep, yStep -- signed, per member
    3,                        // colour
    12,                       // launch heading
    PROG_S)                   // movement program INDEX

.var defLinger = List().add(
    3, 26,                    // count, interval
    120, 0,                   // startX = 120, nine bits split low/high
    30,                       // startY
    36, 0,                    // xStep, yStep -- signed, per member
    7,                        // colour
    10,                       // launch heading
    PROG_LINGER)              // movement program INDEX

.var defLoop = List().add(
    3, 34,                    // count, interval
    70, 0,                    // startX = 70, nine bits split low/high
    30,                       // startY
    50, 0,                    // xStep, yStep -- signed, per member
    13,                       // colour
    8,                        // launch heading
    PROG_LOOP)                // movement program INDEX

.var defLoop5 = List().add(
    5, 34,                    // count, interval
    70, 0,                    // startX = 70, nine bits split low/high
    30,                       // startY
    50, 0,                    // xStep, yStep -- signed, per member
    13,                       // colour
    8,                        // launch heading
    PROG_LOOP)                // movement program INDEX

.var defDive4 = List().add(
    4, 30,                    // count, interval
    175, 0,                   // startX = 175, nine bits split low/high
    0,                        // startY
    35, 0,                    // xStep, yStep -- signed, per member
    1,                        // colour
    0,                        // launch heading
    PROG_DIVE_BOMB)           // movement program INDEX

.var defUpNOver = List().add(
    6, 25,                    // count, interval
    0, 0,                     // startX = 0, nine bits split low/high
    200,                      // startY
    0, 0,                     // xStep, yStep -- signed, per member
    1,                        // colour
    0,                        // launch heading
    PROG_UP_N_OVER)           // movement program INDEX

.var waveDefs = List().add(defSweep).add(defS).add(defLinger).add(defLoop).add(defLoop5).add(defDive4).add(defUpNOver)
.const WAVE_DEFS              = 7
.const WAVE_DEF_SWEEP         = 0
.const WAVE_DEF_S             = 1
.const WAVE_DEF_LINGER        = 2
.const WAVE_DEF_LOOP          = 3
.const WAVE_DEF_LOOP_5        = 4
.const WAVE_DEF_DIVE_4        = 5
.const WAVE_DEF_UP_N_OVER     = 6
.if (waveDefs.size() != WAVE_DEFS) { .error "wave definition count disagrees with the table" }

// --- the absolute trigger list --------------------------------------
// ABSOLUTE SIXTEEN-BIT worldProgress ROWS, and the list does not repeat.
// A trigger names one row; once consumed it never becomes due again. The
// rows must be NON-DECREASING because the director's cursor only ever
// walks forward, and every row must be below STAGE_NO_SPAWN_ROW.
.var trigRow      = List().add(20, 52, 90, 126, 160, 205, 260)

// Which definition each appearance plays.
.var trigDef      = List().add(WAVE_DEF_SWEEP, WAVE_DEF_S, WAVE_DEF_LINGER, WAVE_DEF_LOOP, WAVE_DEF_LOOP_5, WAVE_DEF_DIVE_4, WAVE_DEF_UP_N_OVER)

// WHICH ENEMY THE WAVE IS MADE OF -- an authored column rather than
// arithmetic on the cursor, so inserting a trigger cannot silently invert
// every wave after it.
.var trigSpecies  = List().add(SPECIES_RING, SPECIES_DROPPER, SPECIES_RING, SPECIES_DROPPER, SPECIES_RING, SPECIES_RING, SPECIES_RING)

// WHICH SIDE A DROPPER FLIES IN FROM. Read only when the species above is
// SPECIES_DROPPER; a Ring wave carries whatever is written here and
// ignores it.
.var trigSide     = List().add(DROP_SIDE_LEFT, DROP_SIDE_LEFT, DROP_SIDE_LEFT, DROP_SIDE_RIGHT, DROP_SIDE_LEFT, DROP_SIDE_LEFT, DROP_SIDE_LEFT)

// WHICH MEMBERS OF THIS APPEARANCE MAY SHOOT -- a bitmask over MEMBER
// INDEX, bit 0 the first member sent, and zero for a formation that does
// not shoot at all.
.var trigFire     = List().add(%00000101, %00000010, %00000101, %00000000, %00000101, %00001111, %00110111)

.const WAVE_TRIGGERS          = 7
