// ==========================================================================
// AUTO-GENERATED by tools/level_editor. DO NOT EDIT BY HAND.
// Level: level2
//
// THE MOVEMENT PROGRAM POOL, as authored data. Constants and .var data
// only: this file emits no bytes and moves no program counter.
//
// Both builds import it -- src/waves.asm validates and flies every path at
// assembly time, and src/level_package.asm emits the records into the level
// package at LEVELPKG_MOVE. The record format is engine-owned and lives in
// src/movement_format.asm.
//
//     kind            arg             byte 2           byte 3
//     WM_STRAIGHT     frames          vx               vy
//     WM_HOLD         frames          vx               vy
//     WM_ARC          heading steps   frames per step  entry heading, or
//     WM_ARC_MIRROR   heading steps   frames per step  WM_HEAD_CONT
//     WM_EXIT         --              --               --
//
// Velocities are signed quarter-pixels per frame. Headings run clockwise
// from east in WM_HEAD_LEN steps, with +y DOWN.
// ==========================================================================
#importonce
#import "movement_format.asm"

.var progs = List()

// --- 0: SWEEP -----------------------------------------------------
.eval progs.add(List()
    .add(List().add(WM_STRAIGHT, 34, 6, 0))
    .add(List().add(WM_ARC, 16, 4, 0))
    .add(List().add(WM_EXIT, 0, 0, 0)))

// --- 1: S ---------------------------------------------------------
.eval progs.add(List()
    .add(List().add(WM_ARC_MIRROR, 12, 3, 12))
    .add(List().add(WM_ARC, 20, 3, WM_HEAD_CONT))
    .add(List().add(WM_EXIT, 0, 0, 0)))

// --- 2: LINGER ----------------------------------------------------
.eval progs.add(List()
    .add(List().add(WM_STRAIGHT, 28, 3, 5))
    .add(List().add(WM_HOLD, 48, 0, 1))
    .add(List().add(WM_ARC, 12, 4, 10))
    .add(List().add(WM_EXIT, 0, 0, 0)))

// --- 3: LOOP ------------------------------------------------------
.eval progs.add(List()
    .add(List().add(WM_STRAIGHT, 40, 4, 4))
    .add(List().add(WM_ARC, 76, 2, 8))
    .add(List().add(WM_EXIT, 0, 0, 0)))

// --- 4: DIVE_BOMB -------------------------------------------------
.eval progs.add(List()
    .add(List().add(WM_STRAIGHT, 60, 0, 6))
    .add(List().add(WM_ARC, 32, 4, 16))
    .add(List().add(WM_EXIT, 0, 0, 0)))

// --- 5: UP_N_OVER -------------------------------------------------
.eval progs.add(List()
    .add(List().add(WM_STRAIGHT, 125, 4, -4))
    .add(List().add(WM_ARC, 16, 4, 56))
    .add(List().add(WM_EXIT, 0, 0, 0)))

.const PROG_SWEEP             = 0
.const PROG_S                 = 1
.const PROG_LINGER            = 2
.const PROG_LOOP              = 3
.const PROG_DIVE_BOMB         = 4
.const PROG_UP_N_OVER         = 5

// Byte offsets of each program's first record, computed rather than
// authored: a hand-maintained offset is a number that is right until
// somebody inserts a stage.
.var progAt = List()
.var progBytes = 0
.for (var p = 0; p < progs.size(); p++) {
    .eval progAt.add(progBytes)
    .eval progBytes = progBytes + WM_STAGE_SIZE * progs.get(p).size()
}
// ONE BYTE OF CURSOR, AND THAT IS THE WHOLE CEILING: every object carries
// its position in this pool in wmStage.
.if (progBytes > 256) {
    .error "the stage table has outgrown the one-byte cursor in wmStage"
}
