#!/usr/bin/env python3
"""Generate the 420-metatile-row CAPACITY PROOF level from the authored Level 1.

    python3 tools/gen_proof420.py <out-dir>

WHAT IT IS FOR. It is not level design. It exists to put a genuinely long stage
through the engine -- 420 metatile rows, 1,680 logical rows, 1,655 coarse steps,
about four and a half minutes of scrolling -- so that every stage-row counter,
table index and world-row comparison is exercised well past the 8-bit boundaries
a 105-row level never reaches.

WHAT IT DOES, AND WHAT IT DELIBERATELY DOES NOT. The terrain is the authored
Level 1 map repeated FOUR TIMES, byte for byte, in order. Nothing is invented
and nothing is edited. The metatile definitions and the charset are shared and
are NOT repeated -- there is one tile set, and four copies of it would be four
copies of the same bytes.

TURRETS. The eight authored turrets are spread two-per-copy rather than
replicated four times, and that is a constraint of the engine rather than a
choice: src/turrets.asm keeps its per-turret "repair owed" flags in a single
byte and fails the build above eight turrets. Spreading them preserves each
turret's position WITHIN its copy, keeps the authored count legal, and is what
actually matters for the proof -- it puts authored world rows either side of
every 8-bit boundary the stage crosses:

    copy 0 (+0)      rows 5, 25          below 255
    copy 1 (+420)    rows 529, 537       above 511
    copy 2 (+840)    rows 1057, 1065     above 1023
    copy 3 (+1260)   rows 1597, 1605     above 1535
"""
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "level1"
COPIES = 4
QUIET_ROWS = 55        # the boss approach, preserved from the authored level


def read_block(text, start, end):
    body = text.split(start)[1].split(end)[0]
    return [ln for ln in body.splitlines() if ln.split("//")[0].strip().startswith(".byte")]


def main():
    out = Path(sys.argv[1] if len(sys.argv) > 1 else ROOT / "build" / "proof420")
    out.mkdir(parents=True, exist_ok=True)

    cfg = (SRC / "stage_config.asm").read_text()
    rows0 = int(re.search(r"STAGE_METATILE_ROWS\s*=\s*(\d+)", cfg).group(1))
    rows = rows0 * COPIES
    stage_rows0 = rows0 * 4                       # logical rows per copy

    # ---- stage_config: the height, and the boss approach that follows it --
    # STAGE_NO_SPAWN_ROW HAS TO SCALE WITH THE STAGE. It is a world-progress row
    # and the proof stage is four times as long, so the authored 105-row value
    # would put the quiet zone three and a half minutes before the boss. The
    # clearance itself is what is meaningful, so that is what is preserved:
    # the same 55 rows of approach measured back from this stage's own end.
    stage_end = rows * 4 - 25
    no_spawn = stage_end - QUIET_ROWS
    cfg2 = re.sub(r"(STAGE_METATILE_ROWS\s*=\s*)\d+", r"\g<1>%d" % rows, cfg, count=1)
    cfg2 = re.sub(r"(STAGE_NO_SPAWN_ROW\s*=\s*)\d+", r"\g<1>%d" % no_spawn, cfg2, count=1)
    # The generated config's own comment quotes the derived stage end and quiet
    # zone. Rescaling the constants and leaving the prose behind would ship a
    # file that contradicts itself.
    cfg2 = re.sub(r"(STAGE_METATILE_ROWS \* 4 - 25 = )\d+", r"\g<1>%d" % stage_end,
                  cfg2, count=1)
    cfg2 = re.sub(r"(// leaves )\d+( rows of approach)", r"\g<1>%d\g<2>" % QUIET_ROWS,
                  cfg2, count=1)
    (out / "stage_config.asm").write_text(
        cfg2.replace("// Level: level1", "// Level: level1 x%d CAPACITY PROOF" % COPIES))

    # ---- stage_map: defs once, rows four times ---------------------------
    m = (SRC / "stage_map.asm").read_text()
    defs = read_block(m, "metatileDefs:", "METATILE_DEFS_END:")
    body = read_block(m, "stageMetatileRows:", "STAGE_METATILE_ROWS_END:")
    assert len(body) == rows0, (len(body), rows0)
    lines = ["// GENERATED by tools/gen_proof420.py -- capacity proof, not level design.",
             "// The authored Level 1 terrain, repeated %d times. Bytes are unmodified." % COPIES,
             "metatileDefs:"] + defs + ["METATILE_DEFS_END:", "stageMetatileRows:"]
    for c in range(COPIES):
        lines.append("// ---- copy %d: metatile rows %d..%d ----" % (c, c * rows0, c * rows0 + rows0 - 1))
        lines += [re.sub(r"// row (\d+)", lambda mm, c=c: "// row %d" % (int(mm.group(1)) + c * rows0), ln)
                  for ln in body]
    lines.append("STAGE_METATILE_ROWS_END:")
    (out / "stage_map.asm").write_text("\n".join(lines) + "\n")

    # ---- stage_turrets: two per copy, offset into their copy -------------
    tur = (SRC / "stage_turrets.asm").read_text()
    cols = [int(x) for x in re.search(r"turretCols\s*=\s*List\(\)((?:\.add\([^)]*\))+)", tur).group(1).replace(".add(", "").replace(")", ",").split(",") if x.strip()]
    rws = [int(x) for x in re.search(r"turretRows\s*=\s*List\(\)((?:\.add\([^)]*\))+)", tur).group(1).replace(".add(", "").replace(")", ",").split(",") if x.strip()]
    assert len(cols) == len(rws) == 8, (cols, rws)
    order = sorted(range(8), key=lambda i: -rws[i])          # descending, as emitted
    pairs = []
    for slot, i in enumerate(order):
        copy = COPIES - 1 - (slot // 2)                      # highest rows in the last copy
        pairs.append((rws[i] + copy * stage_rows0, cols[i]))
    pairs.sort(key=lambda p: -p[0])
    (out / "stage_turrets.asm").write_text(
        "// GENERATED by tools/gen_proof420.py -- capacity proof, not level design.\n"
        "// The eight authored turrets, two per terrain copy, each offset by its\n"
        "// copy's world-row base. See the module docstring for why not thirty-two.\n"
        ".const TURRET_TOTAL = %d\n" % len(pairs) +
        ".var turretCols = List()" + "".join(".add(%d)" % c for _, c in pairs) + "\n" +
        ".var turretRows = List()" + "".join(".add(%d)" % r for r, _ in pairs) + "\n")

    # ---- shared, unchanged ------------------------------------------------
    # THE ENCOUNTER SOURCE TRAVELS TOO. wave_programs.asm and wave_encounters.asm
    # are LEVEL-owned (Contract v2 Phase 4), so a level directory without them
    # does not assemble. The proof's stage is four copies of level 1's terrain and
    # it keeps level 1's encounters unchanged -- only the no-spawn row is rescaled
    # above, and every authored trigger row stays far below it.
    for f in ("stage_charset.asm", "stage_enemies.asm",
              "wave_programs.asm", "wave_encounters.asm"):
        shutil.copyfile(SRC / f, out / f)

    print(f"{out}: {rows} metatile rows ({rows*10} map bytes), "
          f"{rows*4} logical rows, stage end {stage_end}, "
          f"no-spawn row {no_spawn}, turret rows {[r for r,_ in pairs]}")


main()
