#!/usr/bin/env python3
"""Split a level's stage_map.asm into defs and rows, padding rows to capacity.

    python3 tools/pad_stage_map.py src/level2 build

WHAT THIS REPLACED, AND WHY. The Makefile used to carve the two halves out with
two `awk` range matches. That was exactly right while every level was 200
metatile rows long, and stopped being right the moment a second level was
authored at 138: the engine's scroller derives its wrap, its start row and its
completion boundary from ONE assembly-time stage height, so a shorter level's
map has to be padded up to that capacity before it is packaged.

THE PADDING GOES AT THE LOW INDICES. stageTopRow starts high and walks DOWN to
zero, so metatile row 199 is what the player sees first and row 0 is where the
stage ends. Padding the low end puts the filler AFTER the authored content, as a
run-in to the boss arena.

AND IT COSTS THE TRIGGERS NOTHING, which is the reason this is safe rather than
merely convenient. An authored row m moves to index m + pad, and worldProgress is
counted DOWN from the top of the array, so the two shifts cancel: authored
trigger row W still fires on authored row W. Padding the high end would have
delayed the whole level by the pad and forced every trigger to be rewritten.

THE FILLER IS A COPY OF AUTHORED ROW 0, not blank. Row 0 is the last row the
player scrolls through, so repeating it continues whatever terrain the level
ends with instead of dropping the player into an empty band before the boss.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# src/levelpkg.asm LEVELPKG_STAGE_ROWS. Read from there rather than repeated
# here, so the two cannot drift.
CAPACITY_CONST = "LEVELPKG_STAGE_ROWS"
ROW_BYTES = 10                      # METATILES_PER_ROW


def capacity(root: Path) -> int:
    src = (root / "src" / "levelpkg.asm").read_text()
    m = re.search(rf"^\.const\s+{CAPACITY_CONST}\s*=\s*(\d+)", src, re.M)
    if not m:
        raise SystemExit(f"{CAPACITY_CONST} not found in src/levelpkg.asm")
    return int(m.group(1))


def authored_rows(cfg: Path) -> int:
    m = re.search(r"^\.const\s+STAGE_METATILE_ROWS\s*=\s*(\d+)",
                  cfg.read_text(), re.M)
    if not m:
        raise SystemExit(f"STAGE_METATILE_ROWS not found in {cfg}")
    return int(m.group(1))


def carve(text: str, start: str, end: str, what: str) -> list[str]:
    """The lines from `start` to `end` inclusive, as the awk ranges did."""
    out, taking = [], False
    for line in text.splitlines():
        if line.startswith(start):
            taking = True
        if taking:
            out.append(line)
        if taking and line.startswith(end):
            return out
    raise SystemExit(f"{what}: no {start!r}..{end!r} range found")


def row_values(lines: list[str]) -> list[list[int]]:
    """Every .byte row in the carved block, as lists of ints."""
    rows = []
    for line in lines:
        body = line.split("//", 1)[0]
        m = re.search(r"\.byte\s+(.*)", body)
        if not m:
            continue
        vals = [int(v, 0) for v in re.findall(r"\$?[0-9a-fA-F]+", m.group(1))
                if v.strip()]
        if vals:
            rows.append(vals)
    return rows


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit("usage: pad_stage_map.py <level dir> <out dir>")
    level_dir, out_dir = Path(sys.argv[1]), Path(sys.argv[2])
    root = Path(__file__).resolve().parent.parent
    cap = capacity(root)
    authored = authored_rows(level_dir / "stage_config.asm")

    if authored > cap:
        raise SystemExit(
            f"{level_dir.name} authors {authored} metatile rows but the engine's "
            f"capacity is {cap}. Raise {CAPACITY_CONST} (and the engine's stage "
            f"height with it) or shorten the level.")

    src = (level_dir / "stage_map.asm").read_text()
    defs = carve(src, "metatileDefs:", "METATILE_DEFS_END:", "metatile defs")
    rows = carve(src, "stageMetatileRows:", "STAGE_METATILE_ROWS_END:", "map rows")

    values = row_values(rows)
    if len(values) != authored:
        raise SystemExit(
            f"{level_dir.name}: stage_config says {authored} metatile rows but "
            f"stage_map.asm emits {len(values)}")
    for i, v in enumerate(values):
        if len(v) != ROW_BYTES:
            raise SystemExit(f"{level_dir.name}: map row {i} has {len(v)} "
                             f"bytes, expected {ROW_BYTES}")

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "stage_map_defs.asm").write_text("\n".join(defs) + "\n")

    pad = cap - authored
    filler = values[0]
    body = [
        "// GENERATED by tools/pad_stage_map.py -- do not edit.",
        f"// {level_dir.name}: {authored} authored metatile rows, padded to the",
        f"// engine's capacity of {cap} with {pad} copies of authored row 0.",
        "// The padding is at the LOW indices, which the stage reaches LAST; see",
        "// the tool's docstring for why that leaves every trigger row correct.",
        "stageMetatileRows:",
    ]
    for _ in range(pad):
        body.append("    .byte " + ", ".join(str(v) for v in filler)
                    + "        // pad")
    for i, v in enumerate(values):
        body.append("    .byte " + ", ".join(str(v) for v in v)
                    + f"        // authored row {i}")
    body.append("STAGE_METATILE_ROWS_END:")
    (out_dir / "stage_map_rows.asm").write_text("\n".join(body) + "\n")

    print(f"  stage map: {level_dir.name} {authored} rows + {pad} pad "
          f"= {cap} ({cap * ROW_BYTES} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
