// ===========================================================================
// terrain.asm — the real level-1 terrain: charset, metatile decode, colour
// ===========================================================================
// MAIN THREAD ONLY. The raster executor never reads one byte of this file, and
// this file never writes a VIC register. It produces CHARACTER CODES into the
// back page, and the scroller publishes that page exactly as it always has.
//
//     scrollTick     decides which back-page row is due
//     regenTick      calls renderRow ROWS_PER_TICK times a frame
//     renderTerrainRow  <- here: one stage row -> 40 screen codes
//     scrollPublish  the frame record, unchanged
//     exFrame        adopts $d018 / the page, unchanged
//
// THE LEVEL PACKAGE, in src/level1/, is auto-generated by the level editor and
// is DATA, not engine code. Every constant below comes from
// stage_config.asm -- the engine derives from the package rather than
// restating it, so a regenerated level cannot silently disagree with the code
// that walks it.
//
// THE MAP FORMAT
//   METATILE_W = METATILE_H = 4, METATILES_PER_ROW = 10  (10 * 4 = 40 columns)
//   metatileDefs        STAGE_METATILE_COUNT * 16 bytes, ROW-MAJOR:
//                       def[subRow * 4 + col] is a character code
//   stageMetatileRows   STAGE_METATILE_ROWS * 10 metatile IDs
//   glyph codes         96 .. 96 + TERRAIN_GLYPH_COUNT - 1
//
// THE COLOURS, all authored by the level package:
//   TERRAIN_BACKGROUND_COLOUR -> $d021 (bit pair 00) -- the VALUE is the
//                                level's, but the REGISTER is written by the
//                                renderer's aperture splits, not terrainInit.
//                                See APERTURE_D021 in src/main.asm.
//   TERRAIN_MC_COLOUR_1       -> $d022 (bit pair 01)
//   TERRAIN_MC_COLOUR_2       -> $d023 (bit pair 10)
//   TERRAIN_CHARACTER_COLOUR  -> colour RAM low 3 bits (bit pair 11)
//   TERRAIN_COLOUR_RAM        = 8 | TERRAIN_CHARACTER_COLOUR, so every cell is
//                                MULTICOLOUR
//
// COLOUR RAM IS WRITTEN ONCE, AT INIT, AND NEVER AGAIN. Terrain colour is
// level-global, and colour RAM is not double buffered -- there is one $d800 for
// both screen pages -- so a uniform colour is the only thing that could be
// correct without a second copy the VIC cannot give us.
//
// That is the single biggest reason real terrain is affordable here:
// regenerating a row writes 40 bytes of screen RAM and ZERO bytes of colour
// RAM. A per-cell colour table would double the row cost AND require a
// colour-RAM double buffer that does not exist.
// ===========================================================================

// src/level1/stage_config.asm is imported at the top of src/main.asm, before
// every module, because the renderer's APERTURE_D021 derives from
// TERRAIN_BACKGROUND_COLOUR and renderer.asm is parsed first. The package's own
// header asks to be imported that early. Every constant it authors is in scope
// here.

.const METATILE_W        = 4
.const METATILE_H        = LEVELPKG_METATILE_H   // the shared contract
.const METATILES_PER_ROW = 10

.if (METATILES_PER_ROW * METATILE_W != SCREEN_COLS) {
    .error "METATILES_PER_ROW * METATILE_W must tile the screen exactly"
}

// THE ENGINE'S STAGE HEIGHT IS THE CONTRACT'S, NOT THE RESIDENT LEVEL'S.
//
// It used to be STAGE_METATILE_ROWS * METATILE_H -- the authored height of
// whatever level the engine happened to be BUILT against -- which made the
// scroller's wrap, its start row and its completion boundary depend on
// LEVELDIR. Building with LEVELDIR=src/level2 produced a 552-row engine; the
// campaign builds with level 1 and gets an 800-row one. Two different games
// from one source tree, decided by a Makefile variable.
//
// It is STILL COMPILE-TIME, and deliberately so -- runtime-variable stage
// height is the agreed follow-up and is not attempted here. What changed is
// WHERE the number comes from: LEVELPKG_STAGE_ROWS, the shared contract that
// also tells tools/pad_stage_map.py what to pad every package up to. One
// number, one place, and no LEVELDIR in it.
.const TERRAIN_STAGE_ROWS = LEVELPKG_STAGE_ROWS * METATILE_H

// --- the glyph namespace ----------------------------------------------------
// The metatile defs are full of literal character codes in this namespace, so
// the base must match what the level editor emitted: rebasing the codes would
// mean transforming the whole map through something nobody can check by eye.
.const TERRAIN_GLYPH_BASE = 96

// THE CEILING, NOT THIS LEVEL'S COUNT. The glyphs arrive in the level package
// now, so the engine reserves a window big enough for any level it will load
// and the actual count is a runtime byte (trnGlyphCount). TERRAIN_GLYPH_COUNT
// still exists -- the PACKAGE build uses it to size what it emits -- but the
// engine must not assume the resident level's value, because the resident level
// changes.
.const TERRAIN_GLYPH_MAX = 128
.if (TERRAIN_GLYPH_BASE + TERRAIN_GLYPH_MAX > 256) {
    .error "the terrain glyph namespace runs past character code 255"
}

// ===========================================================================
// The charset window, and why it is at $0800.
// ===========================================================================
// A CHARSET MUST START ON A 2 KB BOUNDARY INSIDE VIC BANK 0, and the bank's
// other slots are all committed: $0000 is screen A, $1000 and $1800 are the
// character-ROM shadow (the VIC cannot see RAM there at all, which is why this
// engine puts CPU code in them), $2800 is screen B, $3000 holds the HUD,
// player, enemy and projectile bitmaps, and $3800 is the blank aperture
// charset. $0800 is the one that fits.
//
// THE UNUSED PARTS OF THE WINDOW ARE BLANK BY CONSTRUCTION, not by a clearing
// loop. KickAssembler emits one contiguous PRG and zero-fills every byte no
// segment wrote, so codes 0..95 ($0800..$0aff) and 168..255 ($0d40..$0fff)
// load as zeros and render as $d021. The only non-zero bytes in the window
// that are not glyphs are the twelve-byte BASIC stub at $0801, which is
// character codes 0 and 1; terrainInit zeroes them, so a stray code cannot
// draw the SYS line as a glyph.
.const TERRAIN_CHARSET   = $0800
.const TERRAIN_GLYPHS    = TERRAIN_CHARSET + TERRAIN_GLYPH_BASE * 8

.if ((TERRAIN_CHARSET & $07ff) != 0) {
    .error "the terrain charset must start on a 2 KB boundary"
}
.if (TERRAIN_CHARSET + $800 > $4000) {
    .error "the terrain charset must lie inside VIC bank 0"
}
.if (TERRAIN_CHARSET == BLANK_CHARSET) {
    .error "the terrain charset and the blank aperture charset must differ"
}

// THE GLYPHS ARE NO LONGER ASSEMBLED HERE. They used to be -- `#import
// "stage_charset.asm"` at this address -- which made the resident level's
// artwork part of the ENGINE binary and therefore unchangeable at run time. A
// campaign loads a second level whose charset is different (128 glyphs against
// level 1's 80, in different colours), so the bitmaps moved into the level
// package and terrainApplyPackage copies them into this window at level init.
//
// The window is now plain RAM the PRG zero-fills, which is the correct resting
// state: a glyph code nothing has loaded renders as $d021 rather than as a
// fragment of the previous level.
.const TERRAIN_GLYPHS_END = TERRAIN_GLYPHS + TERRAIN_GLYPH_MAX * 8

.if (TERRAIN_GLYPHS_END > TERRAIN_CHARSET + $800) {
    .error "the terrain glyph window runs past the end of the charset"
}
.if (TERRAIN_GLYPHS < $0810) {
    .error "the terrain glyph window would overwrite the BASIC stub"
}
// The terrain window is checked against the turret glyphs in src/turrets.asm,
// which is parsed after this file and is where TURRET_GLYPHS is declared.

// ===========================================================================
// The authored map. IT IS NOT IN THIS BINARY AT ALL.
// ===========================================================================
// The map and the metatile definitions live in the LEVEL PACKAGE -- a second
// file, loaded from disk into RAM under the banked-out KERNAL at boot. See
// src/levelpkg.asm for the contract, src/level_package.asm for the bytes and
// src/levelload.asm for the load.
//
// WHY IT MOVED. A 440-metatile-row stage is 4,400 bytes of rows, and the whole
// machine holds exactly one free run that large: $e000-$fff9, 8,186 bytes of
// RAM underneath the KERNAL ROM. The next largest is 1,478. The old $5800
// segment could hold 150 metatile rows at this level's definition count and no
// rearrangement below $d000 gets near 4,400 without moving three working
// modules. reports/definitive-440-row-memory-audit.md is the evidence.
//
// NOTHING ELSE IN THIS FILE CHANGED, and that is the point. The row lookup
// already builds a full sixteen-bit pointer -- trSrc = stageMetatileRows +
// row*10, dereferenced `lda (trSrc),y` -- so the map has always been
// position-independent and relocating it costs not one cycle. The defs are read
// once by trInit and transposed into trTiles; after that they are cold.
//
// THESE ARE LABELS, NOT DATA. The engine declares where the package puts things
// and reads them; the package emits there. The two builds share no symbols, only
// the addresses in src/levelpkg.asm, which is why the size guards that used to
// live here now live beside the bytes in src/level_package.asm -- this build
// cannot measure data it does not contain.
.label metatileDefs      = LEVELPKG_DEFS
.label stageMetatileRows = LEVELPKG_MAP

// What this build CAN still check is that the level it was compiled against
// fits the region the package was compiled against. Both read the same
// stage_config.asm, so a level too tall for its budget fails here as well as
// there, and it fails whichever of the two is assembled first.
.if (LEVELPKG_STAGE_ROWS * METATILES_PER_ROW > LEVELPKG_MAP_MAX) {
    .error "the stage map has outgrown the level package's map budget"
}
.if (STAGE_METATILE_COUNT * 16 > LEVELPKG_DEFS_MAX) {
    .error "the metatile definitions have outgrown the level package's budget"
}

// ===========================================================================
// THE SUB-ROW TABLE, and why the authored layout is not decoded directly
// ===========================================================================
// metatileDefs is row-major 4x4: the four codes a stage row needs from tile
// `id` are at metatileDefs + id*16 + subRow, four consecutive bytes. Decoding
// that shape directly costs a 16-bit pointer per metatile -- id*16 is up to
// 544, so it does not fit a byte -- and then the def read and the screen write
// want DIFFERENT index registers, because the def index runs 0..3 while the
// screen index runs col..col+3. Biasing one pointer to make a single Y serve
// both costs another fourteen cycles a metatile. Measured on paper at roughly
// 1,040 cycles a row, which would have made the real terrain 30% dearer than
// the placeholder it replaces.
//
// So the defs are TRANSPOSED ONCE, at init, into four sub-row tables:
//
//     trTiles + subRow*256 + id*4 + i   ==   metatileDefs[id*16 + subRow*4 + i]
//
// id*4 is at most 135 for 34 metatiles, so the def read becomes `lda abs,X`
// with a one-byte index and the screen write stays `sta (scrPtr),Y`. The two
// indices advance independently and no pointer arithmetic survives in the
// inner loop at all.
//
// The tables are 256 bytes apart ON PURPOSE. Only the HIGH byte of the four
// read instructions then depends on which sub-row is being drawn, so selecting
// a sub-row is four byte stores at the top of a row rather than eight.
//
// THE AUTHORED DATA IS NOT REWRITTEN. src/level1/stage_map.asm stays byte-for-
// byte as the level editor emitted it; the transpose happens at run time, from
// it, so a regenerated map drops straight in.
// ===========================================================================
.const TR_TILE_STRIDE = 256

* = $6400 "terrain tile tables"
trTiles: .fill 4 * TR_TILE_STRIDE, 0

.if ((trTiles & $ff) != 0) {
    .error "the sub-row tables must be page aligned: the row selector patches high bytes only"
}
.if (LEVELPKG_DEFS_MAX / 16 * METATILE_W != TR_TILE_STRIDE) {
    .error "the transpose walks the whole definition reservation: it must fill the stride exactly"
}

// ===========================================================================
// State. MAIN THREAD ONLY.
// ===========================================================================
// It sits beside the terrain code rather than in the $c000 state page, which
// is full. The rule the state must obey is "main thread only, outside VIC bank
// 0", and $6c00 satisfies both.
//
// trSrc IS IN ZERO PAGE, AND IT HAS TO BE.
//
// It is dereferenced as `lda (trSrc),y`, and the 6502 has no such addressing
// mode for an absolute address -- indirect-indexed exists only for zero page.
// KickAssembler does NOT refuse the instruction when the operand is outside
// zero page: it silently assembles `lda ($0a),y` from the LOW BYTE of a $6c0a
// pointer, and the code then reads through whatever that zero-page location
// happens to hold. The guard below turns that into a build error.
.const trSrc = $f7                      // 16-bit, $f7/$f8

.if (trSrc > $fe) {
    .error "trSrc must be a zero-page pointer: (trSrc),y has no absolute form"
}
.if (trSrc == scrPtr) {
    .error "trSrc collides with another zero-page pointer"
}

* = $6c00 "terrain state"

trIds:     .fill METATILES_PER_ROW, 0   // the cached metatile row's ten IDs
trRowBase: .byte 0, 0                   // metatileRow * METATILES_PER_ROW
trCachedLo: .byte 0                     // which metatile row trIds holds...
trCachedHi: .byte 0                     // ...$ff in the high byte = nothing

// --- THE RESIDENT LEVEL'S RENDER IDENTITY, copied out of its package --------
// These were compiled-in constants until the campaign made the resident level
// changeable. trnBgColour is read by the renderer's two aperture splits every
// frame; the other two are read only at level init.
trnBgColour:   .byte 0                  // $d021, the playfield background
trnCramValue:  .byte 0                  // the colour-RAM fill, bit 3 already set
trnGlyphCount: .byte 0                  // how many glyphs this level authored
terrainStateEnd:

.if (terrainStateEnd > $6c80) {
    .error "the terrain state has outgrown its $6c00 segment"
}

// terrainApplyPackage lives in its own run because the terrain code segment
// ends at $6980, where src/vicbank.asm begins, and adding the routine to it
// overlapped the two. $6b05-$6bff is the gap the vic bank leaves below the
// terrain state at $6c00.
* = $6b10 "terrain package adopt"



// ---------------------------------------------------------------------------
// terrainApplyPackage — adopt the resident package's charset and palette.
//
// CALLED BEFORE terrainInit, AND AGAIN ON EVERY LEVEL LOAD. Everything it reads
// lives above $e000, so it requires the KERNAL banked OUT ($01 = $35); every
// caller is already in that state.
//
// THE GLYPH WINDOW IS CLEARED FIRST, all TERRAIN_GLYPH_MAX of it, not just the
// part the new level fills. Level 1 authors 80 glyphs and level 2 authors 128:
// loading level 1 after level 2 without the clear would leave level 2's glyphs
// 80..127 sitting in the window, and any metatile that referenced a code that
// high would draw the previous level's artwork.
// ---------------------------------------------------------------------------
terrainApplyPackage:
    // ---- 1. the glyphs: the WHOLE window, unconditionally -----------------
    // ALL 1,024 BYTES, not trnGlyphCount * 8, and that is the stronger contract
    // rather than the lazier one. The package reserves the full window at
    // LEVELPKG_CHARS and KickAssembler zero-fills whatever the level did not
    // author, so a level with 80 glyphs supplies 80 glyphs and 384 zero bytes.
    // Copying the lot therefore CLEARS the previous level's high glyphs as a
    // side effect of loading the new one's -- no separate blanking pass, and no
    // way for a stale glyph to survive a level change. A count-driven copy would
    // have left level 2's glyphs 80..127 in the window when level 1 loaded after
    // it, and any metatile naming a code that high would have drawn them.
    ldx #0
!copy:
    .for (var p = 0; p < TERRAIN_GLYPH_MAX * 8 / 256; p++) {
        lda LEVELPKG_CHARS + p * 256,x
        sta TERRAIN_GLYPHS + p * 256,x
    }
    inx
    bne !copy-

    lda LEVELPKG_GLYPHN                 // recorded for diagnostics and tests;
    sta trnGlyphCount                   // the copy above does not depend on it

    // ---- 2. the palette ---------------------------------------------------
    lda LEVELPKG_PAL + 0
    sta trnBgColour                     // $d021 is the RENDERER's to write, at
                                        // rasters 55 and 248; see the note below
    lda LEVELPKG_PAL + 1
    sta $d022                           // bit pair 01
    lda LEVELPKG_PAL + 2
    sta $d023                           // bit pair 10
    lda LEVELPKG_PAL + 3
    sta trnCramValue
    rts


* = $6800 "terrain code"

// ---------------------------------------------------------------------------
// terrainInit — colour RAM, the VIC colour registers, multicolour mode, and
// the transposed sub-row tables. Called once from entry, before the display is
// enabled.
//
// Everything here is set ONCE. There is no per-frame terrain VIC work of any
// kind, which is what keeps terrain off the scroller's frame budget.
// ---------------------------------------------------------------------------
terrainInit:
    // ---- colour RAM: one value, the whole screen -------------------------
    // The fill value is the package's: bit 3 selects MULTICOLOUR for the cell
    // and the low three bits are its bit-pair-11 colour. Both pages share this
    // one colour RAM, which a level-global colour makes correct for free.
    lda trnCramValue
    ldx #0
!fill:
    sta COLOUR_RAM + $000,x
    sta COLOUR_RAM + $100,x
    sta COLOUR_RAM + $200,x
    sta COLOUR_RAM + $2e8,x
    inx
    bne !fill-

    // ---- the two shared multicolour registers terrain still owns ---------
    //
    // $D021 IS NOT WRITTEN HERE, and must not be. The open top and bottom
    // border has no colour of its own while the vertical flip-flop is held
    // open: it shows bit pair 00 -- $d021 -- exactly like the playfield, so
    // setting it once here would paint the whole border in the level's colour.
    //
    // The playfield's background is still THIS LEVEL'S value and still comes
    // from this file's constant; the renderer's two aperture splits read it as
    // APERTURE_D021 and write the register at rasters 55 and 248. Terrain owns
    // the colour, the renderer owns the register -- the same division
    // src/hud.asm already lives by.
    // THE MULTICOLOUR PAIR IS terrainApplyPackage's, AND WRITING IT HERE WAS
    // THE LEVEL 2 CORRUPTION. These two stores used to load the compile-time
    // TERRAIN_MC_COLOUR_1/2 -- the colours of whatever level the ENGINE was
    // built against. terrainApplyPackage sets $d022/$d023 from the loaded
    // package and runs FIRST, so on a runtime level change these overwrote the
    // new level's palette with level 1's: level 2 asks for $d022 = 0, got 15,
    // and every black chip body on its PCB terrain came out light grey.
    //
    // Nothing is written here now. terrainApplyPackage owns the pair, on the
    // boot path and the level-change path alike.

    // ---- multicolour TEXT mode -------------------------------------------
    // Read-modify-write on purpose: $d016 also carries CSEL and XSCROLL, and
    // this engine scrolls VERTICALLY through $d011, so whatever is in XSCROLL
    // must survive.
    lda $d016
    ora #%00010000
    sta $d016

    // ---- the BASIC stub, which is character codes 0 and 1 ----------------
    // The rest of the charset window is zero-filled by the PRG, but these
    // twelve bytes are not. Zeroing them makes every code outside the terrain
    // namespace render as $d021 rather than as fragments of the SYS line.
    lda #0
    ldx #0
!stub:
    sta TERRAIN_CHARSET,x
    inx
    bne !stub-

    // The metatile-ID cache starts empty. $ff is not a reachable high byte for
    // a metatile row -- the tallest legal stage is far short of 65280 rows --
    // so it cannot collide with a real one.
    lda #$ff
    sta trCachedHi

    // ---- transpose the defs into the four sub-row tables ------------------
    //     trTiles[s*256 + id*4 + i]  =  metatileDefs[id*16 + s*4 + i]
    //
    // Written as sixteen unrolled store pairs rather than a nested loop. The
    // source index walks a metatile's sixteen bytes in order, so Y only ever
    // increments; the destination is the one that jumps, and every jump is a
    // CONSTANT displacement the assembler folds into the operand. X holds
    // id*4 throughout, which is at most 132 for 34 metatiles, so no store can
    // cross out of its own 256-byte table.
    //
    // The first version of this used a single self-modified `sta $ffff` with
    // the operand patched per sub-row. It was shorter and it was wrong -- the
    // source pointer overran the def table by 280 bytes and the tables filled
    // with whatever followed in memory. Sixteen explicit stores cost about
    // 6,500 cycles ONCE, at init, and can be checked by reading them.
    lda #<metatileDefs
    sta trSrc
    lda #>metatileDefs
    sta trSrc + 1
    ldx #0                              // X = id * METATILE_W
!tile:
    ldy #0
    .for (var s = 0; s < METATILE_H; s++) {
        .for (var i = 0; i < METATILE_W; i++) {
            lda (trSrc),y
            sta trTiles + s * TR_TILE_STRIDE + i, x
            iny
        }
    }
    lda trSrc
    clc
    adc #METATILE_W * METATILE_H        // sixteen bytes to the next definition
    sta trSrc
    bcc !noCarry+
    inc trSrc + 1
!noCarry:
    txa
    clc
    adc #METATILE_W
    tax
    // THE WHOLE RESERVATION, NOT THIS BUILD'S METATILE COUNT.
    //
    // It was `cpx #STAGE_METATILE_COUNT * METATILE_W` -- the count of whatever
    // level the ENGINE was compiled against -- and that was the second half of
    // the level 2 corruption. Level 1 authors 41 definitions and level 2 authors
    // 49, so an engine built for level 1 transposed only 41 of them: every map
    // cell naming metatile 41..48 read sub-row entries that had never been
    // written, and level 2's terrain lost exactly the detail those tiles carry.
    //
    // Transposing the full LEVELPKG_DEFS reservation fixes it without a count.
    // The package reserves 64 definitions and zero-fills the ones the level did
    // not author, so the pass both loads this level's tiles AND clears the
    // previous level's out of the tail -- the same argument terrainApplyPackage
    // makes for copying the whole charset window. TR_TILE_STRIDE is 256 and
    // 64 * METATILE_W is 256, so the transpose exactly fills the tables.
    cpx #0                              // wrapped past 255: all 64 done
    bne !tile-
    rts

trTilePageLo:
    .byte >trTiles, (>trTiles) + 1, (>trTiles) + 2, (>trTiles) + 3

// ---------------------------------------------------------------------------
// renderTerrainRow — one stage character row into the back page.
//
// Entry:  scrPtr       -> the back page's row, set up by renderRow
//         rrStageLo/Hi =  the stage character row, already reduced mod
//                         STAGE_ROWS by the caller
// Exit:   40 character codes written. No colour RAM. No VIC register.
//
// The decode, against the transposed tables:
//
//     subRow      = stageRow mod METATILE_H
//     metatileRow = stageRow / METATILE_H
//     rowBase     = metatileRow * METATILES_PER_ROW
//     id          = stageMetatileRows[rowBase + col]
//     code        = trTiles[subRow*256 + id*4 + i]          i = 0..3
//
// The ten IDs are read into trIds first so the inner loop touches one table
// instead of two.
// ---------------------------------------------------------------------------
renderTerrainRow:
    // ---- select the sub-row table: four high bytes ------------------------
    lda rrStageLo
    and #METATILE_H - 1
    tax
    lda trTilePageLo,x
    sta trRead0 + 2
    sta trRead1 + 2
    sta trRead2 + 2
    sta trRead3 + 2

    // ---- metatileRow = stageRow / METATILE_H, sixteen bits ----------------
    lda rrStageHi
    lsr
    sta trRowBase + 1
    lda rrStageLo
    ror
    lsr trRowBase + 1
    ror
    sta trRowBase                       // trRowBase(16) = metatileRow

    // ---- is this metatile row already in trIds? ---------------------------
    // A metatile is four character rows tall, so regenerating a page walks
    // FOUR consecutive stage rows out of every metatile row, and all four want
    // the same ten IDs. Reading them again costs a 16-bit multiply, a pointer
    // build and ten indirect loads -- about 200 cycles -- for an answer that
    // has not changed three times out of four.
    //
    // The cache is keyed on the metatile row alone and is therefore valid
    // across a page flip as well: which page the row is being written into
    // does not change what the map says is there.
    lda trRowBase
    cmp trCachedLo
    bne !reload+
    lda trRowBase + 1
    cmp trCachedHi
    beq trHaveIds
!reload:
    lda trRowBase
    sta trCachedLo
    lda trRowBase + 1
    sta trCachedHi

    // ---- rowBase = metatileRow * 10 = (m * 8) + (m * 2) -------------------
    // A is reloaded rather than assumed: this used to run straight on from the
    // `sta trRowBase` above with the low byte still in A, and the cache check
    // inserted before it ends by loading the HIGH byte. Shifting that instead
    // silently produced the right answer for three rows in four -- the ones the
    // cache served -- which is exactly the shape of bug that survives a test
    // that only walks consecutive rows.
    lda trRowBase
    asl
    sta trSrc
    lda trRowBase + 1
    rol
    sta trSrc + 1                       // trSrc(16) = m * 2
    lda trSrc
    asl
    sta trRowBase
    lda trSrc + 1
    rol
    sta trRowBase + 1
    asl trRowBase
    rol trRowBase + 1                   // trRowBase(16) = m * 8
    lda trRowBase
    clc
    adc trSrc
    sta trRowBase
    lda trRowBase + 1
    adc trSrc + 1
    sta trRowBase + 1                   // + m*2            -> m * 10

    // ---- trSrc -> stageMetatileRows[rowBase] ------------------------------
    lda trRowBase
    clc
    adc #<stageMetatileRows
    sta trSrc
    lda trRowBase + 1
    adc #>stageMetatileRows
    sta trSrc + 1

    ldy #METATILES_PER_ROW - 1
!ids:
    lda (trSrc),y
    sta trIds,y
    dey
    bpl !ids-

trHaveIds:
    // ---- ten metatiles, four characters each ------------------------------
    // Y walks the screen column 0,4,...,36 and is the loop counter: it reaches
    // SCREEN_COLS exactly when the tenth metatile is done. X is id*4, the
    // sub-row table index, and the two advance independently -- which is the
    // whole point of the transpose.
    ldy #0
!col:
    tya
    lsr
    lsr
    tax
    lda trIds,x
    asl
    asl
    tax                                 // X = id * METATILE_W
trRead0:
    lda trTiles,x                       // high byte patched per row
    sta (scrPtr),y
    inx
    iny
trRead1:
    lda trTiles,x
    sta (scrPtr),y
    inx
    iny
trRead2:
    lda trTiles,x
    sta (scrPtr),y
    inx
    iny
trRead3:
    lda trTiles,x
    sta (scrPtr),y
    iny
    cpy #SCREEN_COLS
    bne !col-
    rts

.if (* > $6c00) {
    .error "the terrain code has outgrown its $6800 segment"
}
