// ===========================================================================
// terrain.asm — the real level-1 terrain: charset, metatile decode, colour
// ===========================================================================
// MAIN THREAD ONLY. The raster executor never reads one byte of this file, and
// this file never writes a VIC register. It produces CHARACTER CODES into the
// back page, and the scroller publishes that page exactly as it always has.
//
//     scrollTick     decides which back-page row is due
//     regenTick      calls renderRow ROWS_PER_TICK times a frame
//     renderTerrainRow  <- here: one stage row -> 40 screen codes
//     scrollPublish  the frame record, unchanged
//     exFrame        adopts $d018 / the page, unchanged
//
// ---------------------------------------------------------------------------
// WHAT CAME ACROSS, AND FROM WHERE
// ---------------------------------------------------------------------------
// Read out of the c64Shooter checkout at ../shooter_test (git remote
// Sheep83/c64Shooter.git; the task's `c64Shooter` path does not exist on this
// machine and this is the same repository under a different directory name).
//
//   src/generated/level1/stage_config.asm   -> src/level1/stage_config.asm
//   src/generated/level1/stage_charset.asm  -> src/level1/stage_charset.asm
//   src/generated/level1/stage_test.asm     -> src/level1/stage_map.asm
//
// All three are copied BYTE FOR BYTE. They are auto-generated by the old
// repo's `tools/level_editor` and are the level package, not engine code --
// which is why they keep their own directory and their own names, and why the
// engine derives from them rather than restating them.
//
// The old repo's runtime decoder (decodeStageCharacterRow, main.asm:6472) is
// the behavioural reference for the ARITHMETIC below and for nothing else. Its
// page strategy, its raster scheduler and its $d018 handling are not migrated:
// this engine already has its own, and they are qualified.
//
// ---------------------------------------------------------------------------
// THE FORMAT, CONFIRMED AGAINST THE DATA RATHER THAN ASSUMED
// ---------------------------------------------------------------------------
//   METATILE_W = METATILE_H = 4, METATILES_PER_ROW = 10  (10 * 4 = 40 columns)
//   metatileDefs        STAGE_METATILE_COUNT * 16 bytes, ROW-MAJOR:
//                       def[subRow * 4 + col] is a character code
//   stageMetatileRows   STAGE_METATILE_ROWS * 10 metatile IDs
//   glyph codes         96 .. 96 + TERRAIN_GLYPH_COUNT - 1
//
// The task's brief listed some of these from memory and several were stale:
// it gave $d021/$d022/$d023 as 0/12/15, and the level actually authors
// 12/15/11; it mentioned 16 metatile IDs where level1 now has 34. Every value
// used here comes from src/level1/stage_config.asm, which is the generated
// level package and therefore authoritative.
//
//   TERRAIN_BACKGROUND_COLOUR = 12  -> $d021   (bit pair 00) -- the VALUE is
//                                      authored here, but the REGISTER is
//                                      written by the renderer's aperture
//                                      splits, not by terrainInit. See
//                                      APERTURE_D021 in src/main.asm.
//   TERRAIN_MC_COLOUR_1       = 15  -> $d022   (bit pair 01)
//   TERRAIN_MC_COLOUR_2       = 11  -> $d023   (bit pair 10)
//   TERRAIN_CHARACTER_COLOUR  = 1   -> colour RAM low 3 bits (bit pair 11)
//   TERRAIN_COLOUR_RAM        = 9   = 8 | 1, so every cell is MULTICOLOUR
//
// The one value the brief did get right is the colour-RAM byte: 9.
//
// ---------------------------------------------------------------------------
// COLOUR RAM IS WRITTEN ONCE, AT INIT, AND NEVER AGAIN
// ---------------------------------------------------------------------------
// The level's own generated header says it: "Terrain colour is level-global;
// there is intentionally no per-cell colour table." Colour RAM is also NOT
// double buffered -- there is one $d800 for both screen pages -- so a uniform
// colour is the only thing that could be correct without a second copy anyway.
//
// That is worth stating plainly because it is the single biggest reason the
// real terrain is affordable: regenerating a row writes 40 bytes of screen
// RAM and ZERO bytes of colour RAM. A per-cell colour table would have doubled
// the row cost and forced a colour-RAM double buffer the VIC cannot give us.
// ===========================================================================

// src/level1/stage_config.asm IS NOT IMPORTED HERE ANY MORE. It is imported at
// the top of src/main.asm instead, before every module, because the renderer's
// APERTURE_D021 is derived from TERRAIN_BACKGROUND_COLOUR and renderer.asm is
// parsed first. The level package's own header asks for exactly that ("imported
// very early so every level-owned constant exists before the engine constants
// /code that consume them"), so this is the package being used as designed
// rather than a workaround. Every constant it authors is still in scope here.

.const METATILE_W        = 4
.const METATILE_H        = 4
.const METATILES_PER_ROW = 10

.if (METATILES_PER_ROW * METATILE_W != SCREEN_COLS) {
    .error "METATILES_PER_ROW * METATILE_W must tile the screen exactly"
}

// The engine DERIVES the stage height from the level package. STAGE_ROWS in
// src/scroll.asm is checked against this rather than being restated, so a
// level with a different number of metatile rows cannot silently disagree with
// the scroller that walks them.
.const TERRAIN_STAGE_ROWS = STAGE_METATILE_ROWS * METATILE_H

// --- the glyph namespace ----------------------------------------------------
// Code base 96 is kept from the old game DELIBERATELY. The metatile defs are
// full of literal character codes in that namespace, so keeping the base means
// src/level1/stage_map.asm is byte-identical to the authored original instead
// of being rebased by a transform nobody can check by eye.
.const TERRAIN_GLYPH_BASE = 96
.if (TERRAIN_GLYPH_BASE + TERRAIN_GLYPH_COUNT > 256) {
    .error "the terrain glyph namespace runs past character code 255"
}

// ===========================================================================
// The charset window, and why it is at $0800.
// ===========================================================================
// EVERY 2 KB-ALIGNED CHARSET SLOT IN VIC BANK 0 WAS OCCUPIED before this
// slice. $0000 holds screen A, $1000 and $1800 are the character-ROM shadow
// (the VIC cannot see RAM there at all, which is exactly why this engine puts
// code in them), $2000 holds the diagnostic sprites and the P5 ring tables,
// $2800 holds screen B and the raster executor, $3000 holds the HUD, player
// and enemy sprite bitmaps, and $3800 is the blank aperture charset.
//
// $0800 was freed by moving the `main` segment OUT of VIC bank 0, to $5000.
// That is not a workaround, it is the pattern this engine already follows:
// the player ($4000), the scroller ($4200), the weapon ($4600), the object
// pool ($4800), the enemy ($4900) and collision ($4c00) are all main-thread
// code living outside bank 0 precisely so bank 0 can hold what the VIC must
// see. main.asm is main-thread code too -- entry, mainLoop, gameFrame,
// gameInit and the diagnostic HUD, with no interrupt handler anywhere in it --
// so it belonged out there already.
//
// THE UNUSED PARTS OF THE WINDOW ARE BLANK BY CONSTRUCTION, not by a clearing
// loop. KickAssembler emits one contiguous PRG and zero-fills every byte no
// segment wrote, so codes 0..95 ($0800..$0aff) and 168..255 ($0d40..$0fff)
// load as zeros and render as $d021. The only non-zero bytes in the window
// that are not glyphs are the twelve-byte BASIC stub at $0801, which is
// character codes 0 and 1; terrainInit zeroes them, so a stray code cannot
// draw the SYS line as a glyph.
.const TERRAIN_CHARSET   = $0800
.const TERRAIN_GLYPHS    = TERRAIN_CHARSET + TERRAIN_GLYPH_BASE * 8

.if ((TERRAIN_CHARSET & $07ff) != 0) {
    .error "the terrain charset must start on a 2 KB boundary"
}
.if (TERRAIN_CHARSET + $800 > $4000) {
    .error "the terrain charset must lie inside VIC bank 0"
}
.if (TERRAIN_CHARSET == BLANK_CHARSET) {
    .error "the terrain charset and the blank aperture charset must differ"
}

* = TERRAIN_GLYPHS "terrain glyphs"
#import "level1/stage_charset.asm"      // declares terrainGlyphs/terrainGlyphsEnd
                                        // and self-checks its own byte count

.if (terrainGlyphsEnd > TERRAIN_CHARSET + $800) {
    .error "the terrain glyphs run past the end of their charset window"
}
.if (TERRAIN_GLYPHS < $0810) {
    .error "the terrain glyphs would overwrite the BASIC stub"
}

// ===========================================================================
// The authored map. CPU-ONLY DATA, so it lives OUTSIDE VIC bank 0.
// ===========================================================================
// 34 defs * 16 = 544 bytes, plus 105 rows * 10 = 1050 bytes. The VIC never
// reads any of it -- only the character codes this file DERIVES from it ever
// reach a screen page -- so putting it in bank 0 would spend the scarcest
// memory in the machine on data that does not need to be there.
* = $5800 "terrain map data"
#import "level1/stage_map.asm"
terrainMapEnd:

.if (METATILE_DEFS_END - metatileDefs != STAGE_METATILE_COUNT * 16) {
    .error "metatileDefs size does not match STAGE_METATILE_COUNT * 16"
}
.if (STAGE_METATILE_ROWS_END - stageMetatileRows != STAGE_METATILE_ROWS * METATILES_PER_ROW) {
    .error "stageMetatileRows size does not match STAGE_METATILE_ROWS * METATILES_PER_ROW"
}
.if (terrainMapEnd > $6000) {
    .error "the terrain map data has outgrown its $5800 segment"
}

// ===========================================================================
// THE SUB-ROW TABLE, and why the authored layout is not decoded directly
// ===========================================================================
// metatileDefs is row-major 4x4: the four codes a stage row needs from tile
// `id` are at metatileDefs + id*16 + subRow, four consecutive bytes. Decoding
// that shape directly costs a 16-bit pointer per metatile -- id*16 is up to
// 544, so it does not fit a byte -- and then the def read and the screen write
// want DIFFERENT index registers, because the def index runs 0..3 while the
// screen index runs col..col+3. Biasing one pointer to make a single Y serve
// both costs another fourteen cycles a metatile. Measured on paper at roughly
// 1,040 cycles a row, which would have made the real terrain 30% dearer than
// the placeholder it replaces.
//
// So the defs are TRANSPOSED ONCE, at init, into four sub-row tables:
//
//     trTiles + subRow*256 + id*4 + i   ==   metatileDefs[id*16 + subRow*4 + i]
//
// id*4 is at most 135 for 34 metatiles, so the def read becomes `lda abs,X`
// with a one-byte index and the screen write stays `sta (scrPtr),Y`. The two
// indices advance independently and no pointer arithmetic survives in the
// inner loop at all.
//
// The tables are 256 bytes apart ON PURPOSE. Only the HIGH byte of the four
// read instructions then depends on which sub-row is being drawn, so selecting
// a sub-row is four byte stores at the top of a row rather than eight.
//
// THE AUTHORED DATA IS NOT REWRITTEN. src/level1/stage_map.asm stays byte-for-
// byte identical to the file the old repo's level editor emitted; the
// transpose happens at run time, from it, so the file on disk remains
// something a person can diff against the original.
// ===========================================================================
.const TR_TILE_STRIDE = 256

* = $6400 "terrain tile tables"
trTiles: .fill 4 * TR_TILE_STRIDE, 0

.if ((trTiles & $ff) != 0) {
    .error "the sub-row tables must be page aligned: the row selector patches high bytes only"
}
.if (STAGE_METATILE_COUNT * METATILE_W > TR_TILE_STRIDE) {
    .error "a sub-row table has outgrown its 256-byte stride"
}

// ===========================================================================
// State. MAIN THREAD ONLY.
// ===========================================================================
// NOT in the $c000 state page with the other modules', because there is no
// room left there: collision ends at $c5fd and the P3 fixture data starts at
// $c600, which leaves two bytes. The guard that was there caught this on the
// first build rather than letting it overwrite a fixture table, which is what
// those guards are for. Sitting beside the terrain code is just as correct --
// the rule the state has to obey is "main thread only, outside VIC bank 0",
// and $6c00 satisfies both.
// trSrc IS IN ZERO PAGE, AND IT HAS TO BE.
//
// It is dereferenced as `lda (trSrc),y`, and the 6502 has no such addressing
// mode for an absolute address -- indirect-indexed exists only for zero page.
// KickAssembler does not refuse the instruction when the operand is outside
// zero page: it silently assembles `lda ($0a),y` from the LOW BYTE of a $6c0a
// pointer, and the code then reads through whatever zero page happens to hold.
// That cost an hour here. The transposed tables filled with the bytes of
// collisionInit, because $0a/$0b pointed at $4c00.
//
// The guard below is the thing that should have existed first. $fb and $fd are
// already taken by the fixture loader and the screen-row pointer respectively.
.const trSrc = $f7                      // 16-bit, $f7/$f8

.if (trSrc > $fe) {
    .error "trSrc must be a zero-page pointer: (trSrc),y has no absolute form"
}
.if (trSrc == scrPtr) {
    .error "trSrc collides with another zero-page pointer"
}

* = $6c00 "terrain state"

trIds:     .fill METATILES_PER_ROW, 0   // the cached metatile row's ten IDs
trRowBase: .byte 0, 0                   // metatileRow * METATILES_PER_ROW
trCachedLo: .byte 0                     // which metatile row trIds holds...
trCachedHi: .byte 0                     // ...$ff in the high byte = nothing
terrainStateEnd:

.if (terrainStateEnd > $6c80) {
    .error "the terrain state has outgrown its $6c00 segment"
}

* = $6800 "terrain code"

// ---------------------------------------------------------------------------
// terrainInit — colour RAM, the VIC colour registers, multicolour mode, and
// the transposed sub-row tables. Called once from entry, before the display is
// enabled.
//
// Everything here is set ONCE. There is no per-frame terrain VIC work of any
// kind, which is what keeps the scroller's frame budget where Slice A' left it.
// ---------------------------------------------------------------------------
terrainInit:
    // ---- colour RAM: one value, the whole screen -------------------------
    // TERRAIN_COLOUR_RAM is 9 = 8 | 1: bit 3 selects MULTICOLOUR for the cell
    // and the low three bits are its bit-pair-11 colour. Both pages share this
    // one colour RAM, which a level-global colour makes correct for free.
    lda #TERRAIN_COLOUR_RAM
    ldx #0
!fill:
    sta COLOUR_RAM + $000,x
    sta COLOUR_RAM + $100,x
    sta COLOUR_RAM + $200,x
    sta COLOUR_RAM + $2e8,x
    inx
    bne !fill-

    // ---- the two shared multicolour registers terrain still owns ---------
    //
    // $D021 IS NOT WRITTEN HERE. It used to be, and that is what turned the
    // open top and bottom border grey: the border has no colour of its own
    // while the vertical flip-flop is held open, so it shows bit pair 00 --
    // $d021 -- exactly like the playfield does.
    //
    // The playfield's background is still THIS LEVEL'S value and still comes
    // from this file's constant; the renderer's two aperture splits read it as
    // APERTURE_D021 and write the register at rasters 55 and 248. Terrain owns
    // the colour, the renderer owns the register -- the same division
    // src/hud.asm already lives by.
    lda #TERRAIN_MC_COLOUR_1
    sta $d022                           // bit pair 01
    lda #TERRAIN_MC_COLOUR_2
    sta $d023                           // bit pair 10

    // ---- multicolour TEXT mode -------------------------------------------
    // Read-modify-write on purpose: $d016 also carries CSEL and XSCROLL, and
    // this engine scrolls VERTICALLY through $d011, so whatever is in XSCROLL
    // must survive. The old game set MCM the same way and for the same reason
    // (shooter_test/src/main.asm:6341).
    lda $d016
    ora #%00010000
    sta $d016

    // ---- the BASIC stub, which is character codes 0 and 1 ----------------
    // The rest of the charset window is zero-filled by the PRG, but these
    // twelve bytes are not. Zeroing them makes every code outside the terrain
    // namespace render as $d021 rather than as fragments of the SYS line.
    lda #0
    ldx #0
!stub:
    sta TERRAIN_CHARSET,x
    inx
    bne !stub-

    // The metatile-ID cache starts empty. $ff is not a reachable high byte for
    // a metatile row -- the tallest legal stage is far short of 65280 rows --
    // so it cannot collide with a real one.
    lda #$ff
    sta trCachedHi

    // ---- transpose the defs into the four sub-row tables ------------------
    //     trTiles[s*256 + id*4 + i]  =  metatileDefs[id*16 + s*4 + i]
    //
    // Written as sixteen unrolled store pairs rather than a nested loop. The
    // source index walks a metatile's sixteen bytes in order, so Y only ever
    // increments; the destination is the one that jumps, and every jump is a
    // CONSTANT displacement the assembler folds into the operand. X holds
    // id*4 throughout, which is at most 132 for 34 metatiles, so no store can
    // cross out of its own 256-byte table.
    //
    // The first version of this used a single self-modified `sta $ffff` with
    // the operand patched per sub-row. It was shorter and it was wrong -- the
    // source pointer overran the def table by 280 bytes and the tables filled
    // with whatever followed in memory. Sixteen explicit stores cost about
    // 6,500 cycles ONCE, at init, and can be checked by reading them.
    lda #<metatileDefs
    sta trSrc
    lda #>metatileDefs
    sta trSrc + 1
    ldx #0                              // X = id * METATILE_W
!tile:
    ldy #0
    .for (var s = 0; s < METATILE_H; s++) {
        .for (var i = 0; i < METATILE_W; i++) {
            lda (trSrc),y
            sta trTiles + s * TR_TILE_STRIDE + i, x
            iny
        }
    }
    lda trSrc
    clc
    adc #METATILE_W * METATILE_H        // sixteen bytes to the next definition
    sta trSrc
    bcc !noCarry+
    inc trSrc + 1
!noCarry:
    txa
    clc
    adc #METATILE_W
    tax
    cpx #STAGE_METATILE_COUNT * METATILE_W
    bne !tile-
    rts

trTilePageLo:
    .byte >trTiles, (>trTiles) + 1, (>trTiles) + 2, (>trTiles) + 3

// ---------------------------------------------------------------------------
// renderTerrainRow — one stage character row into the back page.
//
// Entry:  scrPtr       -> the back page's row, set up by renderRow
//         rrStageLo/Hi =  the stage character row, already reduced mod
//                         STAGE_ROWS by the caller
// Exit:   40 character codes written. No colour RAM. No VIC register.
//
// The arithmetic is the old decodeStageCharacterRow's
// (shooter_test/src/main.asm:6472), restated against the transposed tables:
//
//     subRow      = stageRow mod METATILE_H
//     metatileRow = stageRow / METATILE_H
//     rowBase     = metatileRow * METATILES_PER_ROW
//     id          = stageMetatileRows[rowBase + col]
//     code        = trTiles[subRow*256 + id*4 + i]          i = 0..3
//
// The ten IDs are read into trIds first, exactly as the old decoder did, so
// the inner loop touches one table instead of two.
// ---------------------------------------------------------------------------
renderTerrainRow:
    // ---- select the sub-row table: four high bytes ------------------------
    lda rrStageLo
    and #METATILE_H - 1
    tax
    lda trTilePageLo,x
    sta trRead0 + 2
    sta trRead1 + 2
    sta trRead2 + 2
    sta trRead3 + 2

    // ---- metatileRow = stageRow / METATILE_H, sixteen bits ----------------
    lda rrStageHi
    lsr
    sta trRowBase + 1
    lda rrStageLo
    ror
    lsr trRowBase + 1
    ror
    sta trRowBase                       // trRowBase(16) = metatileRow

    // ---- is this metatile row already in trIds? ---------------------------
    // A metatile is four character rows tall, so regenerating a page walks
    // FOUR consecutive stage rows out of every metatile row, and all four want
    // the same ten IDs. Reading them again costs a 16-bit multiply, a pointer
    // build and ten indirect loads -- about 200 cycles -- for an answer that
    // has not changed three times out of four.
    //
    // The cache is keyed on the metatile row alone and is therefore valid
    // across a page flip as well: which page the row is being written into
    // does not change what the map says is there.
    lda trRowBase
    cmp trCachedLo
    bne !reload+
    lda trRowBase + 1
    cmp trCachedHi
    beq trHaveIds
!reload:
    lda trRowBase
    sta trCachedLo
    lda trRowBase + 1
    sta trCachedHi

    // ---- rowBase = metatileRow * 10 = (m * 8) + (m * 2) -------------------
    // A is reloaded rather than assumed: this used to run straight on from the
    // `sta trRowBase` above with the low byte still in A, and the cache check
    // inserted before it ends by loading the HIGH byte. Shifting that instead
    // silently produced the right answer for three rows in four -- the ones the
    // cache served -- which is exactly the shape of bug that survives a test
    // that only walks consecutive rows.
    lda trRowBase
    asl
    sta trSrc
    lda trRowBase + 1
    rol
    sta trSrc + 1                       // trSrc(16) = m * 2
    lda trSrc
    asl
    sta trRowBase
    lda trSrc + 1
    rol
    sta trRowBase + 1
    asl trRowBase
    rol trRowBase + 1                   // trRowBase(16) = m * 8
    lda trRowBase
    clc
    adc trSrc
    sta trRowBase
    lda trRowBase + 1
    adc trSrc + 1
    sta trRowBase + 1                   // + m*2            -> m * 10

    // ---- trSrc -> stageMetatileRows[rowBase] ------------------------------
    lda trRowBase
    clc
    adc #<stageMetatileRows
    sta trSrc
    lda trRowBase + 1
    adc #>stageMetatileRows
    sta trSrc + 1

    ldy #METATILES_PER_ROW - 1
!ids:
    lda (trSrc),y
    sta trIds,y
    dey
    bpl !ids-

trHaveIds:
    // ---- ten metatiles, four characters each ------------------------------
    // Y walks the screen column 0,4,...,36 and is the loop counter: it reaches
    // SCREEN_COLS exactly when the tenth metatile is done. X is id*4, the
    // sub-row table index, and the two advance independently -- which is the
    // whole point of the transpose.
    ldy #0
!col:
    tya
    lsr
    lsr
    tax
    lda trIds,x
    asl
    asl
    tax                                 // X = id * METATILE_W
trRead0:
    lda trTiles,x                       // high byte patched per row
    sta (scrPtr),y
    inx
    iny
trRead1:
    lda trTiles,x
    sta (scrPtr),y
    inx
    iny
trRead2:
    lda trTiles,x
    sta (scrPtr),y
    inx
    iny
trRead3:
    lda trTiles,x
    sta (scrPtr),y
    iny
    cpy #SCREEN_COLS
    bne !col-
    rts

.if (* > $6c00) {
    .error "the terrain code has outgrown its $6800 segment"
}
