// ===========================================================================
// turrets.asm — the old game's static background-character turrets
// ===========================================================================
// MAIN THREAD ONLY. The raster executor never reads one byte of this file,
// this file never writes a VIC register, and it never touches a logical
// sprite, the object pool, a mux batch or a sprite pointer. A turret is four
// CHARACTER CODES in a screen page and nothing else, which is what "background
// character" means here and why the sprite renderer stays unaware that turrets
// exist at all.
//
//     scrollTick          decides which back-page row is due
//     regenTick           calls renderRow ROWS_PER_TICK times a frame
//       renderTerrainRow    the base terrain for that stage row
//       turretOverlayRow    <- here: the turret cells, if any, over the top
//     scrollPublish       the frame record, unchanged
//     exFrame             adopts $d018 / the page, unchanged
//
// COMPOSITION HAPPENS DURING HIDDEN-PAGE GENERATION, so the page is coherent
// before it is ever published. Nothing patches the visible screen from
// gameplay code; there is no second scroll coordinate system and no separate
// "turret position" that could disagree with the terrain it sits on.
//
// ---------------------------------------------------------------------------
// WHAT CAME ACROSS, AND FROM WHERE
// ---------------------------------------------------------------------------
// Read out of ~/Desktop/c64Shooter-main.zip, the authoritative old shooter.
//
//   src/generated/level1/stage_turrets.asm  -> src/level1/stage_turrets.asm
//                                              copied BYTE FOR BYTE
//   src/background_turrets.asm              -> the 32 bytes of turretArt
//                                              style TURRET_STATIC_STYLE, and
//                                              the glyph codes, below
//
// The placement file is the level package, like the other three in
// src/level1/; it is auto-generated by the old repo's tools/level_editor and
// it emits no bytes at all -- TURRET_TOTAL plus two assembler lists. The ART
// is engine data in the old repo, not level data, so it lives here.
//
// THE AUTHORED TRUTH, verified against the source rather than remembered:
//
//   TURRET_TOTAL  8
//   turretCols    17, 25, 29,  9, 25, 13, 25, 13
//   turretRows   345,337,225,217,117,109, 25,  5
//
//   "world row = metatileRow * 4 + 1,  world col = metatileCol * 4 + 1"
//                                        -- stage_turrets.asm's own header
//
// A turret is a 2x2 block of background characters:
//
//   world row R   , col C     TL = 226      col C+1   TR = 227
//   world row R+1 , col C     BL = 228      col C+1   BR = 229
//
// which is exactly what the old installTurretRow wrote: TURRET_GLYPH_BASE and
// +1 on the authored row, +2 and +3 on the row after it.
// ===========================================================================

#import "level1/stage_turrets.asm"      // TURRET_TOTAL, turretCols, turretRows.
                                        // Constants and lists only: it emits no
                                        // bytes and moves no program counter.

// ---------------------------------------------------------------------------
// The glyph namespace. 226..229, KEPT FROM THE OLD GAME.
// ---------------------------------------------------------------------------
// The old repo's TURRET_GLYPH_BASE is 226 and its four body codes are 226..229
// (TL, TR, BL, BR). Nothing in THIS engine's charset window wants those codes:
// terrain owns 96..167 and the rest of the window is zero-filled by the PRG.
// So they are kept, for the same reason the terrain glyph base 96 was kept --
// a migrated constant that can be diffed against its source is worth more than
// a tidier one that cannot.
.const TURRET_GLYPH_BASE = 226
.const TURRET_GLYPH_SPAN = 4            // TL, TR, BL, BR -- ONE shared body
.const TURRET_BODY_W     = 2            // characters
.const TURRET_BODY_H     = 2

.if (TURRET_GLYPH_BASE < TERRAIN_GLYPH_BASE + TERRAIN_GLYPH_COUNT) {
    .error "the turret glyphs overlap the terrain glyph namespace"
}
.if (TURRET_GLYPH_BASE + TURRET_GLYPH_SPAN > 256) {
    .error "the turret glyph namespace runs past character code 255"
}

// ---------------------------------------------------------------------------
// The body bitmaps, ASSEMBLED STRAIGHT INTO THE CHARSET WINDOW.
// ---------------------------------------------------------------------------
// The old game copied these 32 bytes into its charset at run time, from
// publishTurretGlyphs, because its turret body could be re-published as the
// art changed. Nothing here ever changes them: one shared static body, four
// codes, whatever the turret count. So they are simply assembled at their
// final address and there is no publication step, no dirty flag and no
// per-frame charset work of any kind.
//
// Source: src/background_turrets.asm, turretArt style TURRET_STATIC_STYLE (4,
// the DOWN-facing body). The other six styles are the old game's aiming
// variants and its hit flash; the shared-glyph renderer used style 4 alone and
// so does this. They are 2-bit multicolour bitmaps against the stage palette:
// the dome is mostly bit pair 11 (colour RAM), the shading is 01 ($d022) and
// the barrel stub at the bottom centre is 10 ($d023).
.const TURRET_GLYPHS = TERRAIN_CHARSET + TURRET_GLYPH_BASE * 8

.if (TURRET_GLYPHS + TURRET_GLYPH_SPAN * 8 > TERRAIN_CHARSET + $800) {
    .error "the turret glyphs run past the end of the terrain charset window"
}
.if (TURRET_GLYPHS < terrainGlyphsEnd) {
    .error "the turret glyphs overlap the terrain glyph bitmaps"
}

* = TURRET_GLYPHS "turret glyphs"
turretGlyphs:
    .byte $00,$00,$0f,$3f,$ff,$ff,$ff,$ff   // 226  TL
    .byte $00,$00,$f0,$fc,$ff,$ff,$ff,$ff   // 227  TR
    .byte $ff,$ff,$ff,$55,$55,$15,$02,$02   // 228  BL
    .byte $ff,$ff,$ff,$55,$55,$54,$80,$80   // 229  BR
turretGlyphsEnd:

.if (turretGlyphsEnd - turretGlyphs != TURRET_GLYPH_SPAN * 8) {
    .error "the turret body must be four 8-byte glyphs"
}

// ===========================================================================
// THE AUTHORED PLACEMENT, REDUCED TO WHAT THE ROW RENDERER ASKS
// ===========================================================================
// The renderer's question, once per generated row, is "does a turret cell
// belong in THIS stage row?". The answer is no for 404 of the level's 420
// rows, so what matters is how cheaply it can be said.
//
// The editor's own rule does most of it. Every authored row is
// metatileRow * 4 + 1, so a turret body occupies SUB-ROWS 1 AND 2 of a single
// metatile row and can never straddle a metatile boundary:
//
//   sub-row 0 or 3   -> no turret is possible. HALF the rows leave in fifteen
//                       cycles without touching a table.
//   sub-row 1 or 2   -> the question is now about the metatile row alone.
//
// THE RULE IS GUARDED, NOT ASSUMED. If a future level authors a row that is
// not metatileRow*4+1 the build fails below rather than silently dropping a
// turret, which is the whole difference between an optimisation and a bug.
//
// The remaining half was a linear scan of the eight authored rows, and it was
// MEASURED rather than assumed to be cheap: a row cost 1,048 cycles with the
// scan against 942 with it skipped -- 106 cycles on every second generated
// row, about 210 a frame at four rows a tick. Small, and entirely avoidable.
//
// So the question is answered by a TABLE INDEXED BY METATILE ROW, built at
// assembly time from the authored list: one byte per metatile row, holding the
// turret that lives there or $ff. The scan becomes `lda abs,x / bmi`, the same
// row now measures 968, and the inner path stops depending on the turret COUNT
// at all. It costs STAGE_METATILE_ROWS bytes outside VIC bank 0 -- 105 for
// level 1 -- which is the same trade src/terrain.asm already makes twice, for
// the transposed sub-row tables and the metatile-ID cache.
.const TURRET_ROW_PHASE = 1             // authored rows are 1 (mod METATILE_H)
.const TURRET_NONE      = $ff           // no turret in this metatile row

.for (var t = 0; t < TURRET_TOTAL; t++) {
    .if (mod(turretRows.get(t), METATILE_H) != TURRET_ROW_PHASE) {
        .error "authored turret row is not metatileRow * METATILE_H + 1"
    }
    .if (turretRows.get(t) + TURRET_BODY_H - 1 >= TERRAIN_STAGE_ROWS) {
        .error "an authored turret body runs off the bottom of the stage"
    }
    .if (turretCols.get(t) + TURRET_BODY_W > SCREEN_COLS) {
        .error "an authored turret body runs off the right of the screen"
    }
    .for (var u = 0; u < t; u++) {
        .if (floor(turretRows.get(u) / METATILE_H)
             == floor(turretRows.get(t) / METATILE_H)) {
            .error "two authored turrets share a metatile row: turretAtMetaRow holds only one"
        }
    }
}
.if (TERRAIN_STAGE_ROWS > 511) {
    .error "turretOverlayRow derives metatileRow with two shifts of a <=9-bit stage row"
}
.if (STAGE_METATILE_ROWS > 255) {
    .error "turretAtMetaRow is indexed by one byte: the stage has too many metatile rows"
}
.if (TURRET_TOTAL > 127) {
    .error "a turret index must stay positive: turretOverlayRow tests TURRET_NONE with bmi"
}
.if (turretCols.size() != TURRET_TOTAL || turretRows.size() != TURRET_TOTAL) {
    .error "the authored turret lists do not match TURRET_TOTAL"
}

// The lookup, built by the assembler: start every metatile row at
// TURRET_NONE, then stamp in each authored turret. Written as a stamping pass
// rather than a per-row search because a search has to answer "which of the
// eight, if any" for every row, and this simply says where each of the eight
// goes.
//
// FLOOR IS NOT DECORATION. KickAssembler's `/` is floating point: 345 / 4 is
// 86.25, not 86, so `turretRows.get(t) / METATILE_H == m` is false for every
// m and the first version of this table came out entirely TURRET_NONE -- a
// silently empty table, a build with no errors and eight invisible turrets.
// The value survived being emitted by .fill only because .fill truncates to a
// byte on the way out. Every division of an authored row in this file is
// floored explicitly, including the ones inside the guards.
.var turretAtRow = List()
.for (var m = 0; m < STAGE_METATILE_ROWS; m++) {
    .eval turretAtRow.add(TURRET_NONE)
}
.for (var t = 0; t < TURRET_TOTAL; t++) {
    .eval turretAtRow.set(floor(turretRows.get(t) / METATILE_H), t)
}

* = $6d00 "turret tables"

// THE LOOKUP. One byte per metatile row of the stage: a turret index, or
// TURRET_NONE. This is the only thing the row renderer consults.
turretAtMetaRow: .fill STAGE_METATILE_ROWS, turretAtRow.get(i)

// metatileRow, derived from the authored world row. Not read by the renderer
// -- the table above already answers its question -- but it is what the table
// is built from, and a test reads it to prove the two agree.
turretMetaRow: .fill TURRET_TOTAL, floor(turretRows.get(i) / METATILE_H)
turretCol:     .fill TURRET_TOTAL, turretCols.get(i)
turretTablesEnd:

.if (turretTablesEnd > $6e00) {
    .error "the turret tables have grown into the turret state at $6e00"
}

// ===========================================================================
// State. MAIN THREAD ONLY, and as close to none as the contract allows.
// ===========================================================================
// ONE BYTE A TURRET, and it is not needed for presentation -- every generated
// cell is a pure function of the authored data and the stage row. It exists to
// establish the restoration contract NOW, while it is free, rather than
// retrofitting one around a destruction system later:
//
//     base terrain  +  turret overlay  =  generated page
//
//     alive -> terrain + turret
//     dead  -> terrain only
//
// Because the overlay is applied ON TOP of a freshly decoded row and the
// authored terrain is never modified, clearing a turret's byte is the whole of
// "put the terrain back": the next regeneration of either page produces the
// underlying terrain with nothing to repair. A future destruction system needs
// only to (a) clear the byte and (b) poke the four cells of the DISPLAYED page
// once, at a safe point in the frame, with the codes renderTerrainRow would
// have written -- which are recoverable at any time because the decode is a
// pure function of the stage row. No cached "ground codes" table, no repair
// path, no state that can go stale.
//
// NOTHING IN THIS SLICE EVER CLEARS A BYTE. There is no firing, no collision,
// no damage and no destruction here; turretInit sets all eight and they stay
// set. The contract is the deliverable, not a gameplay system.
* = $6e00 "turret state"
turretAlive:   .fill TURRET_TOTAL, 1

trtHalf:       .byte 0                  // 0 = the authored row (TL/TR),
                                        // 1 = the row below it (BL/BR)
turretStateEnd:

.if (turretStateEnd > $6e40) {
    .error "the turret state has outgrown its $6e00 segment"
}

* = $6e40 "turret code"

// ---------------------------------------------------------------------------
// turretInit — mark every authored turret alive. Called once from entry,
// BEFORE scrollInit, because scrollInit builds both pages through renderRow
// and a turret inside the boot aperture must be composed into them.
// ---------------------------------------------------------------------------
turretInit:
    lda #1
    ldx #TURRET_TOTAL - 1
!alive:
    sta turretAlive,x
    dex
    bpl !alive-
    rts

// ---------------------------------------------------------------------------
// turretOverlayRow — the turret cells of one stage row, over fresh terrain.
//
// Entry:  scrPtr       -> the back page's row, set up by renderRow
//         rrStageLo/Hi =  the stage character row, already reduced mod
//                         STAGE_ROWS by renderBackgroundRow, and already
//                         decoded into 40 terrain codes by renderTerrainRow
// Exit:   0 or 2 character codes written. No colour RAM. No VIC register.
//         No sprite, no logical object, no batch.
//
// Two cells, never four: a body spans two stage rows and each row is generated
// on its own call, so this writes the top pair or the bottom pair, never both.
// ---------------------------------------------------------------------------

// The answer for 404 of the level's 420 rows, and for every row of a stage
// with no turrets at all. It sits BEFORE the entry point so all three of the
// early exits below branch backwards into it and none needs a jmp.
turretOverlayNone:
    rts

turretOverlayRow:
    // ---- which half of a body could this row be? --------------------------
    // sub-row 1 -> the top pair, sub-row 2 -> the bottom pair, 0 and 3 -> no.
    // Subtracting the phase first turns "is it 1 or 2" into one unsigned
    // compare instead of two equality tests.
    lda rrStageLo
    and #METATILE_H - 1
    sec
    sbc #TURRET_ROW_PHASE
    cmp #TURRET_BODY_H
    bcs turretOverlayNone               // sub-row 0 or 3: nothing here, and
    sta trtHalf                         // this is where half the rows leave

    // ---- metatileRow = stageRow / METATILE_H, and it fits a byte ----------
    // The stage row is at most nine bits (the guard above says so), so the
    // high byte contributes exactly one bit and two shifts land the whole
    // answer in A. 105 metatile rows means A is at most 104.
    lda rrStageHi
    lsr                                 // C = bit 8 of the stage row
    lda rrStageLo
    ror                                 // A = stageRow >> 1
    lsr                                 // A = stageRow >> 2 = metatileRow
    tax

    // ---- one lookup ------------------------------------------------------
    // TURRET_NONE is $ff and a turret index is at most 7, so the "is there
    // one" test is the sign bit of the byte just read.
    lda turretAtMetaRow,x
    bmi turretOverlayNone
    tax                                 // X = the turret, for every table below

    lda turretAlive,x
    beq turretOverlayNone               // destroyed: the row keeps the terrain
                                        // renderTerrainRow just decoded, and
                                        // that IS the restoration path

    ldy turretCol,x                     // the body's left column
    lda trtHalf
    beq !top+
    lda #TURRET_GLYPH_BASE + TURRET_BODY_W
    bne !write+                         // always taken: 228 is not zero
!top:
    lda #TURRET_GLYPH_BASE
!write:
    sta (scrPtr),y                      // TL or BL
    clc
    adc #1
    iny
    sta (scrPtr),y                      // TR or BR
    rts

.if (* > $6f00) {
    .error "the turret code has outgrown its $6e40 segment"
}
